"""Forge: build, register, and launch a NEW AIMEAT crew from generated code.

This is the machinery behind the "agent that makes agents" (crews/crew_forge_crew.py).
A builder agent calls the two tools from `make_forge_tools()`:

  1. write_and_validate_crew(agent_name, build_domain_code, extra_imports)
     -> writes crews/<name>_crew.py on the locked scaffold and validates it in a
        subprocess; returns VALID or the error to fix (call again until VALID).
  2. register_and_launch_crew(agent_name)
     -> `aimeat connect add` for the new agent, then launches it under the watchdog
        as a detached background process; returns the report (incl. the approve step).

The generated crew reuses crewaimeat.aimeat_crew.run_crew, so only build_domain is ever
written by the LLM — the AIMEAT wiring stays the validated scaffold.
"""

from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path

from crewai.tools import tool

# How the assembled crew file looks. The LLM supplies only build_domain (+ optional
# helper defs and extra imports); everything else is fixed scaffold wiring.
_FILE_TEMPLATE = '''\
"""{agent_name}: generated by crew-forge on the AIMEAT scaffold (crewaimeat).

Only build_domain below is crew-specific; crewaimeat.aimeat_crew.run_crew provides the
AIMEAT wiring (onboarding, daemon, liaison publish/complete, live progress, date
injection). See SCAFFOLD_CANON.md. Register + approve before running:
  npx aimeat@latest connect add --agent {agent_name} --mode task-runner --url https://aimeat.io --owner <your-aimeat-account>

Run: uv run python crews/{fname}
"""

from __future__ import annotations
{extra_imports}
from crewai import Agent, Task

from crewaimeat.aimeat_crew import BuildContext, CrewSpec, run_crew
from crewaimeat.crew import _web_tools  # Tavily web search if TAVILY_API_KEY is set, else []

AGENT_NAME = "{agent_name}"


{build_domain_code}


def run() -> None:
    run_crew(CrewSpec(agent_name=AGENT_NAME, build_domain=build_domain))


if __name__ == "__main__":
    run()
'''


def _project_root() -> Path:
    return Path.cwd()


def _fname(agent_name: str) -> str:
    """crews filename for an agent name, matching the new-crew CLI convention."""
    return re.sub(r"[^a-z0-9]+", "_", agent_name.lower()).strip("_") + "_crew.py"


def _rel(path: Path) -> str:
    try:
        return path.relative_to(_project_root()).as_posix()
    except ValueError:
        return str(path)


def write_crew_file(agent_name: str, build_domain_code: str, extra_imports: str = "") -> Path:
    """Assemble crews/<name>_crew.py from the scaffold template + generated build_domain.

    Overwrites freely so the validate-fix-retry loop can rewrite the same file.
    """
    crews_dir = _project_root() / "crews"
    crews_dir.mkdir(exist_ok=True)
    fname = _fname(agent_name)
    extra = ("\n" + extra_imports.strip() + "\n") if extra_imports.strip() else ""
    content = _FILE_TEMPLATE.format(
        agent_name=agent_name,
        fname=fname,
        extra_imports=extra,
        build_domain_code=build_domain_code.strip("\n"),
    )
    dest = crews_dir / fname
    dest.write_text(content, encoding="utf-8")
    return dest


def validate_crew_file(path: Path) -> tuple[bool, str]:
    """Run the subprocess validator. Returns (ok, detail)."""
    try:
        proc = subprocess.run(
            [sys.executable, "-m", "crewaimeat._validate_crew", str(path)],
            capture_output=True,
            text=True,
            timeout=180,
            cwd=str(_project_root()),
        )
    except Exception as exc:  # noqa: BLE001
        return False, f"validator could not run: {exc}"
    out = (proc.stdout or "").strip() or (proc.stderr or "").strip()
    return proc.returncode == 0, out


def register_agent(agent_name: str, owner: str, url: str = "https://aimeat.io") -> tuple[bool, str]:
    """Register a task-runner agent via the latest connector. Approval stays a human step.

    Uses `npx aimeat@latest connect add` (the local `aimeat` may be an older connector that
    predates `connect add` / `--mode`). The owner then approves the agent on AIMEAT.
    """
    base = [
        "npx", "aimeat@latest", "connect", "add",
        "--agent", agent_name,
        "--mode", "task-runner",
        "--url", url,
        "--owner", owner,
    ]
    cmd = ["cmd", "/c", *base] if os.name == "nt" else base
    try:
        # npx may fetch the package on first use, so allow generous time.
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
    except Exception as exc:  # noqa: BLE001
        return False, f"connect add could not run: {exc}"
    out = ((proc.stdout or "") + (proc.stderr or "")).strip()
    return proc.returncode == 0, out


def _is_running_file(fname: str) -> bool:
    """True if some process command line references this crew filename (daemon or watchdog)."""
    try:
        if os.name == "nt":
            ps = (
                "Get-CimInstance Win32_Process | "
                f"Where-Object {{ $_.CommandLine -like '*{fname}*' }} | "
                "Select-Object -First 1 -ExpandProperty ProcessId"
            )
            proc = subprocess.run(
                ["powershell", "-NoProfile", "-Command", ps],
                capture_output=True, text=True, timeout=30,
            )
            return bool((proc.stdout or "").strip())
        proc = subprocess.run(["pgrep", "-f", fname], capture_output=True, text=True, timeout=30)
        return proc.returncode == 0
    except Exception:  # noqa: BLE001
        return False


def is_crew_running(agent_name: str) -> bool:
    return _is_running_file(_fname(agent_name))


def launch_crew(rel_path: str) -> tuple[int | None, str]:
    """Launch the crew under the watchdog as a detached background process.

    Returns (pid, log_path). The process outlives this crew's task and keeps the new
    crew alive across restarts.
    """
    root = _project_root()
    logs = root / "logs"
    logs.mkdir(exist_ok=True)
    log_path = logs / (Path(rel_path).stem + ".watchdog.log")
    logf = open(log_path, "ab")
    try:
        if os.name == "nt":
            script = root / "scripts" / "watchdog.ps1"
            cmd = [
                "powershell", "-NoProfile", "-ExecutionPolicy", "Bypass",
                "-File", str(script), rel_path,
            ]
            # DETACHED_PROCESS | CREATE_NEW_PROCESS_GROUP: survive the parent daemon.
            flags = 0x00000008 | 0x00000200
            proc = subprocess.Popen(
                cmd, cwd=str(root), stdout=logf, stderr=logf,
                stdin=subprocess.DEVNULL, creationflags=flags, close_fds=True,
            )
        else:
            script = root / "scripts" / "watchdog.sh"
            proc = subprocess.Popen(
                ["bash", str(script), rel_path], cwd=str(root), stdout=logf,
                stderr=logf, stdin=subprocess.DEVNULL, start_new_session=True, close_fds=True,
            )
        return proc.pid, _rel(log_path)
    except Exception as exc:  # noqa: BLE001
        logf.close()
        return None, f"launch failed: {exc}"


# --------------------------------------------------------------------------- #
# CrewAI tools handed to the builder agent
# --------------------------------------------------------------------------- #
@tool("write_and_validate_crew")
def write_and_validate_crew(agent_name: str, build_domain_code: str, extra_imports: str = "") -> str:
    """Write crews/<agent_name>_crew.py on the locked AIMEAT scaffold and validate it.

    Pass ONLY the build_domain function in build_domain_code:
        def build_domain(ctx): ...; return (agents, tasks)
    (plus any helper defs it needs). The scaffold imports, AGENT_NAME, run() and the
    __main__ guard are added for you; Agent, Task, BuildContext and _web_tools are
    already imported in the file. Put any additional import lines in extra_imports.

    Returns 'VALID: ...' when it compiles and build_domain returns a non-empty
    (agents, tasks). Otherwise returns 'INVALID: <error>' — fix the build_domain code
    and call this tool again until it is VALID. Overwrites the file each call.
    """
    path = write_crew_file(agent_name, build_domain_code, extra_imports)
    ok, detail = validate_crew_file(path)
    rel = _rel(path)
    if ok:
        return f"VALID: wrote {rel}. {detail}"
    return (
        f"INVALID ({rel}): {detail}\n"
        "Fix the build_domain code and call write_and_validate_crew again."
    )


@tool("register_and_launch_crew")
def register_and_launch_crew(agent_name: str) -> str:
    """Register the new agent on AIMEAT and launch its crew under the watchdog.

    Call this ONCE, only after write_and_validate_crew returned VALID. Runs
    `aimeat connect add` (owner from the AIMEAT_OWNER env var) and then starts the crew
    as a detached background process. Returns a report including the approve step the
    human must complete on the AIMEAT dashboard and the watchdog log path.
    """
    rel = f"crews/{_fname(agent_name)}"
    if not (_project_root() / rel).exists():
        return f"ERROR: {rel} does not exist. Call write_and_validate_crew first."

    owner = os.getenv("AIMEAT_OWNER", "").strip()
    if owner:
        reg_ok, reg_out = register_agent(agent_name, owner)
        reg_line = (
            f"Registered '{agent_name}' (owner {owner})."
            if reg_ok
            else f"connect add did not report success — output:\n{reg_out or '(none)'}"
        )
    else:
        reg_line = (
            "Registration SKIPPED: AIMEAT_OWNER is not set. Set it in .env, then run:\n"
            f"  npx aimeat@latest connect add --agent {agent_name} --mode task-runner "
            "--url https://aimeat.io --owner <your-aimeat-account>"
        )

    pid, log = launch_crew(rel)
    launch_line = (
        f"Launched under the watchdog (pid {pid}). Log: {log}"
        if pid is not None
        else f"Launch problem: {log}"
    )
    return (
        f"NEW AGENT: {agent_name}\n"
        f"File: {rel}\n"
        f"{reg_line}\n"
        f"{launch_line}\n"
        "ACTION REQUIRED — approve the agent so its token activates: open the AIMEAT "
        f"dashboard (Profile -> Agents), find '{agent_name}', and approve it. The crew comes "
        "online within ~30s of approval. If the watchdog stopped before you approved, re-run:\n"
        f"  ./scripts/watchdog.ps1 {rel}\n"
        f"Then queue a task for '{agent_name}' from its Tasks tab to put it to work."
    )


@tool("restart_crew")
def restart_crew(agent_name: str) -> str:
    """Bring an already-built crew back online: if its process is down, launch it under
    the watchdog; if it is already running, leave it. Use this for 'restart' / 'relaunch'
    / 'bring back' requests. The crew file crews/<agent_name>_crew.py must already exist
    (build it first with the forge tools if it does not).
    """
    rel = f"crews/{_fname(agent_name)}"
    if not (_project_root() / rel).exists():
        return f"ERROR: {rel} does not exist. Build the crew first, then restart it."
    if is_crew_running(agent_name):
        return f"'{agent_name}' is already running ({rel}); left it as is."
    pid, log = launch_crew(rel)
    if pid is None:
        return f"Tried to start '{agent_name}' but the launch failed: {log}"
    return (
        f"Started '{agent_name}' under the watchdog (pid {pid}). Log: {log}. "
        "If its token still needs approval it will wait until you approve it on AIMEAT, "
        "then come online by itself."
    )


@tool("list_crews")
def list_crews() -> str:
    """List the crews in crews/ and whether each one appears to be running. Use this for
    'list my agents' / 'what's running' / status requests.
    """
    crews_dir = _project_root() / "crews"
    files = sorted(crews_dir.glob("*_crew.py")) if crews_dir.exists() else []
    if not files:
        return "No crews found in crews/."
    lines = [f"  - {f.name}: {'running' if _is_running_file(f.name) else 'stopped'}" for f in files]
    return "Crews in crews/:\n" + "\n".join(lines)


@tool("reauth_crew")
def reauth_crew(agent_name: str) -> str:
    """Re-run AIMEAT authorization for an existing agent so the owner can approve it again.
    Use after an accidental deny, or when a token expired/was revoked. Re-registers via
    `npx aimeat@latest connect add`; the owner then re-approves it in the dashboard.
    Owner is read from the AIMEAT_OWNER environment variable.
    """
    owner = os.getenv("AIMEAT_OWNER", "").strip()
    if not owner:
        return (
            "AIMEAT_OWNER is not set, so I cannot re-auth. Set it in .env, then run:\n"
            f"  npx aimeat@latest connect add --agent {agent_name} --mode task-runner "
            "--url https://aimeat.io --owner <your-aimeat-account>"
        )
    ok, out = register_agent(agent_name, owner)
    return (
        f"Re-auth started for '{agent_name}'. Approve it on AIMEAT (Profile -> Agents) and it "
        f"comes back online by itself. Connector output:\n{out or '(none)'}"
    )


def make_forge_tools() -> list:
    """The tools the crew-forge builder agent uses to materialize a new crew."""
    return [write_and_validate_crew, register_and_launch_crew]


def make_manage_tools() -> list:
    """The tools crew-forge uses to operate the fleet (restart a downed crew, report status, re-auth)."""
    return [restart_crew, list_crews, reauth_crew]
