"""Emit a DECLARATIVE crew from a JSON definition — the exec-free crew-forge path.

Where ``crewaimeat.forge`` writes a Python ``build_domain`` and subprocess-EXECS it to find out whether
it's valid, this writes a validated JSON crew def (``crew_defs/<base>.json``) plus a thin loader
(``crews/<base>_crew.py``) that runs it through ``crewaimeat.crew_def``. Validation is
``validate_crew_doc`` + a construction smoke test — both IN-PROCESS, so generated code is never exec'd
just to check it. The thin loader is an ordinary ``crews/*_crew.py`` (``AGENT_NAME`` + ``run()`` +
``build_domain``), so fleet discovery / reconcile / register / launch keep working unchanged — in
particular ``register_and_launch_crew`` needs no change (it re-validates the loader via the same
subprocess path, which imports it and interprets the doc).
"""

from __future__ import annotations

import json
import re
from typing import Any

from crewaimeat.crew_def import build_domain_from_json, validate_crew_doc

# The thin loader written to crews/<base>_crew.py. It carries AGENT_NAME + build_domain + run() so it is
# indistinguishable from a hand-written crew to fleet discovery and the subprocess validator, yet all the
# real design is DATA in the JSON. Braces are only ever the {field} placeholders below (no literal '{}').
_LOADER_TEMPLATE = '''"""{agent_name} — a DECLARATIVE crew. Its definition is DATA in crew_defs/{base}.json.

Generated by crew-forge (crewaimeat.forge_json). Agents, tasks, tools, temperature, identity and offer
all live in the JSON — validated before this ever ran live, never exec'd Python. Edit the JSON to change
the crew; this loader stays as-is. See crewaimeat.crew_def.

Run: uv run python crews/{fname}
"""

from __future__ import annotations

from pathlib import Path

from crewaimeat.aimeat_crew import run_crew
from crewaimeat.crew_def import build_domain_from_json, crewspec_from_json, load_crew_doc

AGENT_NAME = "{agent_name}"
_DOC_PATH = Path(__file__).resolve().parent.parent / "crew_defs" / "{base}.json"


def build_domain(ctx):
    """Interpret this crew's JSON definition into (agents, tasks). Kept module-level so the fleet
    validator (crewaimeat._validate_crew) and any direct caller work exactly as for a Python crew."""
    return build_domain_from_json(load_crew_doc(_DOC_PATH), ctx)


def run() -> None:
    run_crew(crewspec_from_json(load_crew_doc(_DOC_PATH)))


if __name__ == "__main__":
    run()
'''


def coerce_doc(crew_json: Any) -> dict | None:
    """Parse an LLM-supplied crew def into a dict, tolerating the common wrappers (a ```json fence, or
    a sentence before/after the object). Returns None if no JSON object can be recovered — the caller
    then reports the parse failure. Already-parsed dicts pass straight through."""
    if isinstance(crew_json, dict):
        return crew_json
    if not isinstance(crew_json, str):
        return None
    try:
        got = json.loads(crew_json)
        return got if isinstance(got, dict) else None
    except ValueError:
        pass
    i, j = crew_json.find("{"), crew_json.rfind("}")
    if 0 <= i < j:
        try:
            got = json.loads(crew_json[i : j + 1])
            return got if isinstance(got, dict) else None
        except ValueError:
            return None
    return None


def _doc_base(agent_name: str) -> str:
    """Filesystem base for an agent name — matches the crews/<base>_crew.py convention (forge._fname)."""
    return re.sub(r"[^a-z0-9]+", "_", agent_name.lower()).strip("_")


def render_loader(agent_name: str) -> str:
    """The thin ``crews/<base>_crew.py`` source that runs ``crew_defs/<base>.json``."""
    base = _doc_base(agent_name)
    return _LOADER_TEMPLATE.format(agent_name=agent_name, base=base, fname=f"{base}_crew.py")


def _sample_ctx() -> Any:
    """A BuildContext with llm=None — the same shape crewaimeat._validate_crew uses for offline
    construction (crewai builds its default LLM lazily at kickoff, so llm=None constructs fine)."""
    from crewaimeat.aimeat_crew import BuildContext

    return BuildContext(task={}, prompt="(sample task text)", llm=None, today="(today)")


def write_json_crew(doc: Any, *, request: str | None = None) -> tuple[bool, str, Any]:
    """Validate a crew doc and, on VALID, write ``crew_defs/<base>.json`` + the thin loader.

    Returns ``(ok, detail, loader_path)``. INVALID returns ``(False, "<errors>", None)`` with NOTHING
    written, so a bad def never reaches the fleet. Validation is exec-free: ``validate_crew_doc`` catches
    schema/wiring problems, then a construction smoke test proves the tools resolve and the tasks build.
    ``request`` is accepted for symmetry with the Python path (forge memory is written by the caller)."""
    # forge helpers imported lazily so this module has no import-time dependency on forge (forge imports
    # forge_json at its top for make_forge_tools — a top-level import back would be a cycle).
    from crewaimeat.forge import _fname, _project_root, _rel

    if not isinstance(doc, dict):
        return False, "INVALID: crew doc must be a JSON object.", None
    errors = validate_crew_doc(doc)
    if errors:
        return False, "INVALID:\n  - " + "\n  - ".join(errors), None
    agent_name = doc["agent_name"]
    try:
        agents, tasks = build_domain_from_json(doc, _sample_ctx())
    except Exception as exc:  # noqa: BLE001 — any construction failure means the doc is not usable live
        return False, f"INVALID: construction failed: {type(exc).__name__}: {exc}", None

    base = _doc_base(agent_name)
    root = _project_root()
    defs_dir = root / "crew_defs"
    crews_dir = root / "crews"
    defs_dir.mkdir(parents=True, exist_ok=True)
    crews_dir.mkdir(parents=True, exist_ok=True)
    doc_path = defs_dir / f"{base}.json"
    doc_path.write_text(json.dumps(doc, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    loader_path = crews_dir / _fname(agent_name)
    loader_path.write_text(render_loader(agent_name), encoding="utf-8")
    return (
        True,
        f"VALID: {len(agents)} agents, {len(tasks)} tasks -> {_rel(doc_path)} + {_rel(loader_path)}",
        loader_path,
    )


def render_schema_brief() -> str:
    """The crew-def SCHEMA + a compact example + the machine's available tool ids — the Architect's spec
    for the declarative (/build-json) path. Tool ids are preflight-gated (forge_catalog), so the Architect
    can never pick a tool that would only fail at run time, exactly like the Python path's catalog brief."""
    from crewaimeat import forge_catalog

    caps = forge_catalog.available_capabilities()
    tool_lines = "\n".join(f"    - {c.id}: {c.purpose}" for c in caps) or "    (no tools available on this machine)"
    return (
        "Design the new crew as a SINGLE JSON object — the crew DEFINITION (data, not code). Shape:\n"
        "{\n"
        '  "agent_name": "<kebab-name>",\n'
        '  "temperature": <0.25 factual | 0.5 mixed | 0.7 creative>,\n'
        '  "process": "sequential",\n'
        '  "discover": <true for a researcher/planner/coordinator that should survey the node first, else false>,\n'
        '  "memory": <true ONLY if the crew must remember across separate runs, else false>,\n'
        '  "tags": ["<kebab subject words>", "role.task-runner"],\n'
        '  "capabilities": {"technical": [{"name": "<skill>", "type": "skill"}],'
        ' "domain": ["<subject words>"], "languages": ["en"]},\n'
        '  "offers": [{"id": "<kebab>", "title": "...", "ask": "what to send + what it returns + what it'
        ' does NOT do (state the negative scope)", "example": "...", "cost": "cheap", "latency": "minutes",'
        ' "repeatability": "accumulative", "verification": "ungated", "consequences": []}],\n'
        '  "agents": [\n'
        '    {"name": "<local-id>", "role": "...", "goal": "...", "backstory": "...",'
        ' "tools": ["<ids you need, or omit>"], "allow_delegation": false}\n'
        "  ],\n"
        '  "tasks": [\n'
        '    {"id": "<local-id>", "agent": "<an agent name>", "description": "...{{ctx.prompt}}...",'
        ' "expected_output": "..."},\n'
        '    {"id": "<local-id>", "agent": "<an agent name>", "description": "...",'
        ' "expected_output": "...", "context": ["<earlier task id>"]}\n'
        "  ]\n"
        "}\n\n"
        "RULES (the validator enforces these — a violation is returned to you to fix):\n"
        '- 2-4 focused agents (role / goal / backstory). Each agent\'s "tools" are TOOL IDS from the list'
        ' below (or omit "tools" for a pure-reasoning agent).\n'
        '- EVERY task needs a string "description" and "expected_output", and an "agent" that matches an'
        ' agent\'s "name".\n'
        "- At least ONE task description MUST inject the request via {{ctx.prompt}} (put it INSIDE the"
        " description string), so the crew acts on what the user actually asked. Prepend {{ctx.today}} to"
        " time-sensitive tasks.\n"
        '- To chain, set "context": [<ids of EARLIER tasks>] — a DAG (never a forward/self reference); the'
        " LAST task's output is the published deliverable.\n"
        "- Do NOT invent fields or placeholders. The only placeholders are {{ctx.prompt}} and {{ctx.today}}.\n\n"
        "AVAILABLE TOOL IDS (attach only what the job genuinely needs; fewer is better):\n" + tool_lines
    )
