"""Forge: build, register, and launch a NEW AIMEAT crew from generated code.

This is the machinery behind the "agent that makes agents" (crews/crew_forge_crew.py).
A builder agent calls the two tools from `make_forge_tools()`:

  1. write_and_validate_crew(agent_name, build_domain_code, extra_imports)
     -> writes crews/<name>_crew.py on the locked scaffold and validates it in a
        subprocess; returns VALID or the error to fix (call again until VALID).
  2. register_and_launch_crew(agent_name)
     -> `aimeat connect add` for the new agent, then launches it under the watchdog
        as a detached background process; returns the report (incl. the approve step).

The generated crew reuses crewaimeat.aimeat_crew.run_crew, so only build_domain is ever
written by the LLM — the AIMEAT wiring stays the validated scaffold.
"""

from __future__ import annotations

import os
import re
import subprocess
import sys
import time
from pathlib import Path

from crewai.tools import tool

from crewaimeat import forge_catalog

# Reads `AGENT_NAME = "..."` from a generated crew file (to check its token/approval).
_AGENT_NAME_RE = re.compile(r'^\s*AGENT_NAME\s*=\s*["\']([^"\']+)["\']', re.M)

# The legacy top-level web-search import, kept for tool-less crews (no capabilities selected). When
# crew-forge wires capabilities it emits a `_tools(ctx)` helper instead, which imports what it needs.
_WEB_IMPORT = "from crewaimeat.crew import _web_tools  # web search: SearXNG if reachable, else keyless DuckDuckGo"

# How the assembled crew file looks. The LLM supplies only build_domain (+ optional
# helper defs and extra imports); everything else is fixed scaffold wiring.
_FILE_TEMPLATE = '''\
"""{agent_name}: generated by crew-forge on the AIMEAT scaffold (crewaimeat).

Only build_domain below is crew-specific; crewaimeat.aimeat_crew.run_crew provides the
AIMEAT wiring (onboarding, daemon, liaison publish/complete, live progress, date
injection). See SCAFFOLD_CANON.md. Register + approve before running:
  npx aimeat@1.34.0 connect --url https://aimeat.io --owner <your-aimeat-account> --agent {agent_name}

Run: uv run python crews/{fname}
"""

from __future__ import annotations
{extra_imports}
from crewai import Agent, Task

from crewaimeat.aimeat_crew import BuildContext, CrewSpec, run_crew
{imports_block}

AGENT_NAME = "{agent_name}"
{readme_block}{tools_block}{identity_block}{offer_block}

{build_domain_code}


def run() -> None:
    run_crew(CrewSpec(agent_name=AGENT_NAME, build_domain=build_domain{readme_arg}{temp_arg}{crewspec_extra}))


if __name__ == "__main__":
    run()
'''


def _embed_readme(readme_md: str) -> str:
    """Embed README markdown as a safe triple-single-quoted Python literal for the generated file.

    Escapes backslashes and any ''' run, and guarantees a trailing newline so the closing quotes
    can never collide with a final quote char. README directives ([[FIGLET..]], [[AVAILABLE_COMMANDS][]])
    are plain text here; the scaffold expands them at publish time.
    """
    body = readme_md.replace("\\", "\\\\").replace("'''", "\\'\\'\\'")
    if not body.endswith("\n"):
        body += "\n"
    return f"README = '''{body}'''"


def _project_root() -> Path:
    return Path.cwd()


def _fname(agent_name: str) -> str:
    """crews filename for an agent name, matching the new-crew CLI convention."""
    return re.sub(r"[^a-z0-9]+", "_", agent_name.lower()).strip("_") + "_crew.py"


def _rel(path: Path) -> str:
    try:
        return path.relative_to(_project_root()).as_posix()
    except ValueError:
        return str(path)


def write_crew_file(
    agent_name: str,
    build_domain_code: str,
    extra_imports: str = "",
    readme_md: str = "",
    temperature: float | None = None,
    subdir: str | None = None,
    capabilities: str | list[str] = "",
    domain: str = "",
    discover: bool = False,
    offer: dict | None = None,
    remember: bool = False,
) -> Path:
    """Assemble crews/<name>_crew.py from the scaffold template + generated build_domain.

    A non-empty `readme_md` is embedded as a README constant and passed to CrewSpec(readme_md=...),
    so the new crew shows a proper README tab. When empty, the scaffold publishes a generated
    default README instead, so the tab is never blank either way. `temperature` (if given) is written
    as CrewSpec(temperature=...) so the new crew runs at a fixed temperature suited to its role
    (creative ~0.7, factual ~0.25) instead of the cool .env default. Overwrites freely so the
    validate-fix-retry loop can rewrite the same file.
    """
    # subdir (e.g. ".candidates") writes to a staging area NOT scanned by reconcile_fleet, so an
    # unapproved evolution candidate is never auto-launched until it's promoted into crews/.
    crews_dir = (_project_root() / "crews" / subdir) if subdir else (_project_root() / "crews")
    crews_dir.mkdir(parents=True, exist_ok=True)
    fname = _fname(agent_name)
    extra = ("\n" + extra_imports.strip() + "\n") if extra_imports.strip() else ""
    if readme_md.strip():
        readme_block = "\n" + _embed_readme(readme_md) + "\n"
        readme_arg = ", readme_md=README"
    else:
        readme_block = ""
        readme_arg = ""
    temp_arg = f", temperature={float(temperature)}" if temperature is not None else ""
    # crew-forge OWNS the tool bindings: emit a `_tools(ctx)` helper for the selected capabilities so
    # the generated build_domain only references _tools(ctx)["<id>"], never the factory calls. When no
    # capability resolves, the file stays tool-less and keeps the legacy _web_tools import available.
    tools_src, _usable, _dropped = forge_catalog.emit_tools_function(capabilities)
    tools_block = ("\n" + tools_src + "\n") if tools_src else ""
    imports_block = "" if tools_src else _WEB_IMPORT
    # Real identity: derive tags + capabilities from the selected tools + the crew's DOMAIN so a forged
    # agent is discoverable by what it does (not the generic onboarding defaults). Emit only when there
    # is signal beyond the bare role tag, so a truly generic crew stays minimal.
    tags, caps_dict = forge_catalog.derive_identity(capabilities, domain)
    if domain.strip() or len(tags) > 1 or caps_dict["technical"]:
        identity_block = f"\n_TAGS = {tags!r}\n_CAPABILITIES = {caps_dict!r}\n"
        identity_arg = ", tags=_TAGS, capabilities=_CAPABILITIES"
    else:
        identity_block = ""
        identity_arg = ""
    # Inline offer: the crew advertises its value on the node without a central offers.py entry.
    if offer:
        offer_block = f"\n_OFFER = {offer!r}\n"
        offer_arg = ", offer=_OFFER"
    else:
        offer_block = ""
        offer_arg = ""
    # memory=True is a CrewSpec-level toggle emitted exactly like discover (the template already renders
    # CrewSpec fields via crewspec_extra). It gives the forged crew persistent CrewAI memory across runs.
    crewspec_extra = (
        (", discover=True" if discover else "") + (", memory=True" if remember else "") + identity_arg + offer_arg
    )
    content = _FILE_TEMPLATE.format(
        agent_name=agent_name,
        fname=fname,
        extra_imports=extra,
        imports_block=imports_block,
        tools_block=tools_block,
        identity_block=identity_block,
        offer_block=offer_block,
        crewspec_extra=crewspec_extra,
        build_domain_code=build_domain_code.strip("\n"),
        readme_block=readme_block,
        readme_arg=readme_arg,
        temp_arg=temp_arg,
    )
    dest = crews_dir / fname
    dest.write_text(content, encoding="utf-8")
    return dest


def validate_crew_file(path: Path) -> tuple[bool, str]:
    """Run the subprocess validator. Returns (ok, detail)."""
    try:
        proc = subprocess.run(
            [sys.executable, "-m", "crewaimeat._validate_crew", str(path)],
            capture_output=True,
            text=True,
            timeout=600,
            cwd=str(_project_root()),
        )
    except Exception as exc:  # noqa: BLE001
        return False, f"validator could not run: {exc}"
    out = (proc.stdout or "").strip() or (proc.stderr or "").strip()
    return proc.returncode == 0, out


def dry_run_build(
    agent_name: str,
    build_domain_code: str,
    *,
    capabilities: str | list[str] = "",
    domain: str = "",
    discover: bool = False,
    offer: dict | None = None,
    remember: bool = False,
    extra_imports: str = "",
    readme_md: str = "",
    temperature: float | None = None,
    subdir: str = ".candidates",
) -> tuple[bool, str, Path]:
    """Write a candidate crew to crews/<subdir>/ and validate it — WITHOUT registering or launching.

    The staging subdir (default ``.candidates``) is not scanned by reconcile_fleet, so a dry-run crew
    is never auto-started, and nothing touches aimeat.io. Returns (ok, detail, path). This is the safe
    way to prove a generated crew compiles + wires its tools + emits its identity; the eval harness and
    tests use it.
    """
    path = write_crew_file(
        agent_name,
        build_domain_code,
        extra_imports,
        readme_md,
        temperature,
        subdir=subdir,
        capabilities=capabilities,
        domain=domain,
        discover=discover,
        offer=offer,
        remember=remember,
    )
    ok, detail = validate_crew_file(path)
    return ok, detail, path


# Broad enough to survive small wording changes in the connector's device-auth output.
_VERIFY_CODE_RE = re.compile(
    r"(?:verification code|one-time code|your code|enter (?:this )?code)[:\s]+([A-Za-z0-9][A-Za-z0-9-]{3,})",
    re.IGNORECASE,
)
_VERIFY_URL_RE = re.compile(r"(https?://\S*(?:verif|activate|device|connect|auth)\S*)", re.IGNORECASE)

# PIN the connector version (not @latest). `@latest` silently auto-updated and broke us (v1.33 removed
# `connect add`); pinning gives reproducible behavior and a deliberate bump when a new connector ships.
AIMEAT_CONNECTOR = "aimeat@1.34.0"


def register_fleet(owner: str, url: str = "https://aimeat.io", agents: list[str] | None = None) -> str:
    """Register every crew (or a given subset) as a task-runner against `url` under `owner`, surfacing
    each agent's device-approval code/URL — the one-command way to stand the SAME fleet up on a SECOND
    node (e.g. a local dev node ``http://localhost:40050``) without hand-editing each crew.

    Run it from the home you want the dev tokens in: the connector writes tokens under AIMEAT_HOME
    (env wins, else ``<cwd>/.aimeat``), so a separate dev clone keeps its tokens isolated from prod.
    Approve each surfaced code in that node's dashboard (Profile -> Agents); each registers
    automatically once approved. One bad registration is reported, not fatal — the rest continue.
    """
    names = agents if agents is not None else [a for a in (_agent_name_of(p) for p in _crew_files()) if a]
    home = os.getenv("AIMEAT_HOME") or str(_project_root() / ".aimeat")
    lines = [f"Registering {len(names)} agent(s) against {url} (owner={owner}, AIMEAT_HOME={home}):"]
    for name in names:
        try:
            _ok, msg = register_agent(name, owner, url)
        except Exception as exc:  # noqa: BLE001 — one bad registration must not abort the rest
            msg = f"FAILED to start: {exc}"
        lines.append(f"  {name:30s} {msg}")
    lines.append("Approve each code in the node's dashboard (Profile -> Agents); each registers once approved.")
    return "\n".join(lines)


# The pristine Popen, stashed at import: register_agent's pytest guard triggers only when a test did
# NOT mock the spawn (the parsing tests replace subprocess.Popen module-wide and must keep working).
_REAL_POPEN = subprocess.Popen


def register_agent(agent_name: str, owner: str, url: str = "https://aimeat.io") -> tuple[bool, str]:
    """Start `connect add` for a new task-runner agent and SURFACE its device verification code + URL.

    `connect add` is an OAuth device flow: it prints a verification code + URL and then polls until
    the owner approves. Capturing that output silently (the old behaviour) hid the code and made the
    call hang. Instead we launch it in the BACKGROUND (it keeps polling and registers once approved),
    read the code + URL it prints within a few seconds, and return them so the owner can approve.
    Non-blocking: returns in ~seconds, not after the full poll.
    """
    # A test that forgot to mock would spawn a REAL device-auth request against the node. The parsing
    # tests mock subprocess.Popen (module-wide), so gate only when the spawn would be the real one.
    if os.environ.get("PYTEST_CURRENT_TEST") and subprocess.Popen is _REAL_POPEN:
        return False, "device-auth skipped under pytest (mock subprocess.Popen in the test)"
    # v1.33+ connector: device-auth is `connect --url --owner --agent`. The old `connect add … --mode
    # task-runner` form is gone — the connector tolerated the extra args but the node rejected the request,
    # so NO code was ever issued and our fallback misreported it as "already registered".
    # npx: resolved via node_engine — a JUST-installed Node.js is on the user PATH only after re-login,
    # and a machine without Node at all gets a clear message instead of a WinError 2 dump.
    from crewaimeat.node_engine import npx_bin

    npx = npx_bin()
    if not npx:
        return False, (
            "Node.js is required to connect an agent but was not found. "
            "Install it from https://nodejs.org/ (the agency's Setup wizard walks you through it)."
        )
    base = [
        npx,
        AIMEAT_CONNECTOR,
        "connect",
        "--url",
        url,
        "--owner",
        owner,
        "--agent",
        agent_name,
    ]
    cmd = ["cmd", "/c", *base] if os.name == "nt" else base
    logs = _project_root() / "logs"
    logs.mkdir(exist_ok=True)
    out_path = logs / f".register_{_fname(agent_name)}.log"
    try:
        outf = open(out_path, "w+b")
        try:
            if os.name == "nt":
                proc = subprocess.Popen(
                    cmd,
                    stdout=outf,
                    stderr=outf,
                    stdin=subprocess.DEVNULL,
                    creationflags=0x08000000,
                    close_fds=True,  # CREATE_NO_WINDOW
                )
            else:
                proc = subprocess.Popen(
                    cmd,
                    stdout=outf,
                    stderr=outf,
                    stdin=subprocess.DEVNULL,
                    start_new_session=True,
                    close_fds=True,
                )
        finally:
            outf.close()  # the child holds its own inherited handle; ours leaked once per Approve click
    except Exception as exc:  # noqa: BLE001
        return False, f"could not start connect add: {exc}"

    code = verify_url = None
    for _ in range(40):  # ~40s: npx fetch + device-auth request, then the code is printed
        time.sleep(1)
        try:
            txt = out_path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            txt = ""
        if not code:
            m = _VERIFY_CODE_RE.search(txt)
            code = m.group(1) if m else None
        if not verify_url:
            m = _VERIFY_URL_RE.search(txt)
            verify_url = m.group(1) if m else None
        if (code and verify_url) or proc.poll() is not None:
            break

    if code and verify_url:
        return (
            True,
            f"APPROVE to activate: open {verify_url} and enter code {code} (it registers automatically once approved).",
        )
    # No code parsed — surface what the connector ACTUALLY printed instead of guessing "already
    # registered" (that misled diagnosis when the device-auth request itself was failing).
    try:
        raw_tail = "\n".join(out_path.read_text(encoding="utf-8", errors="replace").splitlines()[-15:]).strip()
    except OSError:
        raw_tail = ""
    if proc.poll() is None:
        return True, (
            "The connector is waiting for approval but didn't print a code we recognise. "
            f"Its output was:\n{raw_tail or '(no output captured)'}"
        )
    return False, (
        "Device authorization did not complete (the connector exited without a code). "
        f"Its output was:\n{raw_tail or '(no output captured)'}"
    )


def _is_running_file(fname: str) -> bool:
    """True if some process command line references this crew filename FROM THIS checkout.

    REPO-SCOPED: the match also requires this repo's root path (the daemon's cmdline carries it via
    the venv python / absolute watchdog path), so a SIBLING clone running the SAME crew filename — e.g.
    a separate dev fleet — is never mistaken for ours and reconcile relaunches correctly per checkout.
    The root carries a trailing separator boundary so 'crewfive' can't match 'crewfive-dev'.
    """
    root = str(_project_root()).rstrip("\\/")
    try:
        if os.name == "nt":
            # Exclude THIS query's own process ($PID): its command line contains `fname` (the -like
            # pattern), so without the guard the check always matches itself and reports "running".
            root_pat = (root + "\\").replace("'", "''")
            ps = (
                "Get-CimInstance Win32_Process | "
                f"Where-Object {{ $_.ProcessId -ne $PID -and $_.CommandLine -like '*{fname}*' "
                f"-and $_.CommandLine -like '*{root_pat}*' }} | "
                "Select-Object -First 1 -ExpandProperty ProcessId"
            )
            proc = subprocess.run(
                ["powershell", "-NoProfile", "-Command", ps],
                capture_output=True,
                text=True,
                timeout=30,
            )
            return bool((proc.stdout or "").strip())
        # posix: require BOTH this repo's root and the crew filename in the cmdline.
        proc = subprocess.run(
            ["pgrep", "-f", f"{re.escape(root)}/.*{re.escape(fname)}"], capture_output=True, text=True, timeout=30
        )
        return proc.returncode == 0
    except Exception:  # noqa: BLE001
        return False


def is_crew_running(agent_name: str) -> bool:
    return _is_running_file(_fname(agent_name))


def launch_crew(rel_path: str) -> tuple[int | None, str]:
    """Launch the crew under the watchdog as a detached background process.

    Returns (pid, log_path). The process outlives this crew's task and keeps the new
    crew alive across restarts.
    """
    # A detached watchdog outlives the test run and keeps a REAL crew daemon alive on the machine.
    # Tests exercise launch flows by mocking launch_crew itself; this backstop catches a forgotten mock.
    if os.environ.get("PYTEST_CURRENT_TEST"):
        return None, "launch skipped (pytest — mock forge.launch_crew in the test)"
    root = _project_root()
    logs = root / "logs"
    logs.mkdir(exist_ok=True)
    log_path = logs / (Path(rel_path).stem + ".watchdog.log")
    logf = open(log_path, "ab")
    # Put the venv's Scripts/bin dir (where uv.exe lives next to this python.exe) first on
    # PATH so the watchdog's `uv run` resolves even if the parent's PATH lacks it.
    env = os.environ.copy()
    env["PATH"] = str(Path(sys.executable).parent) + os.pathsep + env.get("PATH", "")
    try:
        if os.name == "nt":
            script = root / "scripts" / "watchdog.ps1"
            cmd = [
                "powershell",
                "-NoProfile",
                "-ExecutionPolicy",
                "Bypass",
                "-File",
                str(script),
                rel_path,
            ]
            # CREATE_NO_WINDOW | CREATE_NEW_PROCESS_GROUP: runs hidden and outlives the parent.
            # NOT DETACHED_PROCESS — with that flag PowerShell never executes the script and the
            # log stays empty (verified); CREATE_NO_WINDOW runs it and captures its output.
            flags = 0x08000000 | 0x00000200
            proc = subprocess.Popen(
                cmd,
                cwd=str(root),
                env=env,
                stdout=logf,
                stderr=logf,
                stdin=subprocess.DEVNULL,
                creationflags=flags,
                close_fds=True,
            )
        else:
            script = root / "scripts" / "watchdog.sh"
            proc = subprocess.Popen(
                ["bash", str(script), rel_path],
                cwd=str(root),
                env=env,
                stdout=logf,
                stderr=logf,
                stdin=subprocess.DEVNULL,
                start_new_session=True,
                close_fds=True,
            )
        return proc.pid, _rel(log_path)
    except Exception as exc:  # noqa: BLE001
        logf.close()
        return None, f"launch failed: {exc}"


def _agent_name_of(path: Path) -> str | None:
    """Read AGENT_NAME from a crew file (without importing it)."""
    try:
        m = _AGENT_NAME_RE.search(path.read_text(encoding="utf-8"))
        return m.group(1) if m else None
    except OSError:
        return None


def _crew_files() -> list[Path]:
    """All crew files in crews/ (skipping helpers/probes prefixed with '_')."""
    crews = _project_root() / "crews"
    if not crews.is_dir():
        return []
    return [p for p in sorted(crews.glob("*_crew.py")) if not p.name.startswith("_")]


def reconcile_fleet() -> str:
    """Ensure every approved crew in crews/ is running: launch the stopped ones, skip the
    running ones. Idempotent and reboot-safe — liveness is a live process scan (not stored
    PIDs), so after a restart every crew reads as down and is relaunched exactly once. Only
    crews that are registered AND approved (have a token) are auto-started; others are reported.
    """
    # Host mode: the fleet host runs every agent as a THREAD in one process, so it must NOT also
    # spawn a per-process daemon per crew — that's exactly the duplication the host exists to avoid
    # (and it double-dispatches + fights the per-agent locks). crew-forge calls this on startup, so
    # when it runs inside the host this guard makes reconcile a no-op.
    if os.getenv("AIMEAT_FLEET_HOST"):
        return (
            "Host mode (AIMEAT_FLEET_HOST set): agents run as threads in the fleet host; "
            "skipping per-process reconcile so the host isn't shadowed by a duplicate per-crew fleet."
        )

    from crewaimeat.aimeat_crew import _token_exists  # local import avoids any import cycle

    root = _project_root()
    owner = os.getenv("AIMEAT_OWNER", "").strip() or None
    files = _crew_files()
    if not files:
        return "No crews in crews/ to reconcile."

    # Crude lock so two overlapping reconciles can't double-launch the same crew.
    logs = root / "logs"
    logs.mkdir(exist_ok=True)
    lock = logs / ".fleet.lock"
    try:
        if lock.is_file() and (time.time() - lock.stat().st_mtime) < 90:
            return "A fleet reconcile is already in progress; try again shortly."
        lock.write_text(str(time.time()), encoding="utf-8")
    except OSError:
        pass

    launched, already, needs_approval = [], [], []
    try:
        for path in files:
            name = path.name
            if _is_running_file(name):
                already.append(name)
                continue
            agent = _agent_name_of(path)
            if agent and not _token_exists(agent, owner):
                needs_approval.append(agent)
                continue
            pid, log = launch_crew(f"crews/{name}")
            launched.append(f"{agent or name} (pid {pid})" if pid else f"{name} (FAILED: {log})")
    finally:
        try:
            lock.unlink()
        except OSError:
            pass

    out = [
        f"Fleet reconcile: {len(launched)} launched, {len(already)} already running, "
        f"{len(needs_approval)} need approval."
    ]
    if launched:
        out.append("Launched: " + ", ".join(launched))
    if already:
        out.append("Already running: " + ", ".join(already))
    if needs_approval:
        out.append("Need registration/approval (not started): " + ", ".join(needs_approval))
    return "\n".join(out)


# --------------------------------------------------------------------------- #
# CrewAI tools handed to the builder agent
# --------------------------------------------------------------------------- #
def _capabilities_note(usable: list[str], dropped: list[str]) -> str:
    """A one-line report of which tool capabilities crew-forge wired vs. could not."""
    parts = []
    if usable:
        parts.append("Wired tools you can reference: " + ", ".join(f'_tools(ctx)["{i}"]' for i in usable) + ".")
    if dropped:
        parts.append(
            "NOT wired (unknown, or unavailable on this machine — do NOT reference these): " + ", ".join(dropped) + "."
        )
    return ("\n" + " ".join(parts)) if parts else ""


# --------------------------------------------------------------------------- #
# Precedent memory — crew-forge remembers what it built and recalls it as priors
# --------------------------------------------------------------------------- #
_FORGE_STORE: list = []  # lazy one-shot cache: [PipelineStore | None] once opened (embedder probe once/run)


def _forge_store():
    """crew-forge's own build-experience store (scope=agent: ONE brain across all requesters — orders
    are rarely owner-specific and design experience compounds). None (logged loud once) when no
    embedder is reachable; every precedent feature then just switches off for the run."""
    if not _FORGE_STORE:
        from crewaimeat.pipeline_memory import open_store

        _FORGE_STORE.append(open_store("crew-forge"))
    return _FORGE_STORE[0]


def _precedent_rating(built_agent: str) -> str:
    """The built agent's CURRENT field reputation as a compact suffix (fetched LIVE at recall time so
    a precedent shows today's score, never a stale snapshot). "" when unrated/unreachable — advisory."""
    try:
        # Same-package reuse of the coordinator-side reputation reader (roster gaii map + public
        # selection/benchmark keys) — ratings live on the node, memory only links to them by name.
        from crewaimeat.workflow import _gaii_map, _reputation

        gaii = _gaii_map(AGENT_NAME_FORGE).get(built_agent)
        suffix, _sel, _bench = _reputation(AGENT_NAME_FORGE, built_agent, gaii)
        return suffix or ""
    except Exception as exc:  # noqa: BLE001 — reputation is advisory; a node hiccup must not block a design
        print(f"[forge] precedent rating unavailable for {built_agent} ({type(exc).__name__})", file=sys.stderr)
        return ""


AGENT_NAME_FORGE = "crew-forge"  # forge's own AIMEAT identity (token used for public reputation reads)


def forge_precedent_block(request: str, k: int = 3) -> str:
    """A PRECEDENT prompt block for the Architect: the most similar past orders crew-forge built,
    each with its design summary and live field rating. "" when memory is unavailable, the store is
    empty, or nothing is similar enough — always safe to concatenate."""
    store = _forge_store()
    if store is None or not (request or "").strip():
        return ""
    # 0.5 bar measured empirically (E2E on nomic): a genuinely-similar order scored 0.55, an unrelated
    # one 0.467 — 0.45 let the unrelated one through, 0.5 cuts it while keeping the true match.
    hits = [h for h in store.recall(request, k=k, category="build") if h.score >= 0.5]
    if not hits:
        return ""
    lines = [
        "PRECEDENT — the most similar crews you have designed before, with their CURRENT field "
        "reputation. Use them as priors: lean toward what a well-rated similar build chose "
        "(capabilities, agent count, temperature); do not copy blindly — the catalog and the rules "
        "above still govern, and this order's specifics win:"
    ]
    for i, h in enumerate(hits, 1):
        name = str(h.metadata.get("agent_name") or "?")
        rating = _precedent_rating(name)
        body = h.content if len(h.content) <= 400 else h.content[:400] + " ..."
        lines.append(f"{i}. agent '{name}'{rating}\n   {body}")
    return "\n".join(lines)


def _remember_build(
    request: str,
    agent_name: str,
    *,
    capabilities: str,
    domain: str,
    discover: bool,
    remember: bool,
    temperature: float | None,
    detail: str,
) -> None:
    """Store one VALID build as forge experience (order -> design). Only called with a non-empty
    original request (evals/tests never pass one, so they never write) and only for a VALID result
    (the Builder retries INVALID ones in a loop — storing each retry would spam near-duplicates)."""
    store = _forge_store()
    if store is None:
        return
    import datetime as _dt

    text = (
        f"ORDER: {request.strip()[:600]}\n"
        f"DESIGN: agent={agent_name}; capabilities={capabilities or '(none)'}; domain={domain or '-'}; "
        f"discover={discover}; memory={remember}; temperature={temperature}\n"
        f"RESULT: VALID — {detail[:150]}"
    )
    store.remember(
        text,
        source="forge-build",
        metadata={
            "category": "build",
            "agent_name": agent_name,
            "date": _dt.date.today().isoformat(),
        },
    )


@tool("write_and_validate_crew")
def write_and_validate_crew(
    agent_name: str,
    build_domain_code: str,
    extra_imports: str = "",
    readme_md: str = "",
    temperature: float | None = None,
    capabilities: str = "",
    domain: str = "",
    discover: str = "",
    memory: str = "",
    offer_ask: str = "",
    offer_example: str = "",
    offer_title: str = "",
    request: str = "",
) -> str:
    """Write crews/<agent_name>_crew.py on the locked AIMEAT scaffold and validate it.

    Pass ONLY the build_domain function in build_domain_code:
        def build_domain(ctx): ...; return (agents, tasks)
    (plus any helper defs it needs). The scaffold imports, AGENT_NAME, run() and the
    __main__ guard are added for you; Agent, Task and BuildContext are already imported.
    Put any additional NON-tool import lines in extra_imports.

    TOOLS — pass `capabilities` as the comma-separated ids of the tools the crew needs (from the
    catalog you were given). crew-forge writes a `_tools(ctx)` helper into the file that binds exactly
    those tools; your build_domain gets them via `T = _tools(ctx)` then e.g. `tools=[*T["web"]]`. You do
    NOT import tools or call their factories — reference `_tools(ctx)["<id>"]` for each id you listed.
    Attach only what the job needs; leave capabilities empty for a pure-reasoning crew. Ids that are
    unknown or unavailable on this machine are dropped and reported (do not reference a dropped id).

    IDENTITY — pass `domain` as a few kebab words for the crew's subject area (e.g.
    "competitive-intelligence market-research"), and `discover` as "yes" for a researcher / planner /
    coordinator that should survey the node before acting (else "no"). crew-forge derives real agent
    tags + capabilities from the selected tools + the domain, so the new agent is discoverable by what
    it does instead of shipping the generic onboarding defaults.

    MEMORY — pass `memory` as "yes" ONLY when the crew genuinely needs to REMEMBER across separate runs
    (a personal assistant that recalls preferences, an agent that builds on its own prior work). This is
    CrewAI's built-in persistent memory (embedder-backed) — distinct from the `memory` CAPABILITY, which
    is an in-crew tool for reading/writing the owner's node memory at exact keys. Default "no" — most
    task-runners are stateless and should stay so. PREREQUISITE (state it to the user): memory needs a
    reachable embedder — local ollama with an embedding model pulled (`ollama pull nomic-embed-text`,
    free/private), else NVIDIA_API_KEY (free cloud) or DASHSCOPE_API_KEY (paid). Without one the crew
    fails loud at run time.

    OFFER — pass `offer_ask` (what to send the agent + what it returns + what it does NOT do — state the
    negative scope) and `offer_example` (one concrete example request) so the new agent ADVERTISES its
    value on the node and others can discover + order it. Leave offer_ask empty to advertise nothing.
    crew-forge fills the strict enums and derives a title from the agent name.

    Pass `readme_md` with the crew's README tab markdown (start it with a FIGLET logo, e.g.
    [[FIGLET:slant]["New Crew"]], then a short description and a "How to task me" line). It is
    embedded and published to the agent's README tab. If you omit it, the scaffold publishes a
    generated default README, so the tab is never blank.

    Pass `temperature` to set the new crew's LLM temperature to match its ROLE: creative/generative
    work (writing, naming, jokes, jingles, taglines, brainstorming, storytelling) → ~0.7; factual/
    analytical/precise work (research, code, data, summarization, extraction, fact-checking) → ~0.25;
    mixed → ~0.5. Without it the crew runs at the cool .env default, which under-serves creative work.

    PRECEDENT — pass `request` as the user's ORIGINAL plain-language order (verbatim). A VALID build
    is remembered as forge experience (order -> design), so future similar orders get your design +
    its field rating as a prior. Leave empty only if no original order text exists.

    Returns 'VALID: ...' (plus which tools were wired) when it compiles and build_domain returns a
    non-empty (agents, tasks). Otherwise returns 'INVALID: <error>' — fix the build_domain code and
    call this tool again until it is VALID. Overwrites the file each call.
    """
    usable, dropped = forge_catalog.resolve(capabilities)
    disc = str(discover).strip().lower() in ("yes", "true", "1", "on", "y")
    remember = str(memory).strip().lower() in ("yes", "true", "1", "on", "y")
    offer_meta = forge_catalog.build_offer_meta(agent_name, offer_ask, offer_example, title=offer_title)
    path = write_crew_file(
        agent_name,
        build_domain_code,
        extra_imports,
        readme_md,
        temperature,
        capabilities=capabilities,
        domain=domain,
        discover=disc,
        offer=offer_meta,
        remember=remember,
    )
    ok, detail = validate_crew_file(path)
    rel = _rel(path)
    note = _capabilities_note(usable, dropped)
    if remember:
        # Surface the memory prerequisite at build time (never gate — memory is a runtime concern that
        # fails loud in run_crew if no embedder is reachable). A non-blocking heads-up for the operator.
        try:
            from crewaimeat.embedder_cascade import memory_preflight

            _ok, _why = memory_preflight()
            note += f"\nMEMORY ON: {'embedder ready — ' + _why if _ok else 'PREREQUISITE NOT MET — ' + _why}"
        except Exception as exc:  # noqa: BLE001 — the preflight note is best-effort, never blocks validation
            note += f"\nMEMORY ON: could not check the embedder prerequisite here ({type(exc).__name__}; checked at run time)."
    if ok:
        if request.strip():  # evals/tests pass no request -> no memory writes (offline-safe by design)
            _remember_build(
                request,
                agent_name,
                capabilities=capabilities,
                domain=domain,
                discover=disc,
                remember=remember,
                temperature=temperature,
                detail=detail,
            )
        return f"VALID: wrote {rel}. {detail}{note}"
    return f"INVALID ({rel}): {detail}{note}\nFix the build_domain code and call write_and_validate_crew again."


def register_and_launch(agent_name: str) -> str:
    """Validate, register, and launch a built crew. PLAIN function (callable from code/tests); the
    @tool wrapper below is what the builder agent calls. REFUSES to register/launch a crew that does
    not validate, so a broken crew never reaches the watchdog / crash-loops.
    """
    rel = f"crews/{_fname(agent_name)}"
    path = _project_root() / rel
    if not path.exists():
        return f"ERROR: {rel} does not exist. Call write_and_validate_crew first."

    # Guard: NEVER register/launch a crew that does not validate. write_and_validate_crew is meant to
    # loop to VALID first, but if the builder skipped ahead (or gave up mid-retry), a broken crew would
    # otherwise get registered + crash-loop under the watchdog. Re-validate here and refuse loudly.
    ok, detail = validate_crew_file(path)
    if not ok:
        return (
            f"REFUSED to register/launch '{agent_name}': {rel} does not validate.\n{detail}\n"
            "Fix the build_domain with write_and_validate_crew until it returns VALID, then call this again."
        )

    owner = os.getenv("AIMEAT_OWNER", "").strip()
    if owner:
        _ok, reg_line = register_agent(agent_name, owner)
    else:
        reg_line = (
            "AIMEAT_OWNER is not set — register manually: npx aimeat@1.34.0 connect "
            f"--url https://aimeat.io --owner <your-aimeat-account> --agent {agent_name}"
        )

    if is_crew_running(agent_name):
        launch_line = f"'{agent_name}' is already running; did not launch a duplicate."
    else:
        pid, log = launch_crew(rel)
        launch_line = (
            f"Launched under the watchdog (pid {pid}); it comes online the moment you approve. Log: {log}"
            if pid is not None
            else f"Launch problem: {log}"
        )
    return (
        f"NEW AGENT: {agent_name}  (file: {rel})\n"
        f"ACTION REQUIRED -> {reg_line}\n"
        f"{launch_line}\n"
        f"Once approved, queue a task for '{agent_name}' from its Tasks tab."
    )


@tool("register_and_launch_crew")
def register_and_launch_crew(agent_name: str) -> str:
    """Register the new agent on AIMEAT and launch its crew under the watchdog.

    Call this ONCE, only after write_and_validate_crew returned VALID. It RE-VALIDATES first and refuses
    an invalid crew; on success it runs device-auth (owner from the AIMEAT_OWNER env var) and launches
    the crew as a detached background process. Returns a report including the approve step the human must
    complete on the AIMEAT dashboard and the watchdog log path.
    """
    return register_and_launch(agent_name)


def start_crew(agent_name: str) -> str:
    """Launch a built crew under the watchdog if it is down; if already running, leave it. PLAIN
    function so code/the TUI can call it directly — the @tool wrapper below is for agents (a @tool
    object is not callable, which is why programmatic callers must use this)."""
    rel = f"crews/{_fname(agent_name)}"
    if not (_project_root() / rel).exists():
        return f"ERROR: {rel} does not exist. Build the crew first, then start it."
    if is_crew_running(agent_name):
        return f"'{agent_name}' is already running ({rel}); left it as is."
    pid, log = launch_crew(rel)
    if pid is None:
        return f"Tried to start '{agent_name}' but the launch failed: {log}"
    return (
        f"Started '{agent_name}' under the watchdog (pid {pid}). Log: {log}. "
        "If its token still needs approval it will wait until you approve it on AIMEAT, "
        "then come online by itself."
    )


@tool("restart_crew")
def restart_crew(agent_name: str) -> str:
    """Bring an already-built crew back online: if its process is down, launch it under the
    watchdog; if it is already running, leave it. Use this for 'restart' / 'relaunch' / 'bring back'
    requests. The crew file crews/<agent_name>_crew.py must already exist."""
    return start_crew(agent_name)


def _crew_proc_entries(fname: str) -> list[tuple[int, str]]:
    """[(pid, command_line)] of processes whose command line references this crew filename (excluding
    THIS process). Cross-platform. Only crew processes match — the serve daemon's line is
    'connect serve' (no crew fname), so it is never included here."""
    out: list[tuple[int, str]] = []
    try:
        if os.name == "nt":
            ps = (
                "Get-CimInstance Win32_Process | Where-Object { $_.ProcessId -ne $PID -and "
                "$_.CommandLine -like '*FNAME*' } | "
                'ForEach-Object { "$($_.ProcessId)|$($_.CommandLine)" }'
            ).replace("FNAME", fname)
            r = subprocess.run(["powershell", "-NoProfile", "-Command", ps], capture_output=True, text=True, timeout=30)
            for ln in (r.stdout or "").splitlines():
                if "|" in ln:
                    pid_s, cl = ln.split("|", 1)
                    if pid_s.strip().isdigit():
                        out.append((int(pid_s.strip()), cl))
        else:
            r = subprocess.run(["pgrep", "-af", fname], capture_output=True, text=True, timeout=30)
            for ln in (r.stdout or "").splitlines():
                parts = ln.split(" ", 1)
                if parts and parts[0].isdigit():
                    out.append((int(parts[0]), parts[1] if len(parts) > 1 else ""))
    except Exception:  # noqa: BLE001
        pass
    return out


def _classify_crew_pids(entries: list[tuple[int, str]]) -> tuple[list[int], list[int]]:
    """Split (pid, cmdline) entries into (watchdog_pids, daemon_pids). Pure — unit-tested."""
    wd, dae = [], []
    for pid, cl in entries:
        (wd if re.search(r"watchdog\.(ps1|sh)", cl or "") else dae).append(pid)
    return wd, dae


def _kill_pid_tree(pid: int) -> None:
    """Kill a process (and its child tree on Windows — taskkill /T catches the venv-shim child)."""
    try:
        if os.name == "nt":
            subprocess.run(["taskkill", "/PID", str(pid), "/T", "/F"], capture_output=True, timeout=15)
        else:
            os.kill(pid, 9)
    except Exception:  # noqa: BLE001
        pass


def stop_crew(agent_name: str) -> str:
    """Stop a crew: kill its WATCHDOG first (so it cannot respawn the daemon), then its daemon
    process(es). Touches only this crew's processes (matched by filename) — never the serve daemon."""
    fname = _fname(agent_name)
    entries = _crew_proc_entries(fname)
    if not entries:
        return f"'{agent_name}' is not running (nothing to stop)."
    watchdogs, daemons = _classify_crew_pids(entries)
    for pid in watchdogs:  # watchdog FIRST — otherwise it relaunches the daemon we are about to kill
        _kill_pid_tree(pid)
    for pid in daemons:
        _kill_pid_tree(pid)
    return f"Stopped '{agent_name}': killed {len(watchdogs)} watchdog + {len(daemons)} daemon process(es)."


def recycle_crew(agent_name: str) -> str:
    """A true restart: stop the crew (kill watchdog+daemon) then relaunch it under a fresh watchdog."""
    rel = f"crews/{_fname(agent_name)}"
    if not (_project_root() / rel).exists():
        return f"ERROR: {rel} does not exist. Build the crew first."
    stopped = stop_crew(agent_name)
    pid, log = launch_crew(rel)
    if pid is None:
        return f"{stopped}  Relaunch FAILED: {log}"
    return f"{stopped}  Relaunched (pid {pid}). Log: {log}."


@tool("list_crews")
def list_crews() -> str:
    """List the crews in crews/ and whether each one appears to be running. Use this for
    'list my agents' / 'what's running' / status requests.
    """
    crews_dir = _project_root() / "crews"
    files = sorted(crews_dir.glob("*_crew.py")) if crews_dir.exists() else []
    if not files:
        return "No crews found in crews/."
    lines = [f"  - {f.name}: {'running' if _is_running_file(f.name) else 'stopped'}" for f in files]
    return "Crews in crews/:\n" + "\n".join(lines)


def reauth(agent_name: str) -> str:
    """Re-run AIMEAT authorization for an agent so the owner can approve it again. PLAIN function
    (callable from code/the TUI); the @tool wrapper below is for agents."""
    owner = os.getenv("AIMEAT_OWNER", "").strip()
    if not owner:
        return (
            "AIMEAT_OWNER is not set, so I cannot re-auth. Set it in .env, then run:\n"
            f"  npx aimeat@1.34.0 connect --url https://aimeat.io --owner <your-aimeat-account> "
            f"--agent {agent_name}"
        )
    ok, out = register_agent(agent_name, owner)
    return (
        f"Re-auth started for '{agent_name}'. Approve it on AIMEAT (Profile -> Agents) and it "
        f"comes back online by itself. Connector output:\n{out or '(none)'}"
    )


@tool("reauth_crew")
def reauth_crew(agent_name: str) -> str:
    """Re-run AIMEAT authorization for an existing agent so the owner can approve it again.
    Use after an accidental deny, or when a token expired/was revoked."""
    return reauth(agent_name)


@tool("start_all_crews")
def start_all_crews() -> str:
    """Ensure every approved crew in crews/ is running: launch the stopped ones and skip the
    ones already running. Idempotent and safe to call any time (never double-launches), including
    right after a machine restart to bring the whole fleet back online. Use for /startall, /up.
    """
    return reconcile_fleet()


def make_forge_tools() -> list:
    """The tools the crew-forge builder agent uses to materialize a new crew."""
    return [write_and_validate_crew, register_and_launch_crew]


def make_manage_tools() -> list:
    """The tools crew-forge uses to operate the fleet: restart, re-auth, list, and start-all.

    (Self-evolution lives ON each agent now — the agent self-diagnoses and proposes in its own thread,
    via crewaimeat.evolve; crew-forge's only future role is the mechanical crew-file build, which will
    be a dedicated handler, not these reverted /evolve detour commands.)"""
    return [restart_crew, list_crews, reauth_crew, start_all_crews]
