"""Forge: build, register, and launch a NEW AIMEAT crew from generated code.

This is the machinery behind the "agent that makes agents" (crews/crew_forge_crew.py).
A builder agent calls the two tools from `make_forge_tools()`:

  1. write_and_validate_crew(agent_name, build_domain_code, extra_imports)
     -> writes crews/<name>_crew.py on the locked scaffold and validates it in a
        subprocess; returns VALID or the error to fix (call again until VALID).
  2. register_and_launch_crew(agent_name)
     -> `aimeat connect add` for the new agent, then launches it under the watchdog
        as a detached background process; returns the report (incl. the approve step).

The generated crew reuses crewaimeat.aimeat_crew.run_crew, so only build_domain is ever
written by the LLM — the AIMEAT wiring stays the validated scaffold.
"""

from __future__ import annotations

import os
import re
import subprocess
import sys
import time
from pathlib import Path

from crewai.tools import tool

# Reads `AGENT_NAME = "..."` from a generated crew file (to check its token/approval).
_AGENT_NAME_RE = re.compile(r'^\s*AGENT_NAME\s*=\s*["\']([^"\']+)["\']', re.M)

# How the assembled crew file looks. The LLM supplies only build_domain (+ optional
# helper defs and extra imports); everything else is fixed scaffold wiring.
_FILE_TEMPLATE = '''\
"""{agent_name}: generated by crew-forge on the AIMEAT scaffold (crewaimeat).

Only build_domain below is crew-specific; crewaimeat.aimeat_crew.run_crew provides the
AIMEAT wiring (onboarding, daemon, liaison publish/complete, live progress, date
injection). See SCAFFOLD_CANON.md. Register + approve before running:
  npx aimeat@latest connect add --agent {agent_name} --mode task-runner --url https://aimeat.io --owner <your-aimeat-account>

Run: uv run python crews/{fname}
"""

from __future__ import annotations
{extra_imports}
from crewai import Agent, Task

from crewaimeat.aimeat_crew import BuildContext, CrewSpec, run_crew
from crewaimeat.crew import _web_tools  # Tavily web search if TAVILY_API_KEY is set, else []

AGENT_NAME = "{agent_name}"
{readme_block}

{build_domain_code}


def run() -> None:
    run_crew(CrewSpec(agent_name=AGENT_NAME, build_domain=build_domain{readme_arg}))


if __name__ == "__main__":
    run()
'''


def _embed_readme(readme_md: str) -> str:
    """Embed README markdown as a safe triple-single-quoted Python literal for the generated file.

    Escapes backslashes and any ''' run, and guarantees a trailing newline so the closing quotes
    can never collide with a final quote char. README directives ([[FIGLET..]], [[AVAILABLE_COMMANDS][]])
    are plain text here; the scaffold expands them at publish time.
    """
    body = readme_md.replace("\\", "\\\\").replace("'''", "\\'\\'\\'")
    if not body.endswith("\n"):
        body += "\n"
    return f"README = '''{body}'''"


def _project_root() -> Path:
    return Path.cwd()


def _fname(agent_name: str) -> str:
    """crews filename for an agent name, matching the new-crew CLI convention."""
    return re.sub(r"[^a-z0-9]+", "_", agent_name.lower()).strip("_") + "_crew.py"


def _rel(path: Path) -> str:
    try:
        return path.relative_to(_project_root()).as_posix()
    except ValueError:
        return str(path)


def write_crew_file(
    agent_name: str, build_domain_code: str, extra_imports: str = "", readme_md: str = ""
) -> Path:
    """Assemble crews/<name>_crew.py from the scaffold template + generated build_domain.

    A non-empty `readme_md` is embedded as a README constant and passed to CrewSpec(readme_md=...),
    so the new crew shows a proper README tab. When empty, the scaffold publishes a generated
    default README instead, so the tab is never blank either way. Overwrites freely so the
    validate-fix-retry loop can rewrite the same file.
    """
    crews_dir = _project_root() / "crews"
    crews_dir.mkdir(exist_ok=True)
    fname = _fname(agent_name)
    extra = ("\n" + extra_imports.strip() + "\n") if extra_imports.strip() else ""
    if readme_md.strip():
        readme_block = "\n" + _embed_readme(readme_md) + "\n"
        readme_arg = ", readme_md=README"
    else:
        readme_block = ""
        readme_arg = ""
    content = _FILE_TEMPLATE.format(
        agent_name=agent_name,
        fname=fname,
        extra_imports=extra,
        build_domain_code=build_domain_code.strip("\n"),
        readme_block=readme_block,
        readme_arg=readme_arg,
    )
    dest = crews_dir / fname
    dest.write_text(content, encoding="utf-8")
    return dest


def validate_crew_file(path: Path) -> tuple[bool, str]:
    """Run the subprocess validator. Returns (ok, detail)."""
    try:
        proc = subprocess.run(
            [sys.executable, "-m", "crewaimeat._validate_crew", str(path)],
            capture_output=True,
            text=True,
            timeout=600,
            cwd=str(_project_root()),
        )
    except Exception as exc:  # noqa: BLE001
        return False, f"validator could not run: {exc}"
    out = (proc.stdout or "").strip() or (proc.stderr or "").strip()
    return proc.returncode == 0, out


_VERIFY_CODE_RE = re.compile(r"Verification code:\s*([A-Za-z0-9][A-Za-z0-9-]*)")
_VERIFY_URL_RE = re.compile(r"(https?://\S*verif\S*)")


def register_agent(agent_name: str, owner: str, url: str = "https://aimeat.io") -> tuple[bool, str]:
    """Start `connect add` for a new task-runner agent and SURFACE its device verification code + URL.

    `connect add` is an OAuth device flow: it prints a verification code + URL and then polls until
    the owner approves. Capturing that output silently (the old behaviour) hid the code and made the
    call hang. Instead we launch it in the BACKGROUND (it keeps polling and registers once approved),
    read the code + URL it prints within a few seconds, and return them so the owner can approve.
    Non-blocking: returns in ~seconds, not after the full poll.
    """
    base = [
        "npx", "aimeat@latest", "connect", "add",
        "--agent", agent_name, "--mode", "task-runner", "--url", url, "--owner", owner,
    ]
    cmd = ["cmd", "/c", *base] if os.name == "nt" else base
    logs = _project_root() / "logs"
    logs.mkdir(exist_ok=True)
    out_path = logs / f".register_{_fname(agent_name)}.log"
    try:
        outf = open(out_path, "w+b")
        if os.name == "nt":
            proc = subprocess.Popen(
                cmd, stdout=outf, stderr=outf, stdin=subprocess.DEVNULL,
                creationflags=0x08000000, close_fds=True,  # CREATE_NO_WINDOW
            )
        else:
            proc = subprocess.Popen(
                cmd, stdout=outf, stderr=outf, stdin=subprocess.DEVNULL,
                start_new_session=True, close_fds=True,
            )
    except Exception as exc:  # noqa: BLE001
        return False, f"could not start connect add: {exc}"

    code = verify_url = None
    for _ in range(40):  # ~40s: npx fetch + device-auth request, then the code is printed
        time.sleep(1)
        try:
            txt = out_path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            txt = ""
        if not code:
            m = _VERIFY_CODE_RE.search(txt)
            code = m.group(1) if m else None
        if not verify_url:
            m = _VERIFY_URL_RE.search(txt)
            verify_url = m.group(1) if m else None
        if (code and verify_url) or proc.poll() is not None:
            break

    if code and verify_url:
        return True, f"APPROVE to activate: open {verify_url} and enter code {code} (it registers automatically once approved)."
    if proc.poll() is not None:
        return True, "connect add finished (the agent may already be registered)."
    return True, f"Registration started for '{agent_name}'; approve it in the dashboard (Profile -> Agents)."


def _is_running_file(fname: str) -> bool:
    """True if some process command line references this crew filename (daemon or watchdog)."""
    try:
        if os.name == "nt":
            # Exclude THIS query's own process ($PID): its command line contains `fname`
            # (the -like pattern), so without the guard the check always matches itself
            # and reports "running" for every crew.
            ps = (
                "Get-CimInstance Win32_Process | "
                f"Where-Object {{ $_.ProcessId -ne $PID -and $_.CommandLine -like '*{fname}*' }} | "
                "Select-Object -First 1 -ExpandProperty ProcessId"
            )
            proc = subprocess.run(
                ["powershell", "-NoProfile", "-Command", ps],
                capture_output=True, text=True, timeout=30,
            )
            return bool((proc.stdout or "").strip())
        proc = subprocess.run(["pgrep", "-f", fname], capture_output=True, text=True, timeout=30)
        return proc.returncode == 0
    except Exception:  # noqa: BLE001
        return False


def is_crew_running(agent_name: str) -> bool:
    return _is_running_file(_fname(agent_name))


def launch_crew(rel_path: str) -> tuple[int | None, str]:
    """Launch the crew under the watchdog as a detached background process.

    Returns (pid, log_path). The process outlives this crew's task and keeps the new
    crew alive across restarts.
    """
    root = _project_root()
    logs = root / "logs"
    logs.mkdir(exist_ok=True)
    log_path = logs / (Path(rel_path).stem + ".watchdog.log")
    logf = open(log_path, "ab")
    # Put the venv's Scripts/bin dir (where uv.exe lives next to this python.exe) first on
    # PATH so the watchdog's `uv run` resolves even if the parent's PATH lacks it.
    env = os.environ.copy()
    env["PATH"] = str(Path(sys.executable).parent) + os.pathsep + env.get("PATH", "")
    try:
        if os.name == "nt":
            script = root / "scripts" / "watchdog.ps1"
            cmd = [
                "powershell", "-NoProfile", "-ExecutionPolicy", "Bypass",
                "-File", str(script), rel_path,
            ]
            # CREATE_NO_WINDOW | CREATE_NEW_PROCESS_GROUP: runs hidden and outlives the parent.
            # NOT DETACHED_PROCESS — with that flag PowerShell never executes the script and the
            # log stays empty (verified); CREATE_NO_WINDOW runs it and captures its output.
            flags = 0x08000000 | 0x00000200
            proc = subprocess.Popen(
                cmd, cwd=str(root), env=env, stdout=logf, stderr=logf,
                stdin=subprocess.DEVNULL, creationflags=flags, close_fds=True,
            )
        else:
            script = root / "scripts" / "watchdog.sh"
            proc = subprocess.Popen(
                ["bash", str(script), rel_path], cwd=str(root), env=env, stdout=logf,
                stderr=logf, stdin=subprocess.DEVNULL, start_new_session=True, close_fds=True,
            )
        return proc.pid, _rel(log_path)
    except Exception as exc:  # noqa: BLE001
        logf.close()
        return None, f"launch failed: {exc}"


def _agent_name_of(path: Path) -> str | None:
    """Read AGENT_NAME from a crew file (without importing it)."""
    try:
        m = _AGENT_NAME_RE.search(path.read_text(encoding="utf-8"))
        return m.group(1) if m else None
    except OSError:
        return None


def _crew_files() -> list[Path]:
    """All crew files in crews/ (skipping helpers/probes prefixed with '_')."""
    crews = _project_root() / "crews"
    if not crews.is_dir():
        return []
    return [p for p in sorted(crews.glob("*_crew.py")) if not p.name.startswith("_")]


def reconcile_fleet() -> str:
    """Ensure every approved crew in crews/ is running: launch the stopped ones, skip the
    running ones. Idempotent and reboot-safe — liveness is a live process scan (not stored
    PIDs), so after a restart every crew reads as down and is relaunched exactly once. Only
    crews that are registered AND approved (have a token) are auto-started; others are reported.
    """
    from crewaimeat.aimeat_crew import _token_exists  # local import avoids any import cycle

    root = _project_root()
    owner = os.getenv("AIMEAT_OWNER", "").strip() or None
    files = _crew_files()
    if not files:
        return "No crews in crews/ to reconcile."

    # Crude lock so two overlapping reconciles can't double-launch the same crew.
    logs = root / "logs"
    logs.mkdir(exist_ok=True)
    lock = logs / ".fleet.lock"
    try:
        if lock.is_file() and (time.time() - lock.stat().st_mtime) < 90:
            return "A fleet reconcile is already in progress; try again shortly."
        lock.write_text(str(time.time()), encoding="utf-8")
    except OSError:
        pass

    launched, already, needs_approval = [], [], []
    try:
        for path in files:
            name = path.name
            if _is_running_file(name):
                already.append(name)
                continue
            agent = _agent_name_of(path)
            if agent and not _token_exists(agent, owner):
                needs_approval.append(agent)
                continue
            pid, log = launch_crew(f"crews/{name}")
            launched.append(f"{agent or name} (pid {pid})" if pid else f"{name} (FAILED: {log})")
    finally:
        try:
            lock.unlink()
        except OSError:
            pass

    out = [
        f"Fleet reconcile: {len(launched)} launched, {len(already)} already running, "
        f"{len(needs_approval)} need approval."
    ]
    if launched:
        out.append("Launched: " + ", ".join(launched))
    if already:
        out.append("Already running: " + ", ".join(already))
    if needs_approval:
        out.append("Need registration/approval (not started): " + ", ".join(needs_approval))
    return "\n".join(out)


# --------------------------------------------------------------------------- #
# CrewAI tools handed to the builder agent
# --------------------------------------------------------------------------- #
@tool("write_and_validate_crew")
def write_and_validate_crew(
    agent_name: str, build_domain_code: str, extra_imports: str = "", readme_md: str = ""
) -> str:
    """Write crews/<agent_name>_crew.py on the locked AIMEAT scaffold and validate it.

    Pass ONLY the build_domain function in build_domain_code:
        def build_domain(ctx): ...; return (agents, tasks)
    (plus any helper defs it needs). The scaffold imports, AGENT_NAME, run() and the
    __main__ guard are added for you; Agent, Task, BuildContext and _web_tools are
    already imported in the file. Put any additional import lines in extra_imports.

    Pass `readme_md` with the crew's README tab markdown (start it with a FIGLET logo, e.g.
    [[FIGLET:slant]["New Crew"]], then a short description and a "How to task me" line). It is
    embedded and published to the agent's README tab. If you omit it, the scaffold publishes a
    generated default README, so the tab is never blank.

    Returns 'VALID: ...' when it compiles and build_domain returns a non-empty
    (agents, tasks). Otherwise returns 'INVALID: <error>' — fix the build_domain code
    and call this tool again until it is VALID. Overwrites the file each call.
    """
    path = write_crew_file(agent_name, build_domain_code, extra_imports, readme_md)
    ok, detail = validate_crew_file(path)
    rel = _rel(path)
    if ok:
        return f"VALID: wrote {rel}. {detail}"
    return (
        f"INVALID ({rel}): {detail}\n"
        "Fix the build_domain code and call write_and_validate_crew again."
    )


@tool("register_and_launch_crew")
def register_and_launch_crew(agent_name: str) -> str:
    """Register the new agent on AIMEAT and launch its crew under the watchdog.

    Call this ONCE, only after write_and_validate_crew returned VALID. Runs
    `aimeat connect add` (owner from the AIMEAT_OWNER env var) and then starts the crew
    as a detached background process. Returns a report including the approve step the
    human must complete on the AIMEAT dashboard and the watchdog log path.
    """
    rel = f"crews/{_fname(agent_name)}"
    if not (_project_root() / rel).exists():
        return f"ERROR: {rel} does not exist. Call write_and_validate_crew first."

    owner = os.getenv("AIMEAT_OWNER", "").strip()
    if owner:
        _ok, reg_line = register_agent(agent_name, owner)
    else:
        reg_line = (
            "AIMEAT_OWNER is not set — register manually: npx aimeat@latest connect add --agent "
            f"{agent_name} --mode task-runner --url https://aimeat.io --owner <your-aimeat-account>"
        )

    if is_crew_running(agent_name):
        launch_line = f"'{agent_name}' is already running; did not launch a duplicate."
    else:
        pid, log = launch_crew(rel)
        launch_line = (
            f"Launched under the watchdog (pid {pid}); it comes online the moment you approve. Log: {log}"
            if pid is not None
            else f"Launch problem: {log}"
        )
    return (
        f"NEW AGENT: {agent_name}  (file: {rel})\n"
        f"ACTION REQUIRED -> {reg_line}\n"
        f"{launch_line}\n"
        f"Once approved, queue a task for '{agent_name}' from its Tasks tab."
    )


@tool("restart_crew")
def restart_crew(agent_name: str) -> str:
    """Bring an already-built crew back online: if its process is down, launch it under
    the watchdog; if it is already running, leave it. Use this for 'restart' / 'relaunch'
    / 'bring back' requests. The crew file crews/<agent_name>_crew.py must already exist
    (build it first with the forge tools if it does not).
    """
    rel = f"crews/{_fname(agent_name)}"
    if not (_project_root() / rel).exists():
        return f"ERROR: {rel} does not exist. Build the crew first, then restart it."
    if is_crew_running(agent_name):
        return f"'{agent_name}' is already running ({rel}); left it as is."
    pid, log = launch_crew(rel)
    if pid is None:
        return f"Tried to start '{agent_name}' but the launch failed: {log}"
    return (
        f"Started '{agent_name}' under the watchdog (pid {pid}). Log: {log}. "
        "If its token still needs approval it will wait until you approve it on AIMEAT, "
        "then come online by itself."
    )


@tool("list_crews")
def list_crews() -> str:
    """List the crews in crews/ and whether each one appears to be running. Use this for
    'list my agents' / 'what's running' / status requests.
    """
    crews_dir = _project_root() / "crews"
    files = sorted(crews_dir.glob("*_crew.py")) if crews_dir.exists() else []
    if not files:
        return "No crews found in crews/."
    lines = [f"  - {f.name}: {'running' if _is_running_file(f.name) else 'stopped'}" for f in files]
    return "Crews in crews/:\n" + "\n".join(lines)


@tool("reauth_crew")
def reauth_crew(agent_name: str) -> str:
    """Re-run AIMEAT authorization for an existing agent so the owner can approve it again.
    Use after an accidental deny, or when a token expired/was revoked. Re-registers via
    `npx aimeat@latest connect add`; the owner then re-approves it in the dashboard.
    Owner is read from the AIMEAT_OWNER environment variable.
    """
    owner = os.getenv("AIMEAT_OWNER", "").strip()
    if not owner:
        return (
            "AIMEAT_OWNER is not set, so I cannot re-auth. Set it in .env, then run:\n"
            f"  npx aimeat@latest connect add --agent {agent_name} --mode task-runner "
            "--url https://aimeat.io --owner <your-aimeat-account>"
        )
    ok, out = register_agent(agent_name, owner)
    return (
        f"Re-auth started for '{agent_name}'. Approve it on AIMEAT (Profile -> Agents) and it "
        f"comes back online by itself. Connector output:\n{out or '(none)'}"
    )


@tool("start_all_crews")
def start_all_crews() -> str:
    """Ensure every approved crew in crews/ is running: launch the stopped ones and skip the
    ones already running. Idempotent and safe to call any time (never double-launches), including
    right after a machine restart to bring the whole fleet back online. Use for /startall, /up.
    """
    return reconcile_fleet()


def make_forge_tools() -> list:
    """The tools the crew-forge builder agent uses to materialize a new crew."""
    return [write_and_validate_crew, register_and_launch_crew]


def make_manage_tools() -> list:
    """The tools crew-forge uses to operate the fleet: restart, re-auth, list, and start-all."""
    return [restart_crew, list_crews, reauth_crew, start_all_crews]
