"""image-maker's workspace-contract: turn `image-request` records into generated images.

The SECOND surface of image-maker (the first is the task-runner Image Director crew). Any workspace
can adopt this contract and just write a record:
  inputs : `image-request` (records) — trigger: status == 'requested'
             { id, prompt(required), size?(0.5K|1K|2K|4K), aspect_ratio?(e.g. 1:1, 16:9), status,
               requested_by?, result_ref?, error? }
  outputs: `image-gallery` (DOCUMENT, id = img-<request id>) — a page with the generated image
             embedded (public URL) + the prompt + metadata.
  lifecycle: requested -> in-progress (claim) -> done (+result_ref) | failed (+error)

The loop is plain code (crewaimeat.seedream_gen.generate_image does the OpenRouter Seedream 4.5 call +
the presigned public upload). Reliable-processing per the canon: output-existence dedup is the primary
restart-surviving guard, backed by a per-run processed-set, a bounded batch per pass, one calm cadence.
"""

from __future__ import annotations

import datetime

from crewaimeat.aimeat_crew import _aimeat_call, member_workspaces
from crewaimeat.seedream_gen import generate_image

AGENT = "image-maker"
IN_SPACE, IN_NS = "image-request", "shared.image_requests"
OUT_SPACE, OUT_NS = "image-gallery", "shared.image_gallery"  # a DOCUMENT space

# Machine-readable contract declaration — what adopt-contract provisions into a workspace.
CONTRACT = {
    "id": "image-request",
    "spaces": [
        {
            "space": IN_SPACE,
            "namespace": IN_NS,
            "mode": "records",
            "schema": {
                "type": "object",
                "required": ["id", "prompt", "status"],
                "properties": {
                    "id": {"type": "string"},
                    "prompt": {"type": "string"},
                    "size": {"type": "string"},
                    "aspect_ratio": {"type": "string"},
                    "requested_by": {"type": "string"},
                    "result_ref": {"type": "string"},
                    "error": {"type": "string"},
                    "status": {"type": "string", "enum": ["requested", "in-progress", "done", "failed"]},
                },
            },
        },
        {"space": OUT_SPACE, "namespace": OUT_NS, "mode": "document"},
    ],
}

# Runaway guard (canon): ids handled THIS run; the OUTPUT-dedup below is the primary, restart-surviving guard.
_PROCESSED: set[str] = set()


def _call(tool_name: str, payload: dict):
    return _aimeat_call(AGENT, tool_name, payload)


def _advance(oid: str, wid: str, req: dict, **changes) -> None:
    rec = {k: v for k, v in {**req, **changes}.items() if not k.startswith("_")}
    if _call(
        "aimeat_workspace_write", {"organism_id": oid, "ws": wid, "space": IN_SPACE, "id": rec["id"], "value": rec}
    ):
        _call("aimeat_workspace_publish", {"organism_id": oid, "ws": wid, "namespace": IN_NS, "id": rec["id"]})


def _gallery_markdown(prompt: str, res: dict, today: str) -> str:
    return (
        f"*Generated by image-maker (ByteDance Seedream 4.5) · {today}*\n\n"
        f"![{prompt[:80]}]({res['url']})\n\n"
        f"**Prompt:** {prompt}\n\n"
        f"{res.get('mime', 'image')} · {res.get('bytes', 0)} bytes · [open]({res['url']})\n"
    )


def process_image_requests(max_items: int = 3, targets: list[tuple[str, str]] | None = None) -> dict:
    """Fulfil pending `image-request` records across the agent's member workspaces.

    Deterministic: discover -> claim -> generate_image (Seedream 4.5, public upload) -> write the
    image-gallery document -> advance. Bounded (max_items per pass — each image costs ~$0.04);
    output-dedup settles a request whose gallery doc already exists. Returns counts."""
    pairs = targets if targets is not None else member_workspaces(AGENT)
    if targets is None:  # gate the discovery path on engagements (0.14.0 gates only the push path)
        from crewaimeat.engagements import engaged_pairs

        pairs = engaged_pairs(AGENT, pairs, contract=CONTRACT["id"])
    today = datetime.date.today().isoformat()
    processed = failed = 0
    for oid, wid in pairs:
        if processed + failed >= max_items:
            break
        data = _call("aimeat_workspace_read", {"organism_id": oid, "ws": wid})
        if not data or data.get("manifest") is None:
            continue
        reqs = (data.get("objects", {}) or {}).get(IN_SPACE) or []
        existing = {r.get("id") for r in ((data.get("objects", {}) or {}).get(OUT_SPACE) or [])}
        for req in reqs:
            rid = req.get("id")
            if req.get("status") != "requested" or not rid:
                continue
            if rid in _PROCESSED:  # per-run guard against a stale 'requested' read
                continue
            if f"img-{rid}" in existing:  # output-dedup: already fulfilled -> settle
                _PROCESSED.add(rid)
                _advance(oid, wid, req, status="done", result_ref=f"img-{rid}")
                continue
            if processed + failed >= max_items:
                break
            prompt = (req.get("prompt") or "").strip()
            if not prompt:
                _PROCESSED.add(rid)
                _advance(oid, wid, req, status="failed", error="empty prompt")
                failed += 1
                continue
            _PROCESSED.add(rid)
            _advance(oid, wid, req, status="in-progress")  # CLAIM
            res = generate_image(
                AGENT, prompt, size=(req.get("size") or "2K"), aspect_ratio=(req.get("aspect_ratio") or None)
            )
            if not res.get("ok"):
                _advance(oid, wid, req, status="failed", error=str(res.get("error"))[:300])
                failed += 1
                continue
            out_id = f"img-{rid}"
            title = f"Image · {prompt[:70]}"
            wrote = _call(
                "aimeat_workspace_write",
                {
                    "organism_id": oid,
                    "ws": wid,
                    "space": OUT_SPACE,
                    "id": out_id,
                    "value": {"title": title, "markdown": _gallery_markdown(prompt, res, today)},
                },
            )
            pub = (
                _call("aimeat_workspace_publish", {"organism_id": oid, "ws": wid, "namespace": OUT_NS, "id": out_id})
                if wrote
                else None
            )
            if wrote and pub:
                _advance(oid, wid, req, status="done", result_ref=out_id)
                processed += 1
            else:
                _advance(oid, wid, req, status="failed", error="gallery write failed")
                failed += 1
    return {"processed": processed, "failed": failed}
