"""`crewaimeat quality` — did the output get better when the model changed?

That question had no answer. The paper's prose was routed to DeepSeek V4 Pro on 2026-08-12 because the
previous chain's Finnish was judged unusable, and the evidence for the switch working was an
impression. An impression is not a bad reason to act, but it is a bad thing to keep acting on.

WHAT THIS MEASURES, AND WHAT IT DOES NOT. It does not judge prose. Style is exactly what a deterministic
check cannot see, and an LLM judge scoring an LLM's writing is expensive, noisy, and agrees with itself
for reasons nobody can audit. What it measures instead are the properties that a bad run actually
degrades, all of them already recorded beside every published article:

  · GROUNDING     how many sources the piece cites — and how often a piece that is NORMALLY sourced
                  cites none, which is indistinguishable from invention

                  "Normally sourced" is doing real work there. The first version compared a raw
                  ungrounded share per model and reported DeepSeek as 5x worse than the free router.
                  It was an artifact: `koodaus`, `matikka` and `prompt-niksi` are generated feature
                  sections with no news sources BY DESIGN, they are 100% ungrounded on every model,
                  and they are ~3 of the ~23 articles in every edition. Every actual news category is
                  0% ungrounded, before and after the switch. So a category that has never carried a
                  source in the window is classified as GENERATED and excluded from the headline —
                  self-calibrating, with no hardcoded list to go stale.
  · COMPLETENESS  how many articles an edition actually produced (a weak model silently skips)
  · LENGTH        the median, because collapse to a stub is the other way a run fails quietly

Each is read per ARTICLE and attributed to the MODEL that wrote it, from the node's provenance record
(`generator.model`). So the comparison is not "before and after a date" — it is "these N articles were
written by model X and these M by model Y", which survives a routing change mid-week and a fallback
that quietly served a different model than the one configured.

Deterministic, read-only, no LLM. Works off-fleet through the direct authed REST path.
"""

from __future__ import annotations

import argparse
import datetime
import json
import statistics
import sys
from dataclasses import dataclass, field
from pathlib import Path

DEFAULT_DAYS = 21
DEFAULT_EDITION = "evening"

# The node allows 120 reads per 60s. This report makes two reads per article (the record, then its
# provenance), so an unpaced 21-day run trips the limit within seconds — and a rate-limited read is
# indistinguishable from a missing one unless you are careful, which is exactly the trap the first
# version fell into. Pace under the limit instead of retrying into it.
_MAX_READS_PER_MIN = 100
_MIN_INTERVAL = 60.0 / _MAX_READS_PER_MIN


@dataclass
class Article:
    date: str
    category: str
    model: str
    provider: str
    chars: int
    sources: int | None  # None = we could not read the provenance, NOT "cited nothing"


MIN_TO_CALL_GENERATED = 3


def generated_categories(articles: list[Article]) -> set[str]:
    """Categories that have NEVER carried a source across ENOUGH articles — generated by design.

    Derived from the data, not listed in code: a hardcoded set goes stale the first time a section
    changes and then quietly hides a real regression.

    The `MIN_TO_CALL_GENERATED` floor exists because the two mistakes are not symmetric. Wrongly
    calling a category "generated" HIDES an ungrounded failure and says nothing; wrongly calling it
    "sourced" produces a visible finding someone can check in a minute. So when there is not enough
    evidence, the category is treated as sourced and judged — the error that speaks up.
    """
    seen: dict[str, list[int]] = {}
    for a in articles:
        if a.sources is None:
            continue
        row = seen.setdefault(a.category, [0, 0])  # [observed, with sources]
        row[0] += 1
        row[1] += 1 if a.sources > 0 else 0
    return {cat for cat, (n, sourced) in seen.items() if sourced == 0 and n >= MIN_TO_CALL_GENERATED}


@dataclass
class ModelStats:
    model: str
    articles: list[Article] = field(default_factory=list)
    generated: set = field(default_factory=set)

    @property
    def editions(self) -> int:
        return len({a.date for a in self.articles})

    @property
    def per_edition(self) -> float:
        return len(self.articles) / self.editions if self.editions else 0.0

    @property
    def median_chars(self) -> int:
        return int(statistics.median([a.chars for a in self.articles])) if self.articles else 0

    @property
    def known(self) -> list[Article]:
        """Articles whose provenance we actually READ. Grounding is only meaningful over these."""
        return [a for a in self.articles if a.sources is not None]

    @property
    def sourced_kind(self) -> list[Article]:
        """Articles from a category that IS normally sourced — the only ones grounding can judge."""
        return [a for a in self.known if a.category not in self.generated]

    @property
    def unknown(self) -> int:
        return len(self.articles) - len(self.known)

    @property
    def median_sources(self) -> float:
        rows = self.sourced_kind
        return statistics.median([a.sources for a in rows]) if rows else 0.0

    @property
    def ungrounded(self) -> int:
        """Articles that cite NO source — the one number here that is unambiguously bad.

        Counted ONLY over articles whose provenance was read. The first version counted a
        RATE-LIMITED read as zero sources, which reported 40 well-sourced articles as 100%
        ungrounded. A measurement that invents bad news is worse than no measurement.
        """
        return sum(1 for a in self.sourced_kind if a.sources == 0)

    @property
    def ungrounded_share(self) -> float:
        rows = self.sourced_kind
        return self.ungrounded / len(rows) if rows else 0.0


def _dates(days: int) -> list[str]:
    """The window, in the timezone the editions are KEYED in — not UTC.

    This read UTC until 2026-08-24, when it could not see the edition that had just been written.
    An evening edition dated D is written the night before D (~22:00 UTC), so between midnight
    Helsinki and midnight UTC the newest paper is dated "tomorrow" by a UTC clock and falls outside
    every window. Those three hours are exactly when someone checks what last night's run produced,
    so the measurement was blind at the one moment it was wanted.

    `today_local` is the repo's answer to this, and its docstring already said so: any calendar day
    that becomes a KEY is local; only instants stay UTC.
    """
    from crewaimeat.aimeat_crew import today_local

    today = datetime.date.fromisoformat(today_local())
    return [str(today - datetime.timedelta(days=n)) for n in range(days)]


def collect(agent: str, days: int = DEFAULT_DAYS, edition: str = DEFAULT_EDITION) -> tuple[list[Article], list[str]]:
    """(articles, problems). `problems` names every read that failed, so a thin result is never
    mistaken for a thin newspaper."""
    import time

    from crewaimeat.aimeat_crew import _aimeat_rest

    last = [0.0]

    def paced(method: str, path: str):
        wait = _MIN_INTERVAL - (time.monotonic() - last[0])
        if wait > 0:
            time.sleep(wait)
        last[0] = time.monotonic()
        return _aimeat_rest(agent, method, path)

    articles: list[Article] = []
    problems: list[str] = []
    for date in _dates(days):
        listing = paced("GET", f"/v1/memory?prefix=news.{date}.{edition}.article.&owner_scope=true&limit=60")
        if listing is None:
            problems.append(f"{date}: could not list keys")
            continue
        items = listing.get("items") or listing.get("entries") or []
        for it in items:
            key = it.get("key") or ""
            if ".article." not in key:
                continue
            rec = paced("GET", f"/v1/memory/{key}?owner_scope=true")
            if not isinstance(rec, dict):
                problems.append(f"{key}: could not read")
                continue
            value = rec.get("value")
            text = value if isinstance(value, str) else json.dumps(value, ensure_ascii=False)
            model, provider, sources, problem = _provenance(paced, rec.get("ai_provenance_id"))
            if problem:
                problems.append(f"{key}: {problem}")
            articles.append(
                Article(
                    date=date,
                    category=key.rsplit(".", 1)[-1],
                    model=model,
                    provider=provider,
                    chars=len(text or ""),
                    sources=sources,
                )
            )
    return articles, problems


def _provenance(read, pid: str | None) -> tuple[str, str, int | None, str | None]:
    """(model, provider, source_count, problem) for one published record.

    THREE outcomes, kept apart on purpose:
      · no `ai_provenance_id`  -> the record really declares nothing. That IS a finding.
      · the read failed        -> we do not know. `sources` is None and the caller records a problem;
                                  counting it as zero manufactures a quality failure that never happened.
      · read ok                -> the real model, provider and source count.
    """
    if not pid:
        return "(no provenance record)", "-", None, None
    rec = read("GET", f"/v1/provenance/{pid}")
    if not isinstance(rec, dict):
        return "(unread)", "-", None, f"provenance {pid[:8]}: read failed"
    prov = rec.get("provenance") or {}
    gen = prov.get("generator") or {}
    return (
        str(gen.get("model") or "(model undeclared)"),
        str(gen.get("provider") or "-"),
        len(prov.get("sources") or []),
        None,
    )


def group(articles: list[Article]) -> list[ModelStats]:
    gen = generated_categories(articles)
    by: dict[str, ModelStats] = {}
    for a in articles:
        st = by.setdefault(a.model, ModelStats(model=a.model, generated=gen))
        st.articles.append(a)
    return sorted(by.values(), key=lambda s: len(s.articles), reverse=True)


def render(stats: list[ModelStats], articles: list[Article], days: int, problems: list[str]) -> str:
    if not articles:
        return "no published articles in the window."
    out = [f"published-article quality by MODEL — last {days} days", ""]
    width = max(len(s.model) for s in stats)
    out.append(
        f"  {'model':<{width}}  {'articles':>8} {'eds':>4} {'per ed.':>7} {'med.len':>8} "
        f"{'med.src':>8} {'no source':>12} {'unknown':>8}"
    )
    out.append(f"  {'-' * width}  {'-' * 8} {'-' * 4} {'-' * 7} {'-' * 8} {'-' * 8} {'-' * 12} {'-' * 8}")
    for s in stats:
        flag = "  <-- ungrounded" if s.known and s.ungrounded_share > 0.10 else ""
        src = f"{s.median_sources:>8.1f}" if s.known else f"{'?':>8}"
        bad = f"{s.ungrounded:>4} ({s.ungrounded_share:>3.0%})" if s.known else f"{'unknown':>12}"
        out.append(
            f"  {s.model:<{width}}  {len(s.articles):>8} {s.editions:>4} {s.per_edition:>7.1f} "
            f"{s.median_chars:>8,} {src} {bad:>12} {s.unknown:>8}{flag}"
        )
    gen = sorted(generated_categories(articles))
    if gen:
        out.append("")
        out.append(f"  excluded from grounding: {', '.join(gen)} — never sourced in this window, so")
        out.append("  they are generated sections, not failures. Every other category IS judged.")
    span = sorted({a.date for a in articles})
    out.append("")
    out.append(f"  {len(articles)} articles across {len(span)} editions, {span[0]} … {span[-1]}")
    out.append("")
    out.append("  Grounding, completeness and length only — this does not judge prose, and does not")
    out.append("  pretend to. 'no source' counts only categories that ARE normally sourced; 'unknown'")
    out.append("  is where the provenance could not be read, and is never counted as ungrounded.")
    if problems:
        out.append("")
        out.append(f"  {len(problems)} read(s) FAILED — the numbers above are incomplete by that much:")
        for p in problems[:5]:
            out.append(f"    · {p}")
    return "\n".join(out)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="crewaimeat quality", description=__doc__.splitlines()[0])
    ap.add_argument("--days", type=int, default=DEFAULT_DAYS, help=f"window in days (default {DEFAULT_DAYS})")
    ap.add_argument("--edition", default=DEFAULT_EDITION)
    ap.add_argument("--json", action="store_true", help="machine-readable output")
    ap.add_argument("--root", default=".", help="repo root (default: cwd)")
    args = ap.parse_args(argv)

    from crewaimeat.doctor.inventory import gather

    inv = gather(Path(args.root).resolve())
    agent = next(iter(sorted(inv.served)), None)
    if not agent:
        print("quality: nothing registered in serve.json — no identity to read the node with", file=sys.stderr)
        return 2

    articles, problems = collect(agent, days=args.days, edition=args.edition)
    stats = group(articles)
    if args.json:
        print(
            json.dumps(
                {
                    "days": args.days,
                    "edition": args.edition,
                    "problems": problems,
                    "models": [
                        {
                            "model": s.model,
                            "articles": len(s.articles),
                            "editions": s.editions,
                            "per_edition": round(s.per_edition, 2),
                            "median_chars": s.median_chars,
                            "median_sources": s.median_sources,
                            "ungrounded": s.ungrounded,
                            "ungrounded_share": round(s.ungrounded_share, 3),
                            "unknown_provenance": s.unknown,
                        }
                        for s in stats
                    ],
                },
                indent=2,
            )
        )
    else:
        print(render(stats, articles, args.days, problems))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
