"""What one subscriber ordered: their own interests, editable by them.

Aamukatsaus is the morning SITUATIONAL BRIEFING — what got done, what it cost, SOME-radar,
competitor watch, what is worth doing today, and the Grok run. A subscriber orders the same thing
for THEMSELVES, which means three fields and no more:

    competitors  -> the Kilpailijakatsaus sweep runs these queries instead of ours
    radar        -> the SOME-radar looks for these words instead of ours
    topic        -> the Grok run is written about this

The two fleet sections (`Mitä saatiin aikaan`, `Mihin tehot menivät`) measure an agent fleet, so
they appear only for a subscriber who runs one. Nothing here invents a fourth field: every extra
knob is a thing the subscriber has to understand before their first briefing arrives.

WHERE IT LIVES, and why in OUR memory rather than theirs. The briefing itself is generated by us
into `aamukatsaus.<sub>.<date>` and read through one standing share — the design the owner settled
on, where a copy the subscriber takes is theirs to keep. The order belongs in the same subtree:
`aamukatsaus.<sub>.prefs` is covered by the SAME share, so the subscriber can always read back
exactly what we hold about them. A subscription you cannot inspect is not one you can trust.

They EDIT it by sending it — the app DMs postman (`messages:send` is app-grantable), and the DM
handler calls `set_prefs`. That keeps the write on our side, where the validation is, and needs no
group, no scope and no owner action. See `subscriber_intake.py` for the parsing.
"""

from __future__ import annotations

import datetime
import sys

from crewaimeat.aimeat_crew import _aimeat_call
from crewaimeat.subscriber_space import AGENT, space_of

MAX_QUERIES = 5  # per field — each one is a live search every morning, so the cost is visible here
MAX_LEN = 120

FIELDS = ("competitors", "radar", "topic")


class InvalidOrder(ValueError):
    """The order cannot be run as written. Raised at the boundary, never repaired silently."""


def prefs_key(subscriber: str) -> str:
    return f"{space_of(subscriber)}.prefs"


def _clean_list(raw, field: str) -> list[str]:
    if raw is None:
        return []
    if isinstance(raw, str):
        raw = [p for p in (x.strip() for x in raw.split(",")) if p]
    if not isinstance(raw, list):
        raise InvalidOrder(f"{field} must be a list of phrases (or a comma-separated string), got {type(raw).__name__}")
    out: list[str] = []
    for item in raw:
        s = str(item).strip()
        if not s:
            continue
        if len(s) > MAX_LEN:
            raise InvalidOrder(f"{field}: '{s[:40]}…' is {len(s)} chars, max {MAX_LEN}")
        if s not in out:
            out.append(s)
    if len(out) > MAX_QUERIES:
        raise InvalidOrder(
            f"{field}: {len(out)} phrases, max {MAX_QUERIES}. Each one is a live search every "
            "morning — the limit is what keeps a subscription's cost predictable."
        )
    return out


def normalise(order: dict) -> dict:
    """Validate an order into the exact shape the briefing builder reads. Raises InvalidOrder.

    An order with nothing in any of the three fields is refused rather than accepted-and-empty: it
    would produce a briefing every morning with no content in it, and the subscriber would be left
    guessing whether we lost their order or their interests genuinely returned nothing."""
    if not isinstance(order, dict):
        raise InvalidOrder(f"an order is an object with {', '.join(FIELDS)} — got {type(order).__name__}")
    competitors = _clean_list(order.get("competitors"), "competitors")
    radar = _clean_list(order.get("radar"), "radar")
    topic = str(order.get("topic") or "").strip()
    if len(topic) > MAX_LEN * 3:
        raise InvalidOrder(f"topic is {len(topic)} chars, max {MAX_LEN * 3}")
    if not (competitors or radar or topic):
        raise InvalidOrder(
            "the order is empty — name at least one of: competitors to watch, radar phrases, "
            "or a topic for the Grok run. An empty order produces an empty briefing every morning."
        )
    return {"competitors": competitors, "radar": radar, "topic": topic}


def set_prefs(subscriber: str, order: dict, *, by: str = "app", agent: str = AGENT) -> dict:
    """Write (or replace) a subscriber's order. Validates first — a rejected order changes nothing.

    Keeps `created_at` from any existing record so "subscriber since" survives every edit."""
    clean = normalise(order)
    existing = get_prefs(subscriber, agent=agent) or {}
    now = datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds")
    value = {
        **clean,
        "subscriber": subscriber,
        # The DM thread the order arrived in — the route the briefing goes back out through. Kept
        # from the existing record when an edit does not carry one, so re-ordering from a different
        # surface never silently cuts off delivery.
        "conversation_id": order.get("conversation_id") or existing.get("conversation_id"),
        "ghii": order.get("ghii") or existing.get("ghii"),
        "active": bool(order.get("active", existing.get("active", True))),
        "created_at": existing.get("created_at") or now,
        "updated_at": now,
        "updated_by": by,
    }
    key = prefs_key(subscriber)
    if _aimeat_call(agent, "aimeat_memory_write", {"key": key, "value": value, "visibility": "private"}) is None:
        raise RuntimeError(f"could not write {key} — the order was NOT saved")
    print(
        f"[{agent}] order saved for {subscriber}: {len(clean['competitors'])} competitors, "
        f"{len(clean['radar'])} radar, topic={'yes' if clean['topic'] else 'no'}",
        file=sys.stderr,
    )
    return value


def get_prefs(subscriber: str, *, agent: str = AGENT) -> dict | None:
    r = _aimeat_call(agent, "aimeat_memory_read", {"key": prefs_key(subscriber)})
    if not isinstance(r, dict):
        return None
    val = r.get("value", r)
    return val if isinstance(val, dict) and val.get("subscriber") else None


def list_subscribers(*, active_only: bool = True, agent: str = AGENT) -> list[dict]:
    """Every order we hold. This is the loop the morning run walks."""
    r = _aimeat_call(agent, "aimeat_memory_list", {"owner_scope": True, "prefix": "aamukatsaus.", "limit": 500})
    items = (r.get("items") or []) if isinstance(r, dict) else []
    out = []
    for it in items:
        if not (it.get("key") or "").endswith(".prefs"):
            continue
        val = it.get("value")
        if isinstance(val, dict) and val.get("subscriber") and (val.get("active", True) or not active_only):
            out.append(val)
    return sorted(out, key=lambda v: v.get("subscriber", ""))


def deactivate(subscriber: str, *, agent: str = AGENT) -> bool:
    """Stop producing briefings without destroying the order — the subscriber can resume as they were.

    Deliberately NOT a delete: someone who pauses in July and returns in September should not have
    to reconstruct what they were watching."""
    cur = get_prefs(subscriber, agent=agent)
    if not cur:
        print(f"[{agent}] no order for {subscriber}", file=sys.stderr)
        return False
    set_prefs(subscriber, {**cur, "active": False}, by="owner", agent=agent)
    return True
