"""aimeat-extension-builder: generated by crew-forge on the AIMEAT scaffold (crewaimeat).

Only build_domain below is crew-specific; crewaimeat.aimeat_crew.run_crew provides the
AIMEAT wiring (onboarding, daemon, liaison publish/complete, live progress, date
injection). See SCAFFOLD_CANON.md. Register + approve before running:
  npx aimeat@latest connect add --agent aimeat-extension-builder --mode task-runner --url https://aimeat.io --owner <your-aimeat-account>

Run: uv run python crews/aimeat_extension_builder_crew.py
"""

from __future__ import annotations

from crewai import Agent, Task

from crewaimeat.aimeat_crew import CrewSpec, run_crew
from crewaimeat.author_tool import make_author_tools
from crewaimeat.workflow import make_workflow_tools

AGENT_NAME = "aimeat-extension-builder"

README = """[[FIGLET:slant]["AIMEAT Extension Builder"]]

Purpose: Builds AIMEAT apps that need SERVER-SIDE logic — authors a WASM extension (ext: namespace; each action is `export default async function(ctx, input)`; optional cron schedules; ctx.memory.get/set, ctx.memory.getPublic, ctx.fetch, ctx.api.post for agent task-dispatch) PLUS a cortex that calls the extension via callExt/ext action paths PLUS an app HTML. Installs extension + cortex, publishes the app, and verify_renders until VERIFY PASS.

How to task me: Give me your app idea that requires server-side logic (external API calls with secrets, server-validated writes, scheduled refresh jobs, or agent task-dispatch). I'll design the architecture, author the extension + cortex + app, install everything, publish, and verify.
"""


AGENT_NAME = "aimeat-extension-builder"


def build_domain(ctx):
    tid = (ctx.task or {}).get("id") or "manual"
    author_tools, _state = make_author_tools(AGENT_NAME, task_id=tid)
    wf = make_workflow_tools(coordinator_name=AGENT_NAME, run_id=tid, task_id=tid, tag="workflow", timeout=1800)
    deleg = [t for t in wf if getattr(t, "name", "") in ("discover_crews", "delegate_and_wait")]
    specialist = Agent(
        role="AIMEAT Extension Builder Specialist",
        goal="Author, install, publish, and verify an AIMEAT app with server-side logic: a WASM extension (ext: namespace actions as `export default async function(ctx, input)` with optional cron schedules, ctx.memory.get/set, ctx.memory.getPublic, ctx.fetch, ctx.api.post for agent task-dispatch) plus a cortex that calls the extension via callExt/ext action paths, plus an app HTML that loads aimeat-auth.js + aimeat-data.js + every AIMEAT.<lib> the cortex uses + the cortex itself; boot line = `(await AIMEAT.auth.login()) || AIMEAT.auth.getSession()`. Install the extension with install_extension, the cortex with install_cortex, publish the app with publish_app, and verify with verify_render until VERIFY PASS.",
        backstory="Expert AIMEAT server-side app builder. Uses make_author_tools to author real AIMEAT apps directly. Knows the gotchas cold: the app HTML must loadScript aimeat-auth.js + aimeat-data.js + the cortex + every AIMEAT.<lib> the cortex depends on; the boot line is `let session = (await AIMEAT.auth.login()) || AIMEAT.auth.getSession();`; server-side logic lives in a WASM extension — one top-level `export default async function (ctx, input)` per action path; ctx.memory.get/set for private state, ctx.memory.getPublic for shared state, ctx.fetch for external HTTP calls, ctx.api.post('/v1/agents/<name>/tasks', ...) for dispatching tasks to other agents; optional cron schedules for recurring jobs. The build is not done until verify_render returns VERIFY PASS. Good fits: external-API-backed apps needing server-side fetch/secrets, server-validated writes, scheduled refresh jobs, and apps that dispatch tasks to other agents.",
        tools=[*author_tools, *deleg],
        llm=ctx.llm,
        max_iter=60,
        allow_delegation=False,
        verbose=True,
    )

    design = Task(
        description=(
            f"{ctx.today}\n\n"
            "DESIGN. <<IDEA>>\n"
            f"{ctx.prompt}\n"
            "<</IDEA>>\n\n"
            "Use read_lib_api to understand available AIMEAT libraries (especially AIMEAT.extension, AIMEAT.memory, AIMEAT.fetch patterns). "
            "Use read_node_api to understand extension action path conventions and cron schedule syntax. "
            "Use read_cortex_example to see how a cortex calls an extension via callExt / ext action paths. "
            "Decide: (1) What extension action paths are needed (each as `export default async function(ctx, input)`); "
            "(2) What cron schedules if any; (3) What cortex logic calls the extension; "
            "(4) What the app HTML looks like — it must loadScript aimeat-auth.js, aimeat-data.js, every needed AIMEAT.<lib>, and the cortex; "
            "boot = `(await AIMEAT.auth.login()) || AIMEAT.auth.getSession()`. "
            "Produce a compact design: extension action map, cortex call map, app load order, key data flows."
        ),
        expected_output="A compact design: extension action paths + cron schedules (if any) + cortex call map + app HTML load order + key data flows.",
        agent=specialist,
    )

    build = Task(
        description=(
            "BUILD. Using the design from the previous step:\n\n"
            "1. AUTHOR THE EXTENSION: Write the WASM extension with one `export default async function (ctx, input)` per action path. "
            "Use ctx.memory.get/set for private state, ctx.memory.getPublic for shared state, ctx.fetch for external HTTP, "
            "ctx.api.post('/v1/agents/<name>/tasks', ...) for agent task-dispatch. Add cron schedules if needed.\n\n"
            "2. AUTHOR THE CORTEX: Write the cortex that calls the extension via callExt / ext action paths as designed.\n\n"
            "3. AUTHOR THE APP HTML: The app must loadScript (in order): aimeat-auth.js, aimeat-data.js, every AIMEAT.<lib> the cortex uses, and the cortex. "
            "Boot line: `let session = (await AIMEAT.auth.login()) || AIMEAT.auth.getSession();`\n\n"
            "4. INSTALL: Use install_extension to install the extension. Use install_cortex to install the cortex.\n\n"
            "5. PUBLISH: Use publish_app to publish the app and capture the live URL.\n\n"
            "Report: extension installed (action paths confirmed), cortex installed, app published with live URL."
        ),
        expected_output="Extension installed (action paths confirmed) + cortex installed + app published with the live URL.",
        agent=specialist,
        context=[design],
    )

    verify = Task(
        description=(
            "VERIFY. Use verify_render(filename, expect_csv) on the published app until VERIFY PASS.\n\n"
            "If verify_render returns anything other than VERIFY PASS:\n"
            "- Diagnose the failure (check load order, missing scripts, boot line, extension action paths, cortex calls).\n"
            "- Fix the issue (update extension, cortex, or app HTML as needed).\n"
            "- Re-install/re-publish if changes were made.\n"
            "- Re-run verify_render.\n"
            "- Retry up to 3 times total.\n\n"
            "Do NOT stop until verify_render returns VERIFY PASS."
        ),
        expected_output="VERIFY PASS + live URL of the published app.",
        agent=specialist,
        context=[build],
    )

    return [specialist], [design, build, verify]


def run() -> None:
    run_crew(CrewSpec(agent_name=AGENT_NAME, build_domain=build_domain, readme_md=README, temperature=0.4))


if __name__ == "__main__":
    run()
