"""aimeat-app-editor: generated by crew-forge on the AIMEAT scaffold (crewaimeat).

Only build_domain below is crew-specific; crewaimeat.aimeat_crew.run_crew provides the
AIMEAT wiring (onboarding, daemon, liaison publish/complete, live progress, date
injection). See SCAFFOLD_CANON.md. Register + approve before running:
  npx aimeat@latest connect add --agent aimeat-app-editor --mode task-runner --url https://aimeat.io --owner <your-aimeat-account>

Run: uv run python crews/aimeat_app_editor_crew.py
"""

from __future__ import annotations

from crewaimeat.author_tool import make_author_tools

from crewai import Agent, Task

from crewaimeat.aimeat_crew import BuildContext, CrewSpec, run_crew

AGENT_NAME = "aimeat-app-editor"

README = '''[[FIGLET:slant]["aimeat app editor"]]

Edit any existing AIMEAT app safely — in place, surgically, verified.
How to task me: Give me the app's inline URL + the change you want. I investigate the stack, modify only what's needed, re-install/publish, and verify until the applicable gates PASS.
'''


def build_domain(ctx: BuildContext) -> tuple[list[Agent], list[Task]]:
    tid = (ctx.task or {}).get("id") or "manual"
    author_tools, _state = make_author_tools(AGENT_NAME, task_id=tid)

    specialist = Agent(
        role="AIMEAT App Editor Specialist",
        goal="Safely edit an EXISTING AIMEAT app (and its cortex/extension) IN PLACE — reuse the same names so every change updates the existing artifact, modify only artifacts in the app's stack map, and continue until the applicable verify gates PASS.",
        backstory=(
            "You are an expert AIMEAT app editor. You use make_author_tools to read, modify, re-install, "
            "re-publish, and verify existing apps. You ALWAYS start by calling read_app_stack(url) to confirm "
            "the app exists and to get the full stack map (app filename/owner, cortex(es) + methods, "
            "extension(es) + actions, memory key hints), then read_app_source(url) for the FULL verbatim "
            "source. You modify ONLY artifacts that appear in that stack map: UI changes → the app HTML; "
            "data-logic changes → the cortex; server-side changes → the extension. This app uses ONE cortex — "
            "modify the existing cortex in place; keep it a single cortex rather than adding a second "
            "component/widget cortex. You re-author and re-install_cortex / install_extension / publish_app "
            "using the SAME names so everything updates in place, and you preserve every feature that already "
            "works. You load aimeat-auth.js, aimeat-data.js, the cortex, and every AIMEAT.<lib> the cortex "
            "uses, and you keep the golden rule: run every data/cortex call only AFTER "
            "`await AIMEAT.auth.login()` resolves, inside startApp(session) (read_app_template() shows the "
            "canonical boot()/startApp wiring). Preserve the existing app's working boot; if your edit touches "
            "data loading or the boot sequence, keep that await-login-first order so the 'Not logged in' race "
            "stays prevented. For server-side logic you author an extension with "
            "`export default async function(ctx, input)`. You continue the fix loop until the applicable "
            "verify gates PASS (at most 3 rounds)."
        ),
        tools=[*author_tools],
        llm=ctx.llm,
        max_iter=60,  # investigate + edit + up to 3 verify-fix rounds (re-author/re-install/re-publish/re-verify)
        allow_delegation=False,
        verbose=True
    )

    investigate = Task(
        description=(
            f"{ctx.today}\n\n"
            "INVESTIGATE. Goal: understand the existing app's full stack and confirm the exact change needed.\n\n"
            "<<TASK REQUEST>>\n"
            f"{ctx.prompt}\n"
            "<</TASK REQUEST>>\n\n"
            "HARD REQUIREMENT — extract the app's inline URL from the TASK REQUEST above. It looks like "
            "`https://<node>/v1/apps/<owner>/<file>.html?mode=inline`. If the TASK REQUEST contains no such "
            "URL, REFUSE immediately and ask the user for it. Never guess a target. Never pick an app from a "
            "list and never call read_node_api on /v1/apps to choose a target — the ONLY valid target is the "
            "exact URL in the TASK REQUEST.\n\n"
            "Step 1: Call read_app_stack(url) with THAT EXACT inline URL from the TASK REQUEST. "
            "This confirms the app exists via the apps API and returns the full stack map:\n"
            "  - app filename + owner\n"
            "  - cortex(es): names, methods, source hints\n"
            "  - extension(es): names, actions, source hints\n"
            "  - memory key hints\n\n"
            "If read_app_stack reports the app is NOT FOUND — ABORT. Report the error and stop.\n\n"
            "Step 1b — SAME-OWNER CHECK (publish_app and verify_render run under YOUR OWN owner, not the "
            "URL's owner): call app_inline_url(<the <file>.html filename from the TASK REQUEST URL>). The URL "
            "it returns contains YOUR owner. Compare that owner to the <owner> segment in the TASK REQUEST URL "
            "(/v1/apps/<owner>/<file>.html). If they MATCH, continue. If they DIFFER, REFUSE and stop: 'I can "
            "edit apps only under my own owner — publish_app and verify_render are scoped to it, so editing "
            "another owner's app would create a duplicate under my owner and verify the wrong app, not edit "
            "theirs.' Editing in place is only possible for a same-owner target.\n\n"
            "Step 2: Call read_app_source(url) with THAT EXACT inline URL to load the FULL verbatim app HTML "
            "PLUS every cortex lib it loads (read_app_stack returns only a TRUNCATED stack MAP, not source; "
            "read_node_api truncates too — neither gives you the real source). EDIT every artifact IN PLACE "
            "from this exact verbatim text, never re-author from memory: rewriting from memory silently drops "
            "working features (the classic regression 'fixed the viewer, lost the post form'). Keep every line "
            "you are not deliberately changing byte-for-byte.\n\n"
            "Step 3: Restate the full stack (what's there) AND the exact change the task asks for. "
            "Identify which artifact(s) must be modified:\n"
            "  - UI/visual change → the app HTML file\n"
            "  - data-logic / client-side logic change → the cortex\n"
            "  - server-side logic change → the extension\n"
            "  - memory/schema change → seed_memory + possibly cortex\n\n"
            "Output: a compact investigation report with the stack summary + the exact change plan."
        ),
        expected_output=(
            "Investigation report: (1) app URL confirmed via read_app_stack, (2) full stack map restated "
            "(app, cortex(es), extension(es), memory hints), (3) exact change identified with target artifact(s) "
            "specified, (4) current source of to-be-modified artifacts read and summarized."
        ),
        agent=specialist
    )

    edit = Task(
        description=(
            "EDIT. Goal: surgically modify ONLY the artifact(s) identified in the investigation, "
            "then re-install and re-publish everything in place.\n\n"
            "<<TASK REQUEST>>\n"
            f"{ctx.prompt}\n"
            "<</TASK REQUEST>>\n\n"
            "Rules:\n"
            "  - Modify ONLY artifacts that appeared in the read_app_stack result. Never touch a different app's cortex/extension.\n"
            "  - Preserve everything that already works. Change ONLY what the task asks.\n"
            "  - Use the SAME names for cortex, extension, and app — this updates in place, never creates duplicates.\n\n"
            "For a UI change:\n"
            "  - Modify the app HTML file surgically.\n"
            "  - Ensure the app still loads aimeat-auth.js, aimeat-data.js, every needed AIMEAT.<lib>, and the cortex.\n"
            "  - Preserve the app's existing boot; if you touch it, keep read_app_template()'s canonical order: "
            "`const session = await AIMEAT.auth.login();` then run startApp(session) only after it resolves. "
            "For a PUBLIC/anon viewer keep startApp() UNCONDITIONAL (no `if (session)`) so anonymous visitors render.\n"
            "  - Call publish_app to update the app in place.\n\n"
            "For a data-logic / cortex change:\n"
            "  - Modify the cortex source surgically.\n"
            "  - Call install_cortex with the SAME name to update it in place.\n"
            "  - If the app HTML references the cortex, ensure the reference is still correct, then publish_app.\n\n"
            "For a server-side / extension change:\n"
            "  - Modify the extension source surgically (top-level `export default async function(ctx, input)`).\n"
            "  - Call install_extension with the SAME name to update it in place.\n"
            "  - If the cortex calls the extension, ensure the action names still match.\n\n"
            "For a memory/schema change:\n"
            "  - Call seed_memory with the updated schema/data.\n"
            "  - Update the cortex if it references memory keys.\n\n"
            "After all modifications, call publish_app to push the updated app.\n\n"
            "Output: confirmation of every artifact modified, every install/publish call made, and the live URL."
        ),
        expected_output=(
            "Edit report: (1) list of artifacts modified (with before/after summary of changes), "
            "(2) install_cortex / install_extension / publish_app calls confirmed with same names, "
            "(3) live app URL."
        ),
        agent=specialist,
        context=[investigate]
    )

    verify = Task(
        description=(
            "VERIFY. Goal: confirm the edited app renders correctly AND still works for every audience.\n\n"
            "Step 1: Call verify_render(filename, expect_csv) on the published app. The filename is the "
            "<file>.html segment of the inline URL (verify_render rebuilds the URL under your own owner — "
            "which the Step 1b same-owner check already confirmed matches the target).\n\n"
            "Step 2: If verify_render returns VERIFY FAIL, go to Step 3. If verify_render returns VERIFY "
            "PASS it is NOT necessarily done — verify_render logs in as the OWNER and checks only the initial "
            "render, so it FALSE-PASSes two app classes. Run the applicable extra gate(s):\n"
            "  - PUBLIC / anon-readable app (anyone reads it WITHOUT logging in): run verify_anon_render("
            "filename, expect_csv) with expect_csv = strings that MUST appear in the public view. It loads "
            "with NO login and catches a viewer that renders only for a session (the `if (session) "
            "startApp()` bug that strands anonymous visitors on 'Loading…').\n"
            "  - INTERACTIVE app, or your edit touched an interactive feature (a button/form/game/live data): "
            "run verify_interaction(filename, steps_json) driving the edited feature with the app's REAL "
            "selectors. Use ONLY non-destructive, read-or-create-your-own steps — never click controls that "
            "hide/delete/modify shared or other users' content (a test must not mutate live/shared state).\n"
            "  GREEN only when verify_render PASSES AND (if public) verify_anon_render PASSES AND (if "
            "interactive) verify_interaction PASSES. If any applicable extra gate FAILS, treat it like a "
            "VERIFY FAIL and go to Step 3. When GREEN, report PASS + the live URL, then STOP — do not "
            "re-publish or re-verify after GREEN.\n\n"
            "Step 3: If a verify gate returns FAIL:\n"
            "  - Read the HINT line in the verify output (it maps the failure signature to the likely "
            "artifact) and follow it. Before editing, re-read read_app_source(url) so you fix ONLY the "
            "failure and keep every other feature byte-for-byte.\n"
            "  - If the console error is 'Not logged in. Call AIMEAT.auth.login() first.' the bug is BOOT "
            "ORDER in the APP HTML — a data/cortex/history call runs before `await AIMEAT.auth.login()` "
            "resolves. Fix the APP HTML (move that call into startApp(session) / after the awaited login), "
            "NOT the cortex. Do not reinstall the cortex for this error.\n"
            "  - Fix the relevant artifact (app HTML, cortex, or extension) surgically.\n"
            "  - Re-install_cortex / install_extension / publish_app as needed (same names, in place).\n"
            "  - Re-run the gate that failed (verify_render, and the applicable extra gates from Step 2).\n"
            "  - Repeat fix + retry up to 3 times maximum.\n\n"
            "Declare success only when the applicable gates ALL PASS (Step 2's GREEN definition).\n\n"
            "Output: GREEN confirmation (which gates passed) + live URL, or a clear failure report after 3 exhausted retries."
        ),
        expected_output=(
            "A GREEN report: verify_render PASS, plus verify_anon_render PASS if the app is public/anon-"
            "readable, plus verify_interaction PASS if the edit touched an interactive feature; the live URL; "
            "and the list of artifacts changed. If still failing after 3 rounds: the exact failing-gate text "
            "+ diagnosis."
        ),
        agent=specialist,
        context=[edit]
    )

    return [specialist], [investigate, edit, verify]


def run() -> None:
    run_crew(CrewSpec(agent_name=AGENT_NAME, build_domain=build_domain, readme_md=README, temperature=0.4, poll_seconds=30))


if __name__ == "__main__":
    run()
