"""aimeat-sdlc-architect: generated by crew-forge on the AIMEAT scaffold (crewaimeat).

Only build_domain below is crew-specific; crewaimeat.aimeat_crew.run_crew provides the
AIMEAT wiring (onboarding, daemon, liaison publish/complete, live progress, date
injection). See SCAFFOLD_CANON.md. Register + approve before running:
  npx aimeat@latest connect add --agent aimeat-sdlc-architect --mode task-runner --url https://aimeat.io --owner <your-aimeat-account>

Run: uv run python crews/aimeat_sdlc_architect_crew.py
"""

from __future__ import annotations

from crewaimeat.author_tool import make_author_tools
from crewaimeat.workflow import make_workflow_tools

from crewai import Agent, Task

from crewaimeat.aimeat_crew import BuildContext, CrewSpec, run_crew
from crewaimeat.crew import _web_tools  # Tavily web search if TAVILY_API_KEY is set, else []

AGENT_NAME = "aimeat-sdlc-architect"

README = '''```
 █████╗ ██╗███╗   ███╗███████╗ █████╗ ████████╗
██╔══██╗██║████╗ ████║██╔════╝██╔══██╗╚══██╔══╝
███████║██║██╔████╔██║█████╗  ███████║   ██║
██╔══██║██║██║╚██╔╝██║██╔══╝  ██╔══██║   ██║
██║  ██║██║██║ ╚═╝ ██║███████╗██║  ██║   ██║
╚═╝  ╚═╝╚═╝╚═╝     ╚═╝╚══════╝╚═╝  ╚═╝   ╚═╝
 ███████╗██████╗ ██╗      ██████╗
 ██╔════╝██╔══██╗██║     ██╔════╝
 ███████╗██║  ██║██║     ██║
 ╚════██║██║  ██║██║     ██║
 ███████║██████╔╝███████╗╚██████╗
 ╚══════╝╚═════╝ ╚══════╝ ╚═════╝
  █████╗ ██████╗  ██████╗██╗  ██╗
 ██╔══██╗██╔══██╗██╔════╝██║  ██║
 ███████║██████╔╝██║     ███████║
 ██╔══██║██╔══██╗██║     ██╔══██║
 ██║  ██║██║  ██║╚██████╗██║  ██║
 ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝
```
AIMEAT SDLC Crew Architect — designs focused AIMEAT app/extension builder crews for any requested domain.
How to task me: "Design a new AIMEAT-SDLC specialist crew for the domain: <your domain description>"
'''


def build_domain(ctx):
    tid = (ctx.task or {}).get("id") or "manual"
    author_tools, _state = make_author_tools(AGENT_NAME, task_id=tid)
    wf = make_workflow_tools(coordinator_name=AGENT_NAME, run_id=tid, task_id=tid, tag="workflow", timeout=1800)
    deleg = [t for t in wf if getattr(t, "name", "") in ("discover_crews", "delegate_and_wait")]
    specialist = Agent(
        role="AIMEAT SDLC Crew Architect",
        goal="Design focused AIMEAT app/extension builder crews for any requested domain, using the direct-build toolkit (make_author_tools). Each designed crew must author, install, publish, and VERIFY real AIMEAT apps — never generate placeholder code. Every app starts from read_app_template() for correct auth wiring, uses read_lib_api to discover real APIs/events, and gates completion on verify_render PASS.",
        backstory="You are an expert AIMEAT SDLC architect who specializes in designing builder crews that produce working AIMEAT applications. You know the platform cold: every app STARTS from read_app_template() (it wires auth correctly — loads aimeat-auth.js + aimeat-data.js, mounts the login bar, and runs startApp(session) ONLY after `await AIMEAT.auth.login()`, so there is no boot-order race). Inside boot() you add a loadScript for the cortex + every AIMEAT.<lib> it uses. Server-side logic is an extension (one top-level `export default async function (ctx, input)`). You AUTHOR STRICTLY AGAINST read_lib_api — it covers /v1/libs AND /lib libs and reports each lib's methods AND emitted EVENT names — you never GUESS an API or event name. The build is not done until verify_render returns VERIFY PASS. You adapt the proven Design→Build→Verify structure to whatever domain the user requests, changing roles, goals, and prompts while keeping the make_author_tools wiring and the final verify_render gate.",
        tools=[*author_tools, *deleg], llm=ctx.llm, max_iter=60, allow_delegation=False, verbose=True)
    design = Task(
        description=(
            f"{ctx.today}\n\n"
            "DESIGN. You are designing a NEW AIMEAT-SDLC specialist crew for a specific domain.\n"
            "<<IDEA>>\n"
            f"{ctx.prompt}\n"
            "<</IDEA>>\n\n"
            "Use read_lib_api to discover available AIMEAT libraries and their APIs. "
            "Use read_app_template to understand the correct app boot structure. "
            "Use read_node_api to understand available node types if the domain involves node-based logic. "
            "Use read_cortex_example to see cortex patterns if the domain needs a cortex.\n\n"
            "Decide: does this domain need a cortex? An extension for server logic? What AIMEAT.<lib> modules are required? "
            "What is the key data model / interaction map?\n\n"
            "Produce a compact design document covering:\n"
            "1. The kebab-case agent name (aimeat-<domain>-builder)\n"
            "2. The specialist role, goal, and backstory (adapted to the domain)\n"
            "3. The 3-task pipeline (design→build→verify) with domain-specific task descriptions\n"
            "4. Which AIMEAT libraries and APIs are needed\n"
            "5. Whether a cortex and/or extension is required\n"
            "6. The verification strategy (verify_render + verify_interaction if interactive)"
        ),
        expected_output="A compact design document for the new AIMEAT-SDLC specialist crew, covering agent name, role, goal, backstory, 3-task pipeline, required libraries, cortex/extension needs, and verification strategy.",
        agent=specialist)
    build = Task(
        description=(
            "BUILD. Using the design from the previous task, author the complete crew Python file.\n\n"
            "The file must contain:\n"
            "- AGENT_NAME: the kebab-case aimeat- name\n"
            "- TEMPERATURE: 0.4\n"
            "- EXTRA_IMPORTS: from crewaimeat.author_tool import make_author_tools; from crewaimeat.workflow import make_workflow_tools\n"
            "- README: short markdown with figlet header, one-line purpose, and 'How to task me' line\n"
            "- BUILD_DOMAIN: the full def build_domain(ctx): function\n\n"
            "Inside build_domain:\n"
            "- Call make_author_tools(AGENT_NAME, task_id=tid) to get author_tools\n"
            "- Call make_workflow_tools and filter for discover_crews + delegate_and_wait\n"
            "- Create an Agent with role/goal/backstory adapted to the requested domain, tools=[*author_tools, *deleg], llm=ctx.llm, max_iter=60\n"
            "- Create 3 Tasks: design → build → verify\n"
            "- The verify task MUST use verify_render(filename, expect_csv) until VERIFY PASS, with fix+retry <=3\n"
            "- If the domain app is interactive, verify_interaction is also required\n"
            "- Return (agents, tasks)\n\n"
            "Use install_cortex if a cortex was authored. Use install_extension if server logic was authored. "
            "Use publish_app to publish the app. Use verify_render to confirm the app renders correctly.\n\n"
            "Write the complete crew file content."
        ),
        expected_output="The complete AIMEAT-SDLC specialist crew Python file content, ready to be saved and executed.",
        agent=specialist, context=[design])
    verify = Task(
        description=(
            "VERIFY. Confirm the crew file is structurally correct and complete.\n\n"
            "Check:\n"
            "1. The file has all 5 labeled sections: AGENT_NAME, TEMPERATURE, EXTRA_IMPORTS, README, BUILD_DOMAIN\n"
            "2. build_domain uses make_author_tools(AGENT_NAME, task_id=tid)\n"
            "3. build_domain creates an Agent with tools=[*author_tools, *deleg] and llm=ctx.llm\n"
            "4. build_domain creates exactly 3 tasks: design, build, verify (in that order)\n"
            "5. The verify task description includes verify_render until VERIFY PASS with fix+retry <=3\n"
            "6. build_domain returns (agents, tasks)\n"
            "7. The specialist's backstory mentions read_app_template() boot order, read_lib_api for API discovery, and the verify_render gate\n\n"
            "If any check fails, fix the crew file and re-verify. Retry up to 3 times.\n\n"
            "Output the final verified crew file content."
        ),
        expected_output="A verified, complete AIMEAT-SDLC specialist crew file with all 5 sections, correct build_domain structure, and verify_render gate.",
        agent=specialist, context=[build])
    return [specialist], [design, build, verify]


def run() -> None:
    run_crew(CrewSpec(agent_name=AGENT_NAME, build_domain=build_domain, readme_md=README, temperature=0.4))


if __name__ == "__main__":
    run()
