"""aimeat-realtime-presence-board-builder: generated by crew-forge on the AIMEAT scaffold (crewaimeat).

Only build_domain below is crew-specific; crewaimeat.aimeat_crew.run_crew provides the
AIMEAT wiring (onboarding, daemon, liaison publish/complete, live progress, date
injection). See SCAFFOLD_CANON.md. Register + approve before running:
  npx aimeat@latest connect add --agent aimeat-realtime-presence-board-builder --mode task-runner --url https://aimeat.io --owner <your-aimeat-account>

Run: uv run python crews/aimeat_realtime_presence_board_builder_crew.py
"""

from __future__ import annotations

from crewai import Agent, Task

from crewaimeat.aimeat_crew import CrewSpec, run_crew
from crewaimeat.author_tool import make_author_tools
from crewaimeat.workflow import make_workflow_tools

AGENT_NAME = "aimeat-realtime-presence-board-builder"

README = """```
  ____            _           _     ____                _ _     _            
 |  _ \\ ___ _ __ | | __ _  __| |   |  _ \\ ___ _ __ ___ | (_)___(_) ___  _ __ 
 | |_) / _ \\ '_ \\| |/ _` |/ _` |   | |_) / _ \\ '_ ` _ \\| | / __| |/ _ \\| '_ \\
 |  _ <  __/ |_) | | (_| | (_| |   |  __/  __/ | | | | | | \\__ \\ | (_) | | | |
 |_| \\_\\___| .__/|_|\\__,_|\\__|   |_|   \\___|_| |_| |_|_|_|___/_|\\___/|_| |_|
           |_|                                                               
```
**Purpose:** Build AIMEAT-native realtime presence board apps using the AimeatRealtime `/lib/realtime.js` presence+broadcast API — ephemeral realtime-only state, peer presence lists, broadcast notes feeds, auth-gated posting, and anonymous visitor support.

**How to task me:** Give me a presence board concept (e.g. "team standup board", "live audience Q&A", "realtime study room") and I'll design, build, install, publish, and fully verify a working AIMEAT app — cortex + app HTML — ending with `verify_render PASS` and (for interactive boards) `verify_interaction PASS`.
"""


def build_domain(ctx):
    tid = (ctx.task or {}).get("id") or "manual"
    author_tools, _state = make_author_tools(AGENT_NAME, task_id=tid)
    wf = make_workflow_tools(coordinator_name=AGENT_NAME, run_id=tid, task_id=tid, tag="workflow", timeout=1800)
    deleg = [t for t in wf if getattr(t, "name", "") in ("discover_crews", "delegate_and_wait")]
    specialist = Agent(
        role="AIMEAT Realtime Presence Board Specialist",
        goal="Author, install, publish, and fully verify an AIMEAT-native realtime presence board app — one cortex + one app HTML — using the AimeatRealtime /lib/realtime.js presence+broadcast API, with ephemeral realtime-only state (no persistent memory keys), presence list from peer-joined/peer-left events, notes feed from broadcast events, auth-gated note posting, unconditional startApp() for anonymous visitors, and stable DOM selectors for testing",
        backstory="Expert AIMEAT realtime app builder. Uses make_author_tools for the full direct-build toolkit. ALWAYS starts the app HTML from read_app_template('public_viewer') — this wires auth correctly (loads aimeat-auth.js + aimeat-data.js, mounts the login bar, and runs startApp(session) ONLY after await AIMEAT.auth.login(), so there is no boot-order race). Inside boot() adds loadScript for the cortex + AIMEAT.Realtime from /lib/realtime.js. AUTHORS STRICTLY AGAINST read_lib_api — reads the real /lib/realtime.js API to get every method AND every emitted EVENT name (peer-joined, peer-left, broadcast, etc.) — never guesses. For any server-side logic authors a separate extension (export default async function(ctx, input)). Uses read_cortex_example for cortex patterns and read_node_api for server-side APIs. The app uses ephemeral realtime-only state — no persistent memory keys. Anonymous visitors get unconditional startApp() so they can see the presence board without logging in. All interactive elements use stable data-testid or id selectors for verify_interaction. Ends every build with verify_render until VERIFY PASS, plus verify_interaction for the interactive note-posting feature.",
        tools=[*author_tools, *deleg],
        llm=ctx.llm,
        max_iter=60,
        allow_delegation=False,
        verbose=True,
    )

    design = Task(
        description=(
            f"{ctx.today}\n\n"
            "DESIGN. <<IDEA>>\n"
            f"{ctx.prompt}\n"
            "<</IDEA>>\n\n"
            "Read read_lib_api for /lib/realtime.js to get the EXACT method names and EVENT names "
            "(peer-joined, peer-left, broadcast, etc.) — do NOT guess. "
            "Read read_app_template('public_viewer') to get the correct auth-wired HTML shell. "
            "Read read_node_api for any server-side APIs if an extension is needed. "
            "Read read_cortex_example for cortex authoring patterns.\n\n"
            "Decide: cortex logic + extension (if any) + app HTML structure. "
            "Key map: presence list DOM id, notes feed DOM id, note-input DOM id, post-button DOM id, "
            "auth-gated vs anon-readable sections. "
            "All selectors must be stable (data-testid or id) for verify_interaction.\n\n"
            "Output a compact design: what the cortex does, what the extension does (if any), "
            "what the app HTML does, the DOM id map, and the realtime event flow."
        ),
        expected_output="Compact design: cortex + extension (if any) responsibilities, app HTML structure, stable DOM id selector map, realtime event flow (peer-joined/peer-left/broadcast), auth-gating strategy for note posting, anon visitor startApp() path.",
        agent=specialist,
    )

    build = Task(
        description=(
            "BUILD. Author ONE cortex (+ extension if server logic is needed) + ONE app HTML.\n\n"
            "App HTML MUST be STARTED from read_app_template('public_viewer') — keep its "
            "await-login/startApp boot order intact. Inside boot() add loadScript for the cortex "
            "+ AIMEAT.Realtime from /lib/realtime.js. Use ONLY the method and event names from "
            "read_lib_api — no guessing.\n\n"
            "App behavior:\n"
            "- Ephemeral realtime-only state — NO persistent memory keys.\n"
            "- Presence list populated from peer-joined / peer-left realtime events.\n"
            "- Notes feed populated from broadcast realtime events.\n"
            "- Auth-gated note posting: only logged-in users can post; anonymous visitors see read-only.\n"
            "- Unconditional startApp() for anonymous visitors so the board is visible without login.\n"
            "- Stable DOM selectors (data-testid or id) on every interactive element.\n\n"
            "Install: install_cortex for the cortex, install_extension for the extension (if any), "
            "then publish_app to get the live URL."
        ),
        expected_output="Cortex installed (+ extension if needed) + app published with the live URL. App uses ephemeral realtime state only, has stable DOM selectors, supports anon visitors, and gates note posting behind auth.",
        agent=specialist,
        context=[design],
    )

    verify = Task(
        description=(
            "VERIFY. Run verify_render(filename, expect_csv) until VERIFY PASS. "
            "Fix any failures and retry up to 3 times.\n\n"
            "This app is INTERACTIVE (users click/type to post notes, see presence updates), "
            "so ALSO run verify_interaction(filename, steps_json). Drive the core features "
            "using the app's REAL stable selectors:\n"
            "  1. Load the app as anonymous visitor — expect presence board visible (expect_text).\n"
            "  2. Simulate a peer-join event — expect presence list updated (expect_text).\n"
            "  3. Simulate a broadcast event — expect notes feed updated (expect_text).\n"
            "  4. Log in — expect note input + post button enabled (wait_enabled).\n"
            "  5. Fill note input + click post button — expect note appears in feed (expect_text).\n"
            "  6. Simulate peer-left — expect presence list updated (expect_text).\n\n"
            "Fix any interaction failures and retry until INTERACTION PASS.\n\n"
            "Not done until BOTH verify_render PASS and verify_interaction PASS."
        ),
        expected_output="verify_render PASS + verify_interaction PASS + live URL. All presence board features verified: anon-readable, presence list, notes feed, auth-gated posting.",
        agent=specialist,
        context=[build],
    )

    return [specialist], [design, build, verify]


def run() -> None:
    run_crew(CrewSpec(agent_name=AGENT_NAME, build_domain=build_domain, readme_md=README, temperature=0.4))


if __name__ == "__main__":
    run()
