"""aimeat-app-editor: generated by crew-forge on the AIMEAT scaffold (crewaimeat).

Only build_domain below is crew-specific; crewaimeat.aimeat_crew.run_crew provides the
AIMEAT wiring (onboarding, daemon, liaison publish/complete, live progress, date
injection). See SCAFFOLD_CANON.md. Register + approve before running:
  npx aimeat@latest connect add --agent aimeat-app-editor --mode task-runner --url https://aimeat.io --owner <your-aimeat-account>

Run: uv run python crews/aimeat_app_editor_crew.py
"""

from __future__ import annotations

from crewaimeat.author_tool import make_author_tools
from crewaimeat.workflow import make_workflow_tools

from crewai import Agent, Task

from crewaimeat.aimeat_crew import BuildContext, CrewSpec, run_crew
from crewaimeat.crew import _web_tools  # Tavily web search if TAVILY_API_KEY is set, else []

AGENT_NAME = "aimeat-app-editor"

README = '''  ___ _            _       _       ___    _ _ _
 / _ (_) __ _ _ __| |_    /_\\   _  | __|__| (_) |__
 / /_\\/ |/ _` | '__| __|  / _ \\ (_) | _/ _` | | '_ \\
/ /_\\\\| | (_| | |  | |_  /_/ \\_\\     | (_| | | |_./
\\____/|_|\\__,_|_|   \\__|           /__\\__,_|_|___|

Edit any existing AIMEAT app safely — in place, surgically, verified.
How to task me: Give me the app's inline URL + the change you want. I investigate the stack, modify only what's needed, re-install/publish, and verify_render until PASS.
'''


def build_domain(ctx):
    tid = (ctx.task or {}).get("id") or "manual"
    author_tools, _state = make_author_tools(AGENT_NAME, task_id=tid)
    wf = make_workflow_tools(coordinator_name=AGENT_NAME, run_id=tid, task_id=tid, tag="workflow", timeout=1800)
    deleg = [t for t in wf if getattr(t, "name", "") in ("discover_crews", "delegate_and_wait")]

    specialist = Agent(
        role="AIMEAT App Editor Specialist",
        goal="Safely edit and update an EXISTING AIMEAT app (and its cortex/extension) in place — never create duplicates, never touch unrelated artifacts, and always verify_render until VERIFY PASS.",
        backstory=(
            "You are an expert AIMEAT app editor. You use make_author_tools to read, modify, re-install, "
            "re-publish, and verify existing apps. You ALWAYS start by calling read_app_stack(url) to confirm "
            "the app exists and to get the full stack map (app filename/owner, cortex(es) + methods, "
            "extension(es) + actions, memory key hints). You modify ONLY artifacts that appear in that stack map: "
            "UI changes → the app HTML; data-logic changes → the cortex; server-side changes → the extension. "
            "You re-author and re-install_cortex / install_extension / publish_app using the SAME names so "
            "everything updates in place. You preserve everything that already works. You load aimeat-auth.js, "
            "aimeat-data.js, the cortex, and every AIMEAT.<lib> the cortex uses, and you keep the golden rule: "
            "NO data/cortex call runs before the session exists — app code runs only AFTER "
            "`await AIMEAT.auth.login()` resolves (read_app_template() shows the canonical boot()/startApp "
            "wiring). Preserve the existing app's working boot; but if your edit touches data loading or the "
            "boot sequence, keep that await-login-first order so you do not introduce the 'Not logged in' race. "
            "For server-side logic you author an extension with `export default async function(ctx, input)`. "
            "You never stop until verify_render returns VERIFY PASS."
        ),
        tools=[*author_tools, *deleg],
        llm=ctx.llm,
        max_iter=60,
        allow_delegation=False,
        verbose=True
    )

    investigate = Task(
        description=(
            f"{ctx.today}\n\n"
            "INVESTIGATE. Goal: understand the existing app's full stack and confirm the exact change needed.\n\n"
            "<<TASK REQUEST>>\n"
            f"{ctx.prompt}\n"
            "<</TASK REQUEST>>\n\n"
            "HARD REQUIREMENT — extract the app's inline URL from the TASK REQUEST above. It looks like "
            "`https://<node>/v1/apps/<owner>/<file>.html?mode=inline`. If the TASK REQUEST contains no such "
            "URL, REFUSE immediately and ask the user for it. Never guess a target. Never pick an app from a "
            "list and never call read_node_api on /v1/apps to choose a target — the ONLY valid target is the "
            "exact URL in the TASK REQUEST.\n\n"
            "Step 1: Call read_app_stack(url) with THAT EXACT inline URL from the TASK REQUEST. "
            "This confirms the app exists via the apps API and returns the full stack map:\n"
            "  - app filename + owner\n"
            "  - cortex(es): names, methods, source hints\n"
            "  - extension(es): names, actions, source hints\n"
            "  - memory key hints\n\n"
            "If read_app_stack reports the app is NOT FOUND — ABORT. Report the error and stop.\n\n"
            "Step 2: Read the current source of every artifact in the stack map so you know what exists today.\n\n"
            "Step 3: Restate the full stack (what's there) AND the exact change the task asks for. "
            "Identify which artifact(s) must be modified:\n"
            "  - UI/visual change → the app HTML file\n"
            "  - data-logic / client-side logic change → the cortex\n"
            "  - server-side logic change → the extension\n"
            "  - memory/schema change → seed_memory + possibly cortex\n\n"
            "Output: a compact investigation report with the stack summary + the exact change plan."
        ),
        expected_output=(
            "Investigation report: (1) app URL confirmed via read_app_stack, (2) full stack map restated "
            "(app, cortex(es), extension(es), memory hints), (3) exact change identified with target artifact(s) "
            "specified, (4) current source of to-be-modified artifacts read and summarized."
        ),
        agent=specialist
    )

    edit = Task(
        description=(
            "EDIT. Goal: surgically modify ONLY the artifact(s) identified in the investigation, "
            "then re-install and re-publish everything in place.\n\n"
            "<<TASK REQUEST>>\n"
            f"{ctx.prompt}\n"
            "<</TASK REQUEST>>\n\n"
            "Rules:\n"
            "  - Modify ONLY artifacts that appeared in the read_app_stack result. Never touch a different app's cortex/extension.\n"
            "  - Preserve everything that already works. Change ONLY what the task asks.\n"
            "  - Use the SAME names for cortex, extension, and app — this updates in place, never creates duplicates.\n\n"
            "For a UI change:\n"
            "  - Modify the app HTML file surgically.\n"
            "  - Ensure the app still loads aimeat-auth.js, aimeat-data.js, every needed AIMEAT.<lib>, and the cortex.\n"
            "  - Ensure the boot line is: `let session = (await AIMEAT.auth.login()) || AIMEAT.auth.getSession();`\n"
            "  - Call publish_app to update the app in place.\n\n"
            "For a data-logic / cortex change:\n"
            "  - Modify the cortex source surgically.\n"
            "  - Call install_cortex with the SAME name to update it in place.\n"
            "  - If the app HTML references the cortex, ensure the reference is still correct, then publish_app.\n\n"
            "For a server-side / extension change:\n"
            "  - Modify the extension source surgically (top-level `export default async function(ctx, input)`).\n"
            "  - Call install_extension with the SAME name to update it in place.\n"
            "  - If the cortex calls the extension, ensure the action names still match.\n\n"
            "For a memory/schema change:\n"
            "  - Call seed_memory with the updated schema/data.\n"
            "  - Update the cortex if it references memory keys.\n\n"
            "After all modifications, call publish_app to push the updated app.\n\n"
            "Output: confirmation of every artifact modified, every install/publish call made, and the live URL."
        ),
        expected_output=(
            "Edit report: (1) list of artifacts modified (with before/after summary of changes), "
            "(2) install_cortex / install_extension / publish_app calls confirmed with same names, "
            "(3) live app URL."
        ),
        agent=specialist,
        context=[investigate]
    )

    verify = Task(
        description=(
            "VERIFY. Goal: confirm the edited app renders correctly and works.\n\n"
            "Step 1: Call verify_render(filename, expect_csv) on the published app.\n\n"
            "Step 2: If verify_render returns VERIFY PASS — done. Report PASS + the live URL.\n\n"
            "Step 3: If verify_render returns VERIFY FAIL:\n"
            "  - Diagnose the failure from the verify_render output.\n"
            "  - If the console error is 'Not logged in. Call AIMEAT.auth.login() first.' the bug is BOOT "
            "ORDER in the APP HTML — a data/cortex/history call runs before `await AIMEAT.auth.login()` "
            "resolves. Fix the APP HTML (move that call into startApp(session) / after the awaited login), "
            "NOT the cortex. Do not reinstall the cortex for this error.\n"
            "  - Fix the relevant artifact (app HTML, cortex, or extension) surgically.\n"
            "  - Re-install_cortex / install_extension / publish_app as needed (same names, in place).\n"
            "  - Re-run verify_render.\n"
            "  - Repeat fix + retry up to 3 times maximum.\n\n"
            "Do NOT declare success until verify_render returns VERIFY PASS.\n\n"
            "Output: VERIFY PASS confirmation + live URL, or a clear failure report after 3 exhausted retries."
        ),
        expected_output=(
            "VERIFY PASS + live URL. If failed after 3 retries: detailed failure report with "
            "diagnosis and recommended next steps."
        ),
        agent=specialist,
        context=[edit]
    )

    return [specialist], [investigate, edit, verify]


def run() -> None:
    run_crew(CrewSpec(agent_name=AGENT_NAME, build_domain=build_domain, readme_md=README, temperature=0.4))


if __name__ == "__main__":
    run()
