"""aimeat-realtime-builder: generated by crew-forge on the AIMEAT scaffold (crewaimeat).

Only build_domain below is crew-specific; crewaimeat.aimeat_crew.run_crew provides the
AIMEAT wiring (onboarding, daemon, liaison publish/complete, live progress, date
injection). See SCAFFOLD_CANON.md. Register + approve before running:
  npx aimeat@latest connect add --agent aimeat-realtime-builder --mode task-runner --url https://aimeat.io --owner <your-aimeat-account>

Run: uv run python crews/aimeat_realtime_builder_crew.py
"""

from __future__ import annotations

from crewaimeat.author_tool import make_author_tools
from crewaimeat.workflow import make_workflow_tools

from crewai import Agent, Task

from crewaimeat.aimeat_crew import BuildContext, CrewSpec, run_crew
from crewaimeat.crew import _web_tools  # Tavily web search if TAVILY_API_KEY is set, else []

AGENT_NAME = "aimeat-realtime-builder"

README = '''```
 █████╗ ██╗███╗   ███╗███████╗ █████╗ ████████╗
██╔══██╗██║████╗ ████║██╔════╝██╔══██╗╚══██╔══╝
███████║██║██╔████╔██║█████╗  ███████║   ██║
██╔══██║██║██║╚██╔╝██║██╔══╝  ██╔══██║   ██║
██║  ██║██║██║ ╚═╝ ██║███████╗██║  ██║   ██║
╚═╝  ╚═╝╚═╝╚═╝     ╚═╝╚══════╝╚═╝  ╚═╝   ╚═╝
 ██████╗ ███████╗ █████╗ ██╗     ████████╗██╗███╗   ███╗███████╗
 ██╔══██╗██╔════╝██╔══██╗██║     ╚══██╔══╝██║████╗ ████║██╔════╝
 ██████╔╝█████╗  ███████║██║        ██║   ██║██╔████╔██║█████╗
 ██╔══██╗██╔══╝  ██╔══██║██║        ██║   ██║██║╚██╔╝██║██╔══╝
 ██████╔╝███████╗██║  ██║███████╗   ██║   ██║██║ ╚═╝ ██║███████╗
 ╚═════╝ ╚══════╝╚═╝  ╚═╝╚══════╝   ╚═╝   ╚═╝╚═╝     ╚═╝╚══════╝
 ██████╗ ██╗   ██╗██╗     ██████╗ ███████╗██████╗
 ██╔══██╗██║   ██║██║     ██╔══██╗██╔════╝██╔══██╗
 ██████╔╝██║   ██║██║     ██║  ██║█████╗  ██████╔╝
 ██╔══██╗██║   ██║██║     ██║  ██║██╔══╝  ██╔══██╗
 ██████╔╝╚██████╔╝███████╗██████╔╝███████╗██║  ██║
 ╚═════╝  ╚═════╝ ╚══════╝╚═════╝ ╚══════╝╚═╝  ╚═╝
```
**aimeat-realtime-builder** — AIMEAT SDLC specialist crew for authoring, installing, publishing, and verifying real-time multiplayer apps using AimeatRealtime (rooms, presence, live broadcast, throttled high-frequency events).

**How to task me:** "Build a real-time multiplayer [app idea] with rooms, presence, and live message broadcast using AimeatRealtime."
'''


def build_domain(ctx):
    tid = (ctx.task or {}).get("id") or "manual"
    author_tools, _state = make_author_tools(AGENT_NAME, task_id=tid)
    wf = make_workflow_tools(coordinator_name=AGENT_NAME, run_id=tid, task_id=tid, tag="workflow", timeout=1800)
    deleg = [t for t in wf if getattr(t, "name", "") in ("discover_crews", "delegate_and_wait")]
    specialist = Agent(
        role="AIMEAT Realtime Multiplayer Specialist",
        goal="Author + install + publish + verify a real-time multiplayer AIMEAT app using AimeatRealtime — rooms, presence, live message broadcast, rt.on(...) handlers registered BEFORE rt.connect(), high-frequency event throttling — for the user's idea",
        backstory="Expert AIMEAT real-time engineer. Uses make_author_tools to author production-grade realtime apps. "
                  "ALWAYS starts the app HTML from read_app_template() (correct auth wiring: loads aimeat-auth.js + "
                  "aimeat-data.js, mounts the login bar, runs startApp(session) ONLY after await AIMEAT.auth.login() "
                  "— no boot-order race). Inside boot() adds loadScript('/lib/realtime.js') + every AIMEAT.<lib> the "
                  "app uses. Registers all rt.on(...) handlers BEFORE calling rt.connect(). Implements high-frequency "
                  "event throttling (e.g. position updates) via client-side debounce/batch before broadcast. For server-"
                  "side logic (room validation, presence persistence, rate limiting) authors an extension "
                  "(export default async function(ctx, input)). Installs cortex via install_cortex, extension via "
                  "install_extension, publishes via publish_app, and does NOT consider the build done until "
                  "verify_render returns VERIFY PASS.",
        tools=[*author_tools, *deleg], llm=ctx.llm, max_iter=60, allow_delegation=False, verbose=True)

    design = Task(
        description=f"{ctx.today}\n\nDESIGN. <<IDEA>>\n{ctx.prompt}\n<</IDEA>>\n"
                    "FIRST call read_lib_api('realtime') — it returns the REAL AimeatRealtime methods (connect, "
                    "broadcast, createRoom, listRooms, getRoom, presence, on, …) AND the EXACT emitted event names "
                    "(open/close/broadcast/peer-joined/peer-left/…). Author strictly against those; never guess event "
                    "names or signatures. Use read_app_template to get the correct auth-boot scaffold. Use read_node_api for any "
                    "server-side extension needs. Use read_cortex_example for cortex patterns. Decide: cortex logic "
                    "+ extension (if server-side room validation/presence/rate-limiting is needed) + app HTML structure. "
                    "Key map: room lifecycle (create/join/leave), presence tracking, message types (chat, state, "
                    "system), rt.on() handler registration order (ALL handlers before rt.connect()), throttling "
                    "strategy for high-frequency events (e.g. mouse-move, game-tick). Output a compact design.",
        expected_output="A compact design: room model, presence model, message type map, handler registration order, "
                        "throttling strategy, cortex + extension responsibilities, key map.",
        agent=specialist)

    build = Task(
        description="BUILD. Author ONE cortex (+ extension if server logic is needed for room validation, presence "
                    "persistence, or rate limiting) + ONE app STARTED from read_app_template() (keep its await-login/"
                    "startApp boot order). Inside boot() add loadScript('/lib/realtime.js') + every needed "
                    "AIMEAT.<lib>. Register ALL rt.on(...) handlers BEFORE calling rt.connect(), using the EXACT "
                    "event names read_lib_api('realtime') reports — they are 'open' (connection ready -> ENABLE the "
                    "message input here), 'close', 'broadcast' (an INCOMING message; the sender's object is nested "
                    "under msg.payload, NOT the top level), 'peer-joined' / 'peer-left' (presence), 'error'. Do NOT "
                    "use 'connected' / 'disconnected' / 'message' — those events do not exist and the app will "
                    "silently break (input stays disabled, messages never render). You SEND with rt.broadcast(obj); "
                    "the server does NOT echo your own broadcast back to you, so ALSO render your own outgoing message "
                    "locally (optimistic) right after broadcasting. Throttle high-frequency events (debounce/batch) "
                    "before broadcasting. install_cortex (install_extension for server logic). publish_app. Report the live URL.",
        expected_output="Cortex (+ extension if needed) installed + app published with the live URL. rt.on() handlers "
                        "use the REAL event names (open/close/broadcast/peer-joined/peer-left) registered before "
                        "rt.connect(); incoming messages read msg.payload; own messages rendered optimistically.",
        agent=specialist, context=[design])

    verify = Task(
        description="VERIFY with BOTH gates — render THEN interaction (render alone CANNOT catch a broken "
                    "realtime app; it once PASSed a chat where you could not send a message).\n"
                    "Step 1: verify_render(filename, expect_csv) until VERIFY PASS. If VERIFY FAIL, diagnose "
                    "(auth boot order, missing loadScript for realtime.js, handler registration order, throttling, "
                    "extension errors), fix, re-publish, re-run. Up to 3 tries.\n"
                    "Step 2 (REQUIRED): verify_interaction(filename, steps_json) — DRIVE the real feature and "
                    "assert it works. Use YOUR app's real selectors to: create/enter a room, WAIT for the message "
                    "input to become ENABLED (this catches the wrong connect-event-name bug), send a message, and "
                    "assert it appears. Example shape: [{\"do\":\"fill\",\"selector\":\"#new-room-name\",\"value\":\"t\"},"
                    "{\"do\":\"click\",\"selector\":\"#btn-create-room\"},{\"do\":\"wait_enabled\",\"selector\":\"#msg-input\"},"
                    "{\"do\":\"fill\",\"selector\":\"#msg-input\",\"value\":\"hi\"},{\"do\":\"click\",\"selector\":\"#btn-send\"},"
                    "{\"do\":\"expect_text\",\"selector\":\"#messages\",\"text\":\"hi\"}]. If INTERACTION FAIL, the realtime "
                    "wiring is wrong — re-check read_lib_api('realtime') for the EXACT event names ('open' enables "
                    "input, 'broadcast' delivers messages under .payload), fix, re-publish, re-run BOTH gates.\n"
                    "NOT done until verify_render AND verify_interaction BOTH PASS.",
        expected_output="verify_render PASS AND verify_interaction PASS + live URL confirmed actually working "
                        "(message sent and rendered).",
        agent=specialist, context=[build])

    return [specialist], [design, build, verify]


def run() -> None:
    run_crew(CrewSpec(agent_name=AGENT_NAME, build_domain=build_domain, readme_md=README, temperature=0.4))


if __name__ == "__main__":
    run()
