"""daily-briefing-crew: generated by crew-forge on the AIMEAT scaffold (crewaimeat).

Only build_domain below is crew-specific; crewaimeat.aimeat_crew.run_crew provides the
AIMEAT wiring (onboarding, daemon, liaison publish/complete, live progress, date
injection). See SCAFFOLD_CANON.md. Register + approve before running:
  npx aimeat@latest connect add --agent daily-briefing-crew --mode task-runner --url https://aimeat.io --owner <your-aimeat-account>

Run: uv run python crews/daily_briefing_crew_crew.py
"""

from __future__ import annotations

from crewai import Agent, Task

from crewaimeat.aimeat_crew import BuildContext, CrewSpec, run_crew
from crewaimeat.crew import _web_tools  # Tavily web search if TAVILY_API_KEY is set, else []

AGENT_NAME = "daily-briefing-crew"

README = '''[[FIGLET:slant]["Daily Briefing Crew"]]]

Compiles a concise morning briefing: top world news, local weather, and a productivity tip — delivered in a scannable format to start your day informed.

**How to task me:** Send a prompt like "Give me my morning briefing for today" or "What's the briefing for 2026-06-03?" and I'll research and deliver a structured summary.
'''


def build_domain(ctx):
    news_researcher = Agent(
        role="News Researcher",
        goal="Find the top 5 most important world news stories for today, with concise summaries and source URLs.",
        backstory="You are a veteran wire-service journalist with 20 years of experience distilling complex global events into clear, factual summaries. You always verify facts with web search and cite your sources.",
        llm=ctx.llm,
        tools=_web_tools(),
    )

    weather_researcher = Agent(
        role="Weather Researcher",
        goal="Find current weather conditions and a short forecast for the user's location or a default major city.",
        backstory="You are a meteorological data analyst who excels at pulling accurate, up-to-date weather information from trusted sources. You always use web search to get real-time data.",
        llm=ctx.llm,
        tools=_web_tools(),
    )

    productivity_advisor = Agent(
        role="Productivity Advisor",
        goal="Provide one actionable, evidence-based productivity or wellness tip suitable for starting the day.",
        backstory="You are a behavioral science researcher who translates peer-reviewed findings into practical daily habits. You ground every tip in research and explain the 'why' behind it.",
        llm=ctx.llm,
        tools=_web_tools(),
    )

    briefing_editor = Agent(
        role="Briefing Editor",
        goal="Combine all research inputs into a single, well-structured morning briefing with clear sections, emoji headers, and a motivating closing line.",
        backstory="You are a newsletter editor known for crisp, scannable layouts. You never add information that wasn't provided by the researchers — you only organize, format, and polish.",
        llm=ctx.llm,
    )

    task_news = Task(
        description=(
            f"{ctx.today} — Research the top 5 most important world news stories for today. "
            "For each story, provide: a one-sentence headline, a 2-3 sentence summary, and a source URL. "
            "Use web search to find the latest verified news. "
            f"User request: {ctx.prompt}"
        ),
        agent=news_researcher,
        expected_output="A numbered list of 5 news stories, each with a headline, 2-3 sentence summary, and source URL.",
    )

    task_weather = Task(
        description=(
            f"{ctx.today} — Find the current weather and a brief forecast for today. "
            "Include: temperature, conditions (sunny/rainy/etc.), and any notable alerts. "
            "If the user specified a location in their request, use that; otherwise default to a major city. "
            f"User request: {ctx.prompt}"
        ),
        agent=weather_researcher,
        expected_output="Current temperature, conditions, and a short forecast for today, with location noted.",
    )

    task_tip = Task(
        description=(
            f"{ctx.today} — Provide one actionable productivity or wellness tip for today. "
            "Include the tip itself (1-2 sentences) and a brief explanation of why it works (1-2 sentences). "
            "Use web search to find a fresh, research-backed suggestion. "
            f"User request: {ctx.prompt}"
        ),
        agent=productivity_advisor,
        expected_output="One productivity/wellness tip with a brief evidence-based explanation.",
    )

    task_compile = Task(
        description=(
            f"{ctx.today} — Compile the final morning briefing using ONLY the outputs from the News Researcher, "
            "Weather Researcher, and Productivity Advisor. "
            "Format the briefing with these exact sections:\n"
            "🌍 **Top Stories** — the 5 news items\n"
            "🌤️ **Weather** — the weather summary\n"
            "💡 **Tip of the Day** — the productivity tip\n"
            "Close with one short motivational sentence to start the day. "
            "Do NOT invent any facts — use only what the researchers provided."
        ),
        agent=briefing_editor,
        context=[task_news, task_weather, task_tip],
        expected_output="A complete, formatted morning briefing with all three sections and a closing line.",
    )

    agents = [news_researcher, weather_researcher, productivity_advisor, briefing_editor]
    tasks = [task_news, task_weather, task_tip, task_compile]

    return (agents, tasks)


def run() -> None:
    run_crew(CrewSpec(agent_name=AGENT_NAME, build_domain=build_domain, readme_md=README, temperature=0.25))


if __name__ == "__main__":
    run()
