"""daily-brief: generated by crew-forge on the AIMEAT scaffold (crewaimeat).

Only build_domain below is crew-specific; crewaimeat.aimeat_crew.run_crew provides the
AIMEAT wiring (onboarding, daemon, liaison publish/complete, live progress, date
injection). See SCAFFOLD_CANON.md. Register + approve before running:
  npx aimeat@1.34.0 connect --url https://aimeat.io --owner <your-aimeat-account> --agent daily-brief

Run: uv run python crews/daily_brief_crew.py
"""

from __future__ import annotations

from crewai import Agent, Task

from crewaimeat.aimeat_crew import CrewSpec, run_crew

AGENT_NAME = "daily-brief"

README = """[[FIGLET:slant]["Daily Brief"]]
A focused daily-briefing crew that summarizes top news, checks the schedule, and surfaces action items.

**How to task me:** Send a date or a topic focus (e.g. "AI industry news") and I'll return a compact briefing with headlines, any scheduled items, and a short action-reminder list. I do not write long-form reports or perform deep investigative research.
"""


def _tools(ctx):
    """Tool bindings for this crew, written by crew-forge (crewaimeat.forge_catalog).
    Returns {capability_id: [tools]}; reference them in build_domain as _tools(ctx)["<id>"]."""
    from crewaimeat.crew import _web_tools
    from crewaimeat.memory_tools import make_memory_tools

    return {
        "web": _web_tools(),
        "memory": [*make_memory_tools(AGENT_NAME)],
    }


_TAGS = ["role.task-runner", "web-search", "memory-io", "daily-briefing", "news-summary", "schedule"]
_CAPABILITIES = {
    "technical": [{"name": "web-research", "type": "skill"}],
    "domain": ["daily-briefing", "news-summary", "schedule"],
    "languages": ["en"],
}

_OFFER = {
    "id": "daily-brief",
    "title": "Daily Brief",
    "ask": "Send a date or topic focus and receive a concise daily briefing with top news, calendar items, and action reminders; does not do deep investigative research or produce long-form reports.",
    "example": "Give me today's briefing with focus on AI industry news.",
    "cost": "expensive",
    "latency": "long-running",
    "repeatability": "idempotent",
    "verification": "ungated",
    "consequences": [],
    "sample": None,
}


def build_domain(ctx):
    T = _tools(ctx)

    news_gatherer = Agent(
        role="News Gatherer",
        goal="Find and summarize the most relevant news headlines for the user's requested focus",
        backstory="A fast, precise news researcher who scans multiple sources and distills the day's key stories into clean bullet points. Prioritizes accuracy and recency over depth.",
        llm=ctx.llm,
        tools=[*T["web"]],
    )

    schedule_checker = Agent(
        role="Schedule Checker",
        goal="List any scheduled items or reminders relevant to the requested date",
        backstory="An organized coordinator who reads the owner's memory for calendar entries and reminders, then surfaces what matters today. Never invents events that are not stored.",
        llm=ctx.llm,
        tools=[*T["memory"]],
    )

    brief_writer = Agent(
        role="Brief Writer",
        goal="Compose a single concise daily briefing from the gathered news and schedule items",
        backstory="A no-fluff editor who turns raw inputs into a scannable one-page brief: headlines first, schedule next, action items last. Cuts redundancy and keeps it tight.",
        llm=ctx.llm,
        tools=[],
    )

    gather_task = Task(
        description=(
            f"{ctx.today}\n"
            f"The user's request: {ctx.prompt}\n"
            "Search the web for the most relevant and recent news headlines related to the user's focus. "
            "Return 5-10 concise bullet points, each one or two sentences, with the source name. "
            "Prioritize stories from the last 24-48 hours. If the request is date-specific, align results to that date."
        ),
        expected_output="A bullet list of 5-10 top news items with source names, each one or two sentences.",
        agent=news_gatherer,
    )

    schedule_task = Task(
        description=(
            f"{ctx.today}\n"
            f"The user's request: {ctx.prompt}\n"
            "Read the owner's memory for any calendar entries, reminders, or scheduled items relevant to today's date "
            "or the date the user mentioned. Use the memory tool and target the exact keys where schedule data is stored "
            "(e.g. 'schedule', 'reminders', 'calendar'). READ those keys first. "
            "If a key is missing or empty, STOP and report 'No scheduled items found' — do not fabricate events."
        ),
        expected_output="A short list of scheduled items or reminders for the relevant date, or a clear statement that none were found.",
        agent=schedule_checker,
    )

    brief_task = Task(
        description=(
            f"{ctx.today}\n"
            f"User request: {ctx.prompt}\n"
            "Using the gathered news headlines and the schedule items from the prior tasks, compose a single concise daily briefing. "
            "Structure it as:\n"
            "1. **Top News** — the most important headlines as brief bullets.\n"
            "2. **Today's Schedule** — any calendar items or reminders (or 'Nothing scheduled').\n"
            "3. **Action Items** — 2-4 concrete things the user should do today based on the news and schedule.\n"
            "Keep the entire brief under 400 words. Be precise and actionable."
        ),
        expected_output="A structured daily briefing with Top News, Today's Schedule, and Action Items sections, under 400 words.",
        agent=brief_writer,
        context=[gather_task, schedule_task],
    )

    return ([news_gatherer, schedule_checker, brief_writer], [gather_task, schedule_task, brief_task])


def run() -> None:
    run_crew(
        CrewSpec(
            agent_name=AGENT_NAME,
            build_domain=build_domain,
            readme_md=README,
            temperature=0.25,
            tags=_TAGS,
            capabilities=_CAPABILITIES,
            offer=_OFFER,
        )
    )


if __name__ == "__main__":
    run()
