"""editorial-writer: generated by crew-forge on the AIMEAT scaffold (crewaimeat).

Only build_domain below is crew-specific; crewaimeat.aimeat_crew.run_crew provides the
AIMEAT wiring (onboarding, daemon, liaison publish/complete, live progress, date
injection). See SCAFFOLD_CANON.md. Register + approve before running:
  npx aimeat@latest connect add --agent editorial-writer --mode task-runner --url https://aimeat.io --owner <your-aimeat-account>

Run: uv run python crews/editorial_writer_crew.py
"""

from __future__ import annotations

from crewaimeat.memory_tools import make_memory_tools

from crewai import Agent, Task

from crewaimeat.aimeat_crew import BuildContext, CrewSpec, run_crew
from crewaimeat.crew import _web_tools  # Tavily web search if TAVILY_API_KEY is set, else []

AGENT_NAME = "editorial-writer"

README = '''[[FIGLET:slant]["Editorial Writer"]]

Gonzo-journalism editorial writer in the style of Spider Jerusalem — brutal, sharp, unapologetic. Reads the day's articles from owner memory and forges them into a single scorched-earth daily editorial.

**How to task me:** Run with a prompt containing the date (e.g. "2026-06-03") and edition label (e.g. "morning"). I'll pull every article keyed `news.<date>.<edition>.article.<category>`, synthesize them, and publish the editorial to `news.<date>.<edition>.editorial`. As the LAST stage I also build the **public front-page index** `newspaper.frontpage` (under my own GAII) — a single PUBLIC key listing every article + the editorial with its `{gaii, key, title, date, summary}` — so an anonymous public newspaper app can read the whole edition without logging in. No articles? I stop — no fabrications.
'''


def build_domain(ctx):
    # ── Agents ──────────────────────────────────────────────────────────

    article_reader = Agent(
        role="Article Reader",
        goal="Read all article keys for the given date and edition from owner memory. Return the full set of articles, or signal that none exist.",
        backstory=(
            "You are a meticulous archival researcher. Your only job is to pull raw material from memory — "
            "nothing more, nothing less. You never fabricate, never guess. If a key is missing, you say so plainly."
        ),
        llm=ctx.llm,
        tools=[*make_memory_tools(AGENT_NAME)],
    )

    editorial_writer = Agent(
        role="Gonzo Editorialist",
        goal=(
            "Write a savage, razor-sharp daily editorial in the gonzo-journalism tradition of Spider Jerusalem. "
            "Brutal honesty, caustic wit, zero corporate polish. Your voice is unmistakable."
        ),
        backstory=(
            "You are Spider Jerusalem reborn — a gonzo journalist who treats every editorial as a Molotov cocktail. "
            "You take the day's articles and twist them into a single, blistering column that makes readers laugh, "
            "wince, and think. You never hedge. You never bore. You write like the city is on fire and you're the "
            "only one with a working pen."
        ),
        llm=ctx.llm,
    )

    publisher = Agent(
        role="Publisher",
        goal=(
            "Write the completed editorial to its public key, then build the PUBLIC front-page index "
            "`newspaper.frontpage` (under this agent's own GAII) so an anonymous public newspaper app can "
            "read the whole edition — every article + the editorial, each with its {gaii, key, title, "
            "date, summary} — without anyone logging in."
        ),
        backstory=(
            "You are the final gatekeeper AND the front-page editor. You publish the editorial where the "
            "world can see it, then assemble the single public index the public viewer reads: one entry per "
            "article (pointing at the WRITER agent's GAII + key) plus the editorial (your own GAII + key). "
            "You are precise: you copy each article's GAII verbatim, you set everything public, and you never "
            "invent a key or a gaii — every entry points at a real public body you can name."
        ),
        llm=ctx.llm,
        tools=[*make_memory_tools(AGENT_NAME)],
    )

    # ── Tasks ─────────────────────────────────────────────────────────

    read_articles = Task(
        description=(
            f"{ctx.today}\n\n"
            f"<<TASK REQUEST>>\n{ctx.prompt}\n<</TASK REQUEST>>\n\n"
            "From the TASK REQUEST above, determine the DATE and the EDITION (e.g. '2026-06-03' + "
            "'morning') for this editorial. If the request does not name an edition, default to the "
            "edition that has the most articles for today. Use that exact date + edition in every key "
            "below.\n\n"
            "Read all article keys from owner memory matching the pattern "
            "`news.<date>.<edition>.article.<category>` using list_memory with prefix "
            "`news.<date>.` to discover what editions and categories exist (list_memory prints each row "
            "as `- <key> | gaii=<owner_gaii> | <visibility>` — KEEP the gaii, you need it downstream).\n\n"
            "For each discovered article key, read its full content with read_memory.\n\n"
            "If NO article keys exist at all, STOP and return exactly: NO_ARTICLES_FOUND\n\n"
            "Otherwise, return a structured summary of every article you found, including:\n"
            "- The full key for each article (e.g. `news.2026-06-03.morning.article.talous`)\n"
            "- The GAII that OWNS that key — copy it VERBATIM from the `gaii=` field list_memory prints for "
            "that row (it is the article author's GAII, e.g. `news-writer#owner@node`). If the same "
            "category appears under more than one gaii (one agent wrote it, another copied it), prefer the "
            "row whose gaii is the news/article writer that actually produced the content.\n"
            "- The date, edition, and category parsed from the key (`news.<date>.<edition>.article.<cat>`)\n"
            "- The full text of each article\n\n"
            "Do NOT fabricate any content. Only return what you actually read from memory."
        ),
        agent=article_reader,
        expected_output=(
            "Either the string NO_ARTICLES_FOUND, or a structured collection of all articles — for each: "
            "the full key, its owner GAII (verbatim from list_memory), the date/edition/category, and the "
            "full text."
        ),
    )

    write_editorial = Task(
        description=(
            f"{ctx.today}\n\n"
            "You are Spider Jerusalem. Write a gonzo-journalism editorial that synthesizes ALL the articles "
            "provided by the Article Reader into a single, devastating daily column.\n\n"
            "Style rules:\n"
            "- Brutal, sharp, unapologetic — no corporate hedging, no both-sides cowardice\n"
            "- Strong first-person voice; you have opinions and you share them like grenades\n"
            "- Caustic wit, vivid imagery, the occasional profanity where it earns its place\n"
            "- Weave between articles naturally — find the threads that connect them\n"
            "- Open with a hook that grabs by the throat; close with a line that lingers\n"
            "- This is GONZO journalism: subjective, immersive, literary, angry\n\n"
            "If the previous task returned NO_ARTICLES_FOUND, output exactly: NO_ARTICLES_FOUND\n\n"
            "Otherwise, write the full editorial as plain text. No metadata headers — just the column. "
            "End with the byline '— S.J.' on its own line (just the initials; do not spell out the name)."
        ),
        agent=editorial_writer,
        context=[read_articles],
        expected_output=(
            "Either NO_ARTICLES_FOUND, or the complete gonzo editorial as a single text block."
        ),
    )

    publish_editorial = Task(
        description=(
            f"{ctx.today}\n\n"
            "Take the editorial written by the Gonzo Editorialist and publish it, then build the public "
            "front-page index.\n\n"
            "If the editorial is NO_ARTICLES_FOUND, do nothing and return: NO_ARTICLES_FOUND\n\n"
            "Otherwise:\n"
            "1. Write the editorial to key `news.<date>.<edition>.editorial` with visibility='public' "
            "using write_memory.\n"
            "2. Find the editorial's OWN GAII: call list_memory with prefix `news.<date>.<edition>.editorial` "
            "and read the `gaii=` of that row — that is YOUR GAII (the editorial author).\n"
            "3. Build the PUBLIC FRONT-PAGE INDEX with index_frontpage. Pass entries_json = a JSON array "
            "with ONE entry per ARTICLE plus ONE entry for the EDITORIAL:\n"
            "   - article entry: {\"gaii\":\"<that article's owner GAII from read step — the WRITER agent>\", "
            "\"key\":\"<the article's exact key>\", \"title\":\"<Category capitalized> | <date>\", "
            "\"date\":\"<date>\", \"edition\":\"<edition>\", \"category\":\"<category>\", "
            "\"summary\":\"<one sentence, ~140 chars, drawn from the article>\", \"kind\":\"article\"}\n"
            "   - editorial entry: {\"gaii\":\"<YOUR GAII from step 2>\", "
            "\"key\":\"news.<date>.<edition>.editorial\", \"title\":\"Editorial | <date> <edition>\", "
            "\"date\":\"<date>\", \"edition\":\"<edition>\", \"category\":\"editorial\", "
            "\"summary\":\"<one sentence teaser of the editorial>\", \"kind\":\"editorial\"}\n"
            "   Use each article's REAL owner GAII (verbatim, do not guess) and its REAL key. Every body "
            "these point at is already public. index_frontpage read-modify-writes `newspaper.frontpage` "
            "under your GAII at visibility='public' and returns the PUBLISHER gaii + INDEX_KEY.\n"
            "4. Return a confirmation: the editorial key, the number of front-page entries written, and — "
            "VERBATIM — the PUBLISHER gaii and INDEX_KEY that index_frontpage reported (the public newspaper "
            "app must be pointed at exactly those)."
        ),
        agent=publisher,
        context=[read_articles, write_editorial],
        expected_output=(
            "Confirmation: editorial key written; `newspaper.frontpage` built with N entries "
            "(articles + editorial); and the exact PUBLISHER gaii + INDEX_KEY for the viewer app. "
            "Or NO_ARTICLES_FOUND if no articles existed."
        ),
    )

    agents = [article_reader, editorial_writer, publisher]
    tasks = [read_articles, write_editorial, publish_editorial]

    return (agents, tasks)


def run() -> None:
    run_crew(CrewSpec(agent_name=AGENT_NAME, build_domain=build_domain, readme_md=README, temperature=0.7))


if __name__ == "__main__":
    run()
