"""editorial-writer: generated by crew-forge on the AIMEAT scaffold (crewaimeat).

Only build_domain below is crew-specific; crewaimeat.aimeat_crew.run_crew provides the
AIMEAT wiring (onboarding, daemon, liaison publish/complete, live progress, date
injection). See SCAFFOLD_CANON.md. Register + approve before running:
  npx aimeat@latest connect add --agent editorial-writer --mode task-runner --url https://aimeat.io --owner <your-aimeat-account>

Run: uv run python crews/editorial_writer_crew.py
"""

from __future__ import annotations

from crewaimeat.memory_tools import make_memory_tools

from crewai import Agent, Task

from crewaimeat.aimeat_crew import BuildContext, CrewSpec, run_crew
from crewaimeat.crew import _web_tools  # Tavily web search if TAVILY_API_KEY is set, else []

AGENT_NAME = "editorial-writer"

README = '''[[FIGLET:slant]["Editorial Writer"]]

Gonzo-journalism editorial writer in the style of Spider Jerusalem — brutal, sharp, unapologetic. Reads the day's articles from owner memory and forges them into a single scorched-earth daily editorial.

**How to task me:** Run with a prompt containing the date (e.g. "2026-06-03") and edition label (e.g. "morning"). I'll pull every article keyed `news.<date>.<edition>.article.<category>`, synthesize them, and publish the editorial to `news.<date>.<edition>.editorial` plus update `news.index`. No articles? I stop — no fabrications.
'''


def build_domain(ctx):
    # ── Agents ──────────────────────────────────────────────────────────

    article_reader = Agent(
        role="Article Reader",
        goal="Read all article keys for the given date and edition from owner memory. Return the full set of articles, or signal that none exist.",
        backstory=(
            "You are a meticulous archival researcher. Your only job is to pull raw material from memory — "
            "nothing more, nothing less. You never fabricate, never guess. If a key is missing, you say so plainly."
        ),
        llm=ctx.llm,
        tools=[*make_memory_tools(AGENT_NAME)],
    )

    editorial_writer = Agent(
        role="Gonzo Editorialist",
        goal=(
            "Write a savage, razor-sharp daily editorial in the gonzo-journalism tradition of Spider Jerusalem. "
            "Brutal honesty, caustic wit, zero corporate polish. Your voice is unmistakable."
        ),
        backstory=(
            "You are Spider Jerusalem reborn — a gonzo journalist who treats every editorial as a Molotov cocktail. "
            "You take the day's articles and twist them into a single, blistering column that makes readers laugh, "
            "wince, and think. You never hedge. You never bore. You write like the city is on fire and you're the "
            "only one with a working pen."
        ),
        llm=ctx.llm,
    )

    publisher = Agent(
        role="Publisher",
        goal=(
            "Write the completed editorial to the public-visible key and update the news index. "
            "Ensure the index entry contains date, edition, and all categories found."
        ),
        backstory=(
            "You are the final gatekeeper. You take the finished editorial and publish it where the world can see it, "
            "then update the index so the editorial is discoverable. You are precise and methodical."
        ),
        llm=ctx.llm,
        tools=[*make_memory_tools(AGENT_NAME)],
    )

    # ── Tasks ─────────────────────────────────────────────────────────

    read_articles = Task(
        description=(
            f"{ctx.today}\n\n"
            "Read all article keys from owner memory matching the pattern "
            "`news.<date>.<edition>.article.<category>` using list_memory with prefix "
            "`news.<date>.` to discover what editions and categories exist.\n\n"
            "For each discovered article key, read its full content with read_memory.\n\n"
            "If NO article keys exist at all, STOP and return exactly: NO_ARTICLES_FOUND\n\n"
            "Otherwise, return a structured summary of every article you found, including:\n"
            "- The full key for each article\n"
            "- The category name\n"
            "- The full text of each article\n\n"
            "Do NOT fabricate any content. Only return what you actually read from memory."
        ),
        agent=article_reader,
        expected_output=(
            "Either the string NO_ARTICLES_FOUND, or a structured collection of all articles "
            "with their keys, categories, and full text."
        ),
    )

    write_editorial = Task(
        description=(
            f"{ctx.today}\n\n"
            "You are Spider Jerusalem. Write a gonzo-journalism editorial that synthesizes ALL the articles "
            "provided by the Article Reader into a single, devastating daily column.\n\n"
            "Style rules:\n"
            "- Brutal, sharp, unapologetic — no corporate hedging, no both-sides cowardice\n"
            "- Strong first-person voice; you have opinions and you share them like grenades\n"
            "- Caustic wit, vivid imagery, the occasional profanity where it earns its place\n"
            "- Weave between articles naturally — find the threads that connect them\n"
            "- Open with a hook that grabs by the throat; close with a line that lingers\n"
            "- This is GONZO journalism: subjective, immersive, literary, angry\n\n"
            "If the previous task returned NO_ARTICLES_FOUND, output exactly: NO_ARTICLES_FOUND\n\n"
            "Otherwise, write the full editorial as plain text. No metadata headers — just the column."
        ),
        agent=editorial_writer,
        context=[read_articles],
        expected_output=(
            "Either NO_ARTICLES_FOUND, or the complete gonzo editorial as a single text block."
        ),
    )

    publish_editorial = Task(
        description=(
            f"{ctx.today}\n\n"
            "Take the editorial written by the Gonzo Editorialist and publish it.\n\n"
            "If the editorial is NO_ARTICLES_FOUND, do nothing and return: NO_ARTICLES_FOUND\n\n"
            "Otherwise:\n"
            "1. Write the editorial to key `news.<date>.<edition>.editorial` with visibility='public' "
            "using write_memory.\n"
            "2. Read the current `news.index` key (if it exists).\n"
            "3. Update the index with an entry containing: date, edition, and list of categories "
            "from the articles that were read. Append to existing entries if the index already exists.\n"
            "4. Write the updated index back to `news.index` with visibility='public'.\n\n"
            "Return a confirmation of what was published: the editorial key, the index entry added, "
            "and the categories included."
        ),
        agent=publisher,
        context=[read_articles, write_editorial],
        expected_output=(
            "Confirmation of publication: editorial key written, index updated with date/edition/categories. "
            "Or NO_ARTICLES_FOUND if no articles existed."
        ),
    )

    agents = [article_reader, editorial_writer, publisher]
    tasks = [read_articles, write_editorial, publish_editorial]

    return (agents, tasks)


def run() -> None:
    run_crew(CrewSpec(agent_name=AGENT_NAME, build_domain=build_domain, readme_md=README, temperature=0.7))


if __name__ == "__main__":
    run()
