"""exchange-composer — a DECLARATIVE crew. Its definition is DATA in crew_defs/exchange_composer.json.

Generated by crew-forge (crewaimeat.forge_json). Agents, tasks, tools, temperature, identity and offer
all live in the JSON — validated before this ever ran live, never exec'd Python. Edit the JSON to change
the crew; this loader stays as-is. See crewaimeat.crew_def.

Run: uv run python crews/exchange_composer_crew.py
"""

from __future__ import annotations

from pathlib import Path

from crewaimeat.aimeat_crew import run_crew
from crewaimeat.crew_def import build_domain_from_json, crewspec_from_json, load_crew_doc

AGENT_NAME = "exchange-composer"
_DOC_PATH = Path(__file__).resolve().parent.parent / "crew_defs" / "exchange_composer.json"


def build_domain(ctx):
    """Interpret this crew's JSON definition into (agents, tasks). Kept module-level so the fleet
    validator (crewaimeat._validate_crew) and any direct caller work exactly as for a Python crew."""
    return build_domain_from_json(load_crew_doc(_DOC_PATH), ctx)


def run() -> None:
    run_crew(crewspec_from_json(load_crew_doc(_DOC_PATH)))


if __name__ == "__main__":
    run()
