"""finnish-corporate-researcher: generated by crew-forge on the AIMEAT scaffold (crewaimeat).

Only build_domain below is crew-specific; crewaimeat.aimeat_crew.run_crew provides the
AIMEAT wiring (onboarding, daemon, liaison publish/complete, live progress, date
injection). See SCAFFOLD_CANON.md. Register + approve before running:
  npx aimeat@latest connect add --agent finnish-corporate-researcher --mode task-runner --url https://aimeat.io --owner <your-aimeat-account>

Run: uv run python crews/finnish_corporate_researcher_crew.py
"""

from __future__ import annotations

from crewai import Agent, Task

from crewaimeat.aimeat_crew import BuildContext, CrewSpec, run_crew
from crewaimeat.crew import _web_tools  # Tavily web search if TAVILY_API_KEY is set, else []

AGENT_NAME = "finnish-corporate-researcher"

README = '''[[FIGLET:slant]["Finnish Corporate Researcher"]]

Deep-dive public-source research on Finnish companies — extracts data from asiakastieto.fi, kauppalehti.fi/yritykset, finder.fi, ytj.fi, prh.fi, vainu.io, proff.fi, LinkedIn, Glassdoor, Indeed, Duunitori, Crunchbase, company blogs, Finnish media (Kauppalehti, Talouselämä, Tivi, HS, Yle), Reddit/r/Suomi, and Suomi24. Returns structured findings with source URLs for every fact. Handles Y-tunnus-based lookups, financials, management, employee sentiment, funding rounds, and synthesis.

**How to task me:** Provide a company name, Y-tunnus (e.g. 1234567-8), or a research question about a Finnish company. I'll return a structured report with sourced facts.
'''


def build_domain(ctx):
    from datetime import date

    # ── Agent 1: Y-tunnus & Registry Lookup Specialist ──────────────────────
    agent_registry_lookup = Agent(
        role="Finnish Corporate Registry Researcher",
        goal=(
            "Resolve a Finnish company's identity using its Y-tunnus or name. "
            "Pull foundational data from ytj.fi, prh.fi (Patentti- ja rekisterihallitus), "
            "and finder.fi: company name, Y-tunnus, business ID status, line of business "
            "(toimiala), registered address, date of incorporation, legal form, and key "
            "registrar notes. Every fact must include a source URL."
        ),
        backstory=(
            "You are a meticulous Finnish corporate registry specialist. You know the structure "
            "of the Finnish Business Information System (ytj.fi) and the PRH trade register by heart. "
            "You always start with the Y-tunnus because it is the authoritative key. You cross-check "
            "PRH data against finder.fi summaries. You never state a fact without a verifiable URL. "
            "You handle edge cases: merged companies, dormant entities, and name changes."
        ),
        llm=ctx.llm,
        tools=_web_tools(),
    )

    # ── Agent 2: Financial & Funding Data Extractor ─────────────────────────
    agent_financials = Agent(
        role="Finnancial & Funding Analyst",
        goal=(
            "Extract financial data and funding history for a Finnish company. "
            "Pull from kauppalehti.fi/yritykset, talouselama.fi, asiakastieto.fi, "
            "proff.fi, vainu.io, crunchbase.com, and the company's own investor relations pages. "
            "Capture: revenue, profit/loss, balance sheet totals, key ratios, funding rounds "
            "(amount, date, investors), and credit ratings. Every figure must have a source URL."
        ),
        backstory=(
            "You are a Finnish financial data analyst with deep knowledge of where Finnish companies "
            "disclose their numbers. You know that asiakastieto.fi holds official financial statements "
            "filed with the PRH, that kauppalehti.fi/yritykset aggregates key figures, and that "
            "Crunchbase and Vainu track startup funding. You always note the fiscal year for every "
            "number and flag when data is estimated vs. audited."
        ),
        llm=ctx.llm,
        tools=_web_tools(),
    )

    # ── Agent 3: People, Culture & Sentiment Researcher ──────────────────────
    agent_people_sentiment = Agent(
        role="People & Sentiment Researcher",
        goal=(
            "Research the management team, key personnel, and employee/customer sentiment for a "
            "Finnish company. Pull from LinkedIn, Glassdoor, Indeed, Duunitori, the company's "
            "own website (team / about pages), Kauppalehti, Talouselämä, Tivi, HS, Yle, "
            "Reddit r/Suomi, and Suomi24. Capture: CEO and board members, employee count, "
            "Glassdoor/Indeed ratings, notable news sentiment, and any public controversies. "
            "Every claim must include a source URL."
        ),
        backstory=(
            "You are a people-intelligence researcher focused on the Finnish market. You know that "
            "LinkedIn profiles give management structure, Glassdoor and Indeed reveal employee "
            "sentiment, Duunitori is the go-to for Finnish job market data, and Finnish media "
            "(Kauppalehti, Talouselämä, Tivi, HS, Yle) cover executive moves and corporate news. "
            "Reddit r/Suomi and Suomi24 forums often surface candid employee and customer opinions. "
            "You always distinguish between verified facts and anecdotal sentiment."
        ),
        llm=ctx.llm,
        tools=_web_tools(),
    )

    # ── Agent 4: Synthesis & Structured Report Compiler ─────────────────────
    agent_synthesis = Agent(
        role="Corporate Research Synthesis Lead",
        goal=(
            "Compile all findings from the registry, financials, and people/sentiment researchers "
            "into a single, well-structured Finnish corporate research report. "
            "The report must be organized by topic, include every source URL, note data gaps, "
            "and end with a confidence assessment. This is the final published deliverable."
        ),
        backstory=(
            "You are the lead analyst who assembles multi-source corporate dossiers. You merge "
            "structured data from three specialist researchers into a coherent narrative. You "
            "organize by sections: Company Identity, Financials & Funding, People & Sentiment, "
            "and Overall Assessment. You never drop a source URL. You flag contradictions "
            "between sources and note when data is missing or stale. Your report is the "
            "authoritative output the end user reads."
        ),
        llm=ctx.llm,
        tools=_web_tools(),
    )

    # ── Tasks ──────────────────────────────────────────────────────────────────

    task_registry = Task(
        description=(
            f"{ctx.today} — Research target: {ctx.prompt}\n\n"
            "Step 1: Identify the company's Y-tunnus (business ID) if not already provided. "
            "Search ytj.fi, prh.fi, and finder.fi.\n"
            "Step 2: Extract and return the following fields with source URLs:\n"
            "  - Company name (current and former names)\n"
            "  - Y-tunnus\n"
            "  - Status (active / merged / dissolved / dormant)\n"
            "  - Date of incorporation\n"
            "  - Legal form (Oy, Osuuskunta, Ay, etc.)\n"
            "  - Registered address\n"
            "  - Line of business / industry (TOL/TOIMIALA code and description)\n"
            "  - Auditor (if listed)\n"
            "  - Any PRH notes or flags\n\n"
            "Format as a structured list. Every fact MUST have a source URL on the same line."
        ),
        agent=agent_registry_lookup,
        expected_output=(
            "A structured list of company identity and registry fields, each with a source URL."
        ),
    )

    task_financials = Task(
        description=(
            f"{ctx.today} — Research target: {ctx.prompt}\n\n"
            "Using the company identity from the registry task, extract financial and funding data.\n"
            "Search: kauppalehti.fi/yritykset, talouselama.fi, asiakastieto.fi, proff.fi, "
            "vainu.io, crunchbase.com, and the company's own investor relations / annual report pages.\n\n"
            "Extract and return:\n"
            "  - Revenue (last 3 fiscal years if available)\n"
            "  - Operating profit / loss\n"
            "  - Balance sheet total\n"
            "  - Key ratios (equity ratio, ROI if available)\n"
            "  - Credit rating (if any, e.g. from asiakastieto)\n"
            "  - Funding rounds (date, amount, lead investors, round type)\n"
            "  - Notable M&A activity\n\n"
            "Format as a structured list. Every figure MUST have a source URL and the fiscal year/date."
        ),
        agent=agent_financials,
        context=[task_registry],
        expected_output=(
            "A structured list of financial figures and funding events, each with a source URL and date."
        ),
    )

    task_people_sentiment = Task(
        description=(
            f"{ctx.today} — Research target: {ctx.prompt}\n\n"
            "Using the company identity from the registry task, research people and sentiment data.\n"
            "Search: LinkedIn, Glassdoor, Indeed, Duunitori, the company's own website, "
            "Kauppalehti, Talouselämä, Tivi, HS, Yle, Reddit r/Suomi, Suomi24.\n\n"
            "Extract and return:\n"
            "  - CEO and key management (name, title, LinkedIn URL if found)\n"
            "  - Board of directors (names and roles)\n"
            "  - Employee count (latest figure and source)\n"
            "  - Glassdoor rating and number of reviews (if available)\n"
            "  - Indeed rating (if available)\n"
            "  - Notable news articles (headline, source, date, URL)\n"
            "  - Employee/customer sentiment themes from Reddit r/Suomi and Suomi24\n"
            "  - Any public controversies or legal issues\n\n"
            "Format as a structured list. Every claim MUST have a source URL."
        ),
        agent=agent_people_sentiment,
        context=[task_registry],
        expected_output=(
            "A structured list of people data, sentiment indicators, and notable mentions, each with a source URL."
        ),
    )

    task_synthesis = Task(
        description=(
            f"{ctx.today} — Research target: {ctx.prompt}\n\n"
            "You are the synthesis lead. Compile ALL findings from the three research tasks below "
            "into a single, authoritative Finnish corporate research report.\n\n"
            "Structure the report as follows:\n\n"
            "# [Company Name] — Corporate Research Report\n"
            f"*Research date: {date.today().isoformat()}*\n"
            f"*Query: {ctx.prompt}*\n\n"
            "## 1. Company Identity & Registry\n"
            "(All registry fields with source URLs)\n\n"
            "## 2. Financials & Funding\n"
            "(All financial figures and funding events with source URLs and dates)\n\n"
            "## 3. People & Sentiment\n"
            "(Management, board, employee data, ratings, news, sentiment themes with source URLs)\n\n"
            "## 4. Data Gaps & Limitations\n"
            "(What could not be found, stale data warnings, access limitations)\n\n"
            "## 5. Confidence Assessment\n"
            "(Overall confidence in the report: High / Medium / Low, with reasoning)\n\n"
            "## 6. Source Index\n"
            "(Numbered list of all source URLs referenced in the report)\n\n"
            "Rules:\n"
            "- Every factual claim must have a source URL inline.\n"
            "- Flag any contradictions between sources.\n"
            "- If a section has no data, state 'No public data found' rather than omitting it.\n"
            "- This is the final published deliverable — make it polished and complete."
        ),
        agent=agent_synthesis,
        context=[task_registry, task_financials, task_people_sentiment],
        expected_output=(
            "A complete, structured Finnish corporate research report with all sections, "
            "source URLs for every fact, data gaps noted, and a confidence assessment."
        ),
    )

    agents = [agent_registry_lookup, agent_financials, agent_people_sentiment, agent_synthesis]
    tasks = [task_registry, task_financials, task_people_sentiment, task_synthesis]

    return (agents, tasks)


def run() -> None:
    # Factual registry research — run cool to stay grounded.
    run_crew(CrewSpec(agent_name=AGENT_NAME, build_domain=build_domain, readme_md=README, temperature=0.25))


if __name__ == "__main__":
    run()
