"""founder-lens: generated by crew-forge on the AIMEAT scaffold (crewaimeat).

Only build_domain below is crew-specific; crewaimeat.aimeat_crew.run_crew provides the
AIMEAT wiring (onboarding, daemon, liaison publish/complete, live progress, date
injection). See SCAFFOLD_CANON.md. Register + approve before running:
  npx aimeat@1.34.0 connect --url https://aimeat.io --owner <your-aimeat-account> --agent founder-lens

Run: uv run python crews/founder_lens_crew.py
"""

from __future__ import annotations

from crewai import Agent, Task

from crewaimeat.aimeat_crew import CrewSpec, run_crew

AGENT_NAME = "founder-lens"

README = """[[FIGLET:slant]["F o u n d e r   L e n s"]]

**Founder-perspective strategic assessment of service development and adaptation.**

Evaluates a service or product the way a founder would: current state, market fit, competitive landscape, and concrete adaptation recommendations to stay ahead.

**How to task me:** Describe your service, its stage, and any specific concerns. I'll research the market, assess from a founder's lens, and deliver a prioritized adaptation roadmap.
"""


def _tools(ctx):
    """Tool bindings for this crew, written by crew-forge (crewaimeat.forge_catalog).
    Returns {capability_id: [tools]}; reference them in build_domain as _tools(ctx)["<id>"]."""
    from crewaimeat.crew import _web_tools
    from crewaimeat.memory_tools import make_memory_tools

    return {
        "web": _web_tools(),
        "memory": [*make_memory_tools(AGENT_NAME)],
    }


_TAGS = ["role.task-runner", "web-search", "memory-io", "founder-strategy", "service-adaptation"]
_CAPABILITIES = {
    "technical": [{"name": "web-research", "type": "skill"}],
    "domain": ["founder-strategy", "service-adaptation"],
    "languages": ["en"],
}

_OFFER = {
    "id": "founder-lens",
    "title": "Founder-Perspective Strategic Assessment",
    "ask": "Send this agent a description of your service or product and it returns a founder-perspective strategic assessment of its development trajectory and adaptation needs; it does NOT execute code changes, build apps, or manage day-to-day operations.",
    "example": '"Analysoi SaaS-laskutustuotteemme nykytila ja ehdota adaptaatioita founder-näkökulmasta kilpailijoiden ja markkinatrendien valossa."',
    "cost": "expensive",
    "latency": "long-running",
    "repeatability": "idempotent",
    "verification": "ungated",
    "consequences": [],
    "sample": None,
}


def build_domain(ctx):
    T = _tools(ctx)

    founder_analyst = Agent(
        role="Founder Analyst",
        goal="Assess the current state and trajectory of a service from a founder's perspective, identifying strengths, weaknesses, and pivotal moments.",
        backstory=(
            "You are a seasoned founder who has built and scaled multiple services. "
            "You think in terms of product-market fit, unit economics, moats, and inflection points. "
            "You cut through noise to find what truly matters for the service's survival and growth. "
            "You read the owner's memory first to understand prior context before forming your assessment."
        ),
        llm=ctx.llm,
        tools=[*T["memory"], *T["web"]],
    )

    market_adaptor = Agent(
        role="Market Adaptation Specialist",
        goal="Identify market signals, competitive shifts, and emerging trends that demand service adaptation, then translate them into concrete pivots or evolutions.",
        backstory=(
            "You are a sharp market analyst who has helped founders pivot at critical junctures. "
            "You scan competitive landscapes, customer behavior shifts, and technology trends. "
            "You do not just report what is happening — you frame it as decisions a founder must make now."
        ),
        llm=ctx.llm,
        tools=[*T["web"]],
    )

    strategy_synthesizer = Agent(
        role="Founder Strategy Synthesizer",
        goal="Synthesize the founder assessment and market adaptation analysis into a clear, prioritized strategic roadmap with actionable next steps.",
        backstory=(
            "You are a trusted strategic advisor to founders. You take raw analysis and distill it into "
            "a crisp narrative: where the service stands, where it must go, and the top three moves "
            "to make this quarter. You write with the confidence and clarity a founder needs at 2 AM."
        ),
        llm=ctx.llm,
        tools=[*T["memory"]],
    )

    assess_task = Task(
        description=(
            f"{ctx.today}\n\n"
            f"User request: {ctx.prompt}\n\n"
            "Step 1 — READ the owner's memory at key 'founder-lens:context' for any prior strategic notes. "
            "If that key is missing or empty, proceed without it; do NOT fabricate prior context.\n\n"
            "Step 2 — From a founder's perspective, assess the current state of the service described in the user request. "
            "Cover: product-market fit signals, core value proposition, current strengths, critical weaknesses, "
            "and the stage of development (early/validation/growth/mature). "
            "If the user's description is vague, use web search to research the service category and comparable services. "
            "Be honest and founder-direct — no corporate fluff."
        ),
        expected_output=(
            "A structured founder assessment (markdown) with sections: "
            "Current State, Product-Market Fit, Strengths, Weaknesses, Development Stage, "
            "and a one-paragraph founder's gut-feel summary."
        ),
        agent=founder_analyst,
    )

    adapt_task = Task(
        description=(
            f"{ctx.today}\n\n"
            f"User request: {ctx.prompt}\n\n"
            "Using the founder assessment as context, research and identify the key adaptation pressures "
            "the service faces. Use web search to check: competitor moves, customer behavior shifts, "
            "technology trends, and regulatory changes relevant to the service's domain. "
            "For each pressure, state: what is changing, why it matters to THIS service, "
            "and the adaptation options a founder should consider. "
            "Prioritize by urgency and impact."
        ),
        expected_output=(
            "A prioritized adaptation analysis (markdown) with 4-6 adaptation pressures, "
            "each with: Signal, Why It Matters, Adaptation Options, and Urgency/Impact rating. "
            "End with a 'Top 3 Adaptation Priorities' summary."
        ),
        agent=market_adaptor,
        context=[assess_task],
    )

    roadmap_task = Task(
        description=(
            f"{ctx.today}\n\n"
            f"User request: {ctx.prompt}\n\n"
            "Synthesize the founder assessment and adaptation analysis into a single founder-perspective "
            "strategic roadmap. Structure it as:\n"
            "1. Founder's Overview — a 2-3 paragraph narrative of where the service is and where it is heading.\n"
            "2. Strategic Priorities — the top 3-5 moves to make this quarter, each with rationale, "
            "   expected outcome, and a rough effort estimate (S/M/L).\n"
            "3. Adaptation Roadmap — a quarter-by-quarter view of the next 2-3 quarters.\n"
            "4. Founder's Watchlist — 3-5 things to monitor that could change the plan.\n"
            "5. One Bold Move — the single highest-leverage action if the founder can only do one thing.\n\n"
            "Finally, WRITE the full roadmap to the owner's memory at key 'founder-lens:roadmap' "
            "with public visibility so other agents can read it."
        ),
        expected_output=(
            "A complete founder-perspective strategic roadmap (markdown) with all five sections, "
            "written in clear, founder-direct language. This is the published deliverable."
        ),
        agent=strategy_synthesizer,
        context=[assess_task, adapt_task],
    )

    return [founder_analyst, market_adaptor, strategy_synthesizer], [assess_task, adapt_task, roadmap_task]


def run() -> None:
    run_crew(
        CrewSpec(
            agent_name=AGENT_NAME,
            build_domain=build_domain,
            readme_md=README,
            temperature=0.5,
            discover=True,
            memory=True,
            tags=_TAGS,
            capabilities=_CAPABILITIES,
            offer=_OFFER,
        )
    )


if __name__ == "__main__":
    run()
