"""idea-feasibility-rater: generated by crew-forge on the AIMEAT scaffold (crewaimeat).

Only build_domain below is crew-specific; crewaimeat.aimeat_crew.run_crew provides the
AIMEAT wiring (onboarding, daemon, liaison publish/complete, live progress, date
injection). See SCAFFOLD_CANON.md. Register + approve before running:
  npx aimeat@latest connect add --agent idea-feasibility-rater --mode task-runner --url https://aimeat.io --owner <your-aimeat-account>

Run: uv run python crews/idea_feasibility_rater_crew.py
"""

from __future__ import annotations

from crewai import Agent, Task

from crewaimeat.aimeat_crew import BuildContext, CrewSpec, run_crew
from crewaimeat.crew import _web_tools  # Tavily web search if TAVILY_API_KEY is set, else []

AGENT_NAME = "idea-feasibility-rater"


def build_domain(ctx):
    agents = [
        Agent(
            role="Idea Analyst",
            goal="Thoroughly dissect the user's idea to understand its core concept, context, and intended outcomes. Identify key assumptions and surface-level strengths and weaknesses.",
            backstory="A seasoned strategist with a background in both startup incubation and corporate innovation. Known for asking the 'dumb' questions that reveal the critical flaws everyone else missed.",
            llm=ctx.llm,
        ),
        Agent(
            role="Market & Reality Checker",
            goal="Investigate the current landscape relevant to the idea. Identify real-world competitors, market trends, technological feasibility, and regulatory hurdles using web search.",
            backstory="A data-driven researcher who lives on industry reports and competitor analysis. Believes that no idea exists in a vacuum and that 'it's been tried before' is the most important phrase in business.",
            llm=ctx.llm,
            tools=_web_tools(),
        ),
        Agent(
            role="Brutally Honest Evaluator",
            goal="Synthesize the analysis and research into a final feasibility verdict. Provide a clear rating, list the top risks and opportunities, and deliver a final recommendation with actionable next steps.",
            backstory="A no-nonsense consultant who has seen a thousand pitches. Has a reputation for being the bearer of bad news, but always provides a clear path forward. Celebrates genuinely great ideas with enthusiasm.",
            llm=ctx.llm,
        ),
    ]

    task_0 = Task(
        description=(
            f"Analyze the following idea and its context: {ctx.prompt}\n\n"
            "Break it down into its core components: the problem it solves, the proposed solution, the target audience, and the key assumptions being made. "
            "Do not judge feasibility yet; just provide a clear, structured summary of the idea's anatomy."
        ),
        agent=agents[0],
        expected_output="A structured breakdown of the idea's core components.",
    )

    task_1 = Task(
        description=(
            f"Given the idea analysis from the previous task, conduct a thorough reality check. "
            "Use web search to find: "
            "1. Existing competitors or similar solutions. "
            "2. Current market trends that support or contradict the idea. "
            "3. Any obvious technological, legal, or logistical hurdles. "
            "4. The general sentiment or demand for such a solution."
        ),
        agent=agents[1],
        context=[task_0],
        expected_output="A report on the external factors affecting the idea's viability.",
    )

    task_2 = Task(
        description=(
            f"Synthesize the idea analysis and the reality check into a final, brutally honest feasibility assessment. "
            "Your output MUST follow this exact structure:\n\n"
            "### Feasibility Score: [Score]/10\n"
            "(A single number representing the overall feasibility)\n\n"
            "### Top 3 Risks:\n"
            "(The three most critical threats to the idea's success)\n\n"
            "### Top 3 Opportunities:\n"
            "(The three most compelling reasons this could work)\n\n"
            "### Final Verdict & Next Steps:\n"
            "- If the idea is highly feasible (8+), celebrate! Explain why it's brilliant and suggest how to capitalize on the momentum.\n"
            "- If the idea has potential but needs work (4-7), provide 1-3 concrete, actionable options to improve it and increase its feasibility.\n"
            "- If the idea is not feasible (1-3), be kind but clear. Explain the fundamental flaws and suggest a pivot or a completely different approach.\n\n"
            "Be direct, honest, and constructive."
        ),
        agent=agents[2],
        context=[task_0, task_1],
        expected_output="The final feasibility report with a score, risks, opportunities, and a clear path forward.",
    )

    tasks = [task_0, task_1, task_2]

    return agents, tasks


def run() -> None:
    # Feasibility analysis — a little reasoning latitude (balanced).
    run_crew(CrewSpec(agent_name=AGENT_NAME, build_domain=build_domain, temperature=0.5))


if __name__ == "__main__":
    run()
