"""idea-feasibility-rater: generated by crew-forge on the AIMEAT scaffold (crewaimeat).

Only build_domain below is crew-specific; crewaimeat.aimeat_crew.run_crew provides the
AIMEAT wiring (onboarding, daemon, liaison publish/complete, live progress, date
injection). See SCAFFOLD_CANON.md. Register + approve before running:
  npx aimeat@latest connect add --agent idea-feasibility-rater --mode task-runner --url https://aimeat.io --owner <your-aimeat-account>

Run: uv run python crews/idea_feasibility_rater_crew.py
"""

from __future__ import annotations

from crewai import Agent, Task

from crewaimeat.aimeat_crew import BuildContext, CrewSpec, run_crew
from crewaimeat.crew import _web_tools  # Tavily web search if TAVILY_API_KEY is set, else []

AGENT_NAME = "idea-feasibility-rater"


def build_domain(ctx):
    agents = []
    tasks = []

    # --- Agents ---

    analyst = Agent(
        role="Idea Analyst",
        goal="Deconstruct the user's idea into its core components, assumptions, and context to prepare a structured brief for evaluation.",
        backstory="You are a sharp, methodical analyst who strips away fluff and identifies the true mechanics of any idea—business, creative, or otherwise. You never judge; you only map.",
        llm=ctx.llm,
        tools=_web_tools(),
    )
    agents.append(analyst)

    critic = Agent(
        role="Brutal Honesty Critic",
        goal="Evaluate the idea with ruthless honesty. Identify risks, feasibility gaps, and opportunities. Rate feasibility on a 1-10 scale and explain why.",
        backstory="You are a no-nonsense evaluator who has seen a thousand ideas fail. You don't sugarcoat. You find the cracks, the blind spots, and the hidden strengths. Your honesty is a gift, not an insult.",
        llm=ctx.llm,
        tools=_web_tools(),
    )
    agents.append(critic)

    enhancer = Agent(
        role="Idea Enhancer",
        goal="Propose 1-3 concrete options to improve the idea if it's not perfect. If the idea is already excellent, celebrate it genuinely and explain why it works.",
        backstory="You are a creative problem-solver who loves making good ideas great and great ideas legendary. You offer practical, actionable paths forward—not vague encouragement. When something is truly brilliant, you say so with enthusiasm.",
        llm=ctx.llm,
        tools=_web_tools(),
    )
    agents.append(enhancer)

    # --- Tasks ---

    task_analyze = Task(
        description=(
            f"{ctx.today}\n\n"
            "Analyze the following idea presented by the user. Break it down into:\n"
            "1. Core concept (what is the idea in one sentence)\n"
            "2. Context (business, creative, personal, etc.)\n"
            "3. Key assumptions the idea relies on\n"
            "4. What success would look like\n"
            "5. Any obvious surface-level strengths or weaknesses\n\n"
            "User's idea:\n"
            f"{ctx.prompt}\n\n"
            "Provide a structured analysis brief."
        ),
        agent=analyst,
        expected_output="A structured analysis brief covering the 5 points above.",
    )
    tasks.append(task_analyze)

    task_evaluate = Task(
        description=(
            f"{ctx.today}\n\n"
            "Using the analysis brief, evaluate this idea with brutal honesty. Cover:\n"
            "1. Feasibility rating (1-10) with clear justification\n"
            "2. Top 3-5 risks (be specific and realistic)\n"
            "3. Top 3-5 opportunities or hidden strengths\n"
            "4. Key assumptions that could break the idea\n"
            "5. A blunt verdict: is this idea worth pursuing as-is?\n\n"
            "Be honest, not mean. The user wants truth, not comfort."
        ),
        agent=critic,
        context=[task_analyze],
        expected_output="A brutally honest evaluation with feasibility rating, risks, opportunities, and a clear verdict.",
    )
    tasks.append(task_evaluate)

    task_enhance = Task(
        description=(
            f"{ctx.today}\n\n"
            "Based on the analysis and evaluation, produce the final deliverable for the user:\n\n"
            "If the idea has significant gaps or risks:\n"
            "- Propose 1-3 concrete, actionable options to improve the idea\n"
            "- For each option, explain what problem it solves and what it adds\n"
            "- Rank the options by impact vs. effort\n\n"
            "If the idea is already strong and feasible:\n"
            "- Celebrate it! Explain specifically why it works\n"
            "- Suggest 1-2 ways to make it even better or scale it\n\n"
            "Format the output clearly so the user can immediately understand their idea's standing and next steps.\n\n"
            "This is the final published output—make it polished, direct, and useful."
        ),
        agent=enhancer,
        context=[task_analyze, task_evaluate],
        expected_output="The final deliverable: a clear verdict on the idea with improvement options (1-3) or a celebration of a great idea, formatted for immediate user value.",
    )
    tasks.append(task_enhance)

    return (agents, tasks)


def run() -> None:
    run_crew(CrewSpec(agent_name=AGENT_NAME, build_domain=build_domain))


if __name__ == "__main__":
    run()
