"""jingle-writer: generated by crew-forge on the AIMEAT scaffold (crewaimeat).

Only build_domain below is crew-specific; crewaimeat.aimeat_crew.run_crew provides the
AIMEAT wiring (onboarding, daemon, liaison publish/complete, live progress, date
injection). See SCAFFOLD_CANON.md. Register + approve before running:
  npx aimeat@latest connect add --agent jingle-writer --mode task-runner --url https://aimeat.io --owner <your-aimeat-account>

Run: uv run python crews/jingle_writer_crew.py
"""

from __future__ import annotations

from crewai import Agent, Task

from crewaimeat.aimeat_crew import BuildContext, CrewSpec, run_crew
from crewaimeat.crew import _web_tools  # Tavily web search if TAVILY_API_KEY is set, else []

AGENT_NAME = "jingle-writer"

README = '''[[FIGLET:slant]["Jingle Writer"]]

Writes short, catchy rhyming jingles (4–6 lines) for marketing videos.

**How to task me:** Describe your product, brand, or campaign and I'll craft a memorable, rhyming jingle ready for your video ad.
'''


def build_domain(ctx):
    from crewai import Agent, Task

    # ── Agents ──────────────────────────────────────────────────────

    market_researcher = Agent(
        role="Market Researcher",
        goal="Uncover the key selling points, target audience, and emotional hooks for the product or brand described in the user's request.",
        backstory="You are a seasoned market researcher who specializes in distilling brands down to their most compelling, jingle-worthy angles. You know what makes consumers remember a product.",
        llm=ctx.llm,
        tools=_web_tools(),
    )

    lyric_brainstormer = Agent(
        role="Lyric Brainstormer",
        goal="Generate multiple short rhyming concepts and hook lines based on the research findings, exploring different rhyme schemes and rhythms.",
        backstory="You are a creative wordsmith with a knack for catchy phrases. You love playing with rhyme, rhythm, and wordplay to make ideas stick in people's heads.",
        llm=ctx.llm,
    )

    jingle_composer = Agent(
        role="Jingle Composer",
        goal="Select the best brainstormed concept and polish it into a final 4–6 line rhyming jingle optimized for a marketing video.",
        backstory="You are a professional jingle writer with years of experience crafting memorable ad tunes. You know how to turn a rough hook into a tight, catchy, brand-aligned jingle that sings.",
        llm=ctx.llm,
    )

    # ── Tasks ───────────────────────────────────────────────────────

    research_task = Task(
        description=(
            f"{ctx.today}\n\n"
            "Research the product, brand, or campaign described here:\n\n"
            f"{ctx.prompt}\n\n"
            "Identify:\n"
            "1. The top 2–3 selling points or unique features.\n"
            "2. The target audience and the emotions to evoke.\n"
            "3. Any brand name, tagline, or key phrase that must appear.\n"
            "4. Comparable jingles or ad campaigns for inspiration.\n\n"
            "Return a concise research brief."
        ),
        agent=market_researcher,
        expected_output="A concise research brief with selling points, target audience, emotional hooks, mandatory phrases, and inspirational references.",
    )

    brainstorm_task = Task(
        description=(
            "Using the research brief from the previous task, brainstorm at least 3 distinct rhyming jingle concepts. "
            "Each concept should be 4–6 lines, use a different rhyme scheme or rhythm, and incorporate the key selling points "
            "and brand phrases identified in the research. Label each concept (A, B, C…) and note its rhyme pattern."
        ),
        agent=lyric_brainstormer,
        expected_output="At least 3 labeled rhyming jingle concepts (4–6 lines each) with noted rhyme patterns.",
        context=[research_task],
    )

    compose_task = Task(
        description=(
            f"{ctx.today}\n\n"
            "Review the brainstormed jingle concepts from the previous task and select the strongest one. "
            "Polish it into a final 4–6 line rhyming jingle for a marketing video. "
            "Ensure it:\n"
            "- Flows naturally when read aloud\n"
            "- Includes the brand/product name or key phrase\n"
            "- Evokes the target emotion\n"
            "- Has a consistent rhyme scheme\n\n"
            "Output ONLY the final jingle text, no commentary."
        ),
        agent=jingle_composer,
        expected_output="A polished, catchy 4–6 line rhyming jingle ready for a marketing video.",
        context=[brainstorm_task],
    )

    # ── Return ──────────────────────────────────────────────────────

    agents = [market_researcher, lyric_brainstormer, jingle_composer]
    tasks = [research_task, brainstorm_task, compose_task]

    return (agents, tasks)


def run() -> None:
    # Jingles are a creative service — enforce a warm temperature (no per-task classification needed).
    run_crew(CrewSpec(agent_name=AGENT_NAME, build_domain=build_domain, readme_md=README, temperature=0.7))


if __name__ == "__main__":
    run()
