"""news-writer: generated by crew-forge on the AIMEAT scaffold (crewaimeat).

Only build_domain below is crew-specific; crewaimeat.aimeat_crew.run_crew provides the
AIMEAT wiring (onboarding, daemon, liaison publish/complete, live progress, date
injection). See SCAFFOLD_CANON.md. Register + approve before running:
  npx aimeat@latest connect add --agent news-writer --mode task-runner --url https://aimeat.io --owner <your-aimeat-account>

Run: uv run python crews/news_writer_crew.py
"""

from __future__ import annotations

from crewaimeat.memory_tools import make_memory_tools

from crewai import Agent, Task

from crewaimeat.aimeat_crew import BuildContext, CrewSpec, run_crew
from crewaimeat.crew import _web_tools  # Tavily web search if TAVILY_API_KEY is set, else []

AGENT_NAME = "news-writer"

README = '''[[FIGLET:slant]["News Writer"]]

Multi-category Finnish news writer that reads raw material from owner memory and rewrites each category into original Finnish articles written in own words.

**How to task me:** Provide the date and edition (e.g. "2026-06-03 morning") and ensure raw material is stored under `news.<date>.<edition>.raw.<category>` keys. Articles are published to `news.<date>.<edition>.article.<category>` keys.
'''


def build_domain(ctx):
    raw_reader = Agent(
        role="Raw Material Reader",
        goal="Read raw news material from owner memory keys and validate availability before rewriting begins.",
        backstory="A meticulous Finnish newsroom archivist who checks that raw material exists for each category and extracts it faithfully. Never fabricates or guesses — if a key is missing, that category is skipped entirely.",
        llm=ctx.llm,
        tools=[*make_memory_tools(AGENT_NAME)],
    )

    politics_writer = Agent(
        role="Finnish Politics News Writer",
        goal="Rewrite raw Finnish political news material into an original, engaging article written entirely in Finnish and in own words.",
        backstory="A seasoned Finnish political journalist with a sharp, analytical yet accessible writing style. Specializes in domestic and EU politics, known for clear prose that makes complex policy understandable to everyday readers.",
        llm=ctx.llm,
        tools=[*make_memory_tools(AGENT_NAME)],  # needs write_memory to publish its article key
    )

    business_writer = Agent(
        role="Finnish Business & Economy News Writer",
        goal="Rewrite raw Finnish business and economy news material into an original, insightful article written entirely in Finnish and in own words.",
        backstory="An experienced Finnish business reporter with a talent for translating market data and corporate developments into compelling narratives. Writing style is precise, data-informed, and reader-friendly.",
        llm=ctx.llm,
        tools=[*make_memory_tools(AGENT_NAME)],  # needs write_memory to publish its article key
    )

    culture_writer = Agent(
        role="Finnish Culture & Lifestyle News Writer",
        goal="Rewrite raw Finnish culture, arts, and lifestyle news material into an original, vibrant article written entirely in Finnish and in own words.",
        backstory="A creative Finnish culture correspondent with a warm, evocative writing voice. Covers arts, entertainment, sports, and lifestyle with enthusiasm and a distinctly Finnish perspective.",
        llm=ctx.llm,
        tools=[*make_memory_tools(AGENT_NAME)],  # needs write_memory to publish its article key
    )

    editor = Agent(
        role="Finnish News Editor",
        goal="Review all rewritten Finnish news articles for quality, consistency, and completeness. Compile a final summary of which categories were published and which were skipped.",
        backstory="A detail-oriented Finnish news editor who ensures every article meets publication standards. Produces a clear summary report listing all published article keys and any skipped categories.",
        llm=ctx.llm,
        tools=[*make_memory_tools(AGENT_NAME)],
    )

    task_read_raw = Task(
        description=(
            f"{ctx.today} — {ctx.prompt}\n\n"
            "Read raw news material from owner memory. For each expected category (e.g. politics, business, culture, sports, science), "
            "attempt to read the key pattern: news.<date>.<edition>.raw.<category>.\n\n"
            "INSTRUCTIONS:\n"
            "1. Use list_memory(prefix='news.') to discover available raw keys.\n"
            "2. For each raw key found, use read_memory(key) to fetch the content.\n"
            "3. If a raw key is missing for a category, SKIP that category — never fabricate content.\n"
            "4. Return a structured summary: for each available category, provide the category name and the full raw content.\n"
            "5. Also list which categories were skipped due to missing keys."
        ),
        agent=raw_reader,
        expected_output="A structured summary listing each available category with its raw content, plus a list of skipped categories.",
    )

    task_write_politics = Task(
        description=(
            f"{ctx.today} — Write an original Finnish news article for the POLITICS category.\n\n"
            "INSTRUCTIONS:\n"
            "1. Read the raw politics material provided in context.\n"
            "2. Rewrite it into a completely original Finnish article in your own words — do not copy phrases verbatim.\n"
            "3. Write in the style of a seasoned Finnish political journalist: sharp, analytical, accessible.\n"
            "4. Use write_memory(key='news.<date>.<edition>.article.politics', value=<your article>, visibility='public') to publish.\n"
            "5. If no politics raw material was available, skip and note it."
        ),
        agent=politics_writer,
        context=[task_read_raw],
        expected_output="The politics article text and confirmation of the memory key written, or a note that it was skipped.",
    )

    task_write_business = Task(
        description=(
            f"{ctx.today} — Write an original Finnish news article for the BUSINESS / ECONOMY category.\n\n"
            "INSTRUCTIONS:\n"
            "1. Read the raw business material provided in context.\n"
            "2. Rewrite it into a completely original Finnish article in your own words — do not copy phrases verbatim.\n"
            "3. Write in the style of an experienced Finnish business reporter: precise, data-informed, reader-friendly.\n"
            "4. Use write_memory(key='news.<date>.<edition>.article.business', value=<your article>, visibility='public') to publish.\n"
            "5. If no business raw material was available, skip and note it."
        ),
        agent=business_writer,
        context=[task_read_raw],
        expected_output="The business article text and confirmation of the memory key written, or a note that it was skipped.",
    )

    task_write_culture = Task(
        description=(
            f"{ctx.today} — Write an original Finnish news article for the CULTURE / LIFESTYLE category.\n\n"
            "INSTRUCTIONS:\n"
            "1. Read the raw culture material provided in context.\n"
            "2. Rewrite it into a completely original Finnish article in your own words — do not copy phrases verbatim.\n"
            "3. Write in the style of a creative Finnish culture correspondent: warm, evocative, distinctly Finnish.\n"
            "4. Use write_memory(key='news.<date>.<edition>.article.culture', value=<your article>, visibility='public') to publish.\n"
            "5. If no culture raw material was available, skip and note it."
        ),
        agent=culture_writer,
        context=[task_read_raw],
        expected_output="The culture article text and confirmation of the memory key written, or a note that it was skipped.",
    )

    task_editor_review = Task(
        description=(
            f"{ctx.today} — Review all rewritten Finnish news articles and compile a publication summary.\n\n"
            "INSTRUCTIONS:\n"
            "1. Use list_memory(prefix='news.<date>.<edition>.article.') to find all published article keys.\n"
            "2. Read each published article with read_memory(key) to verify content quality.\n"
            "3. Compile a final summary report listing:\n"
            "   - All successfully published article keys and their categories\n"
            "   - Any categories that were skipped due to missing raw material\n"
            "   - A brief quality note on each article\n"
            "4. Write the summary report using write_memory(key='news.<date>.<edition>.summary', value=<report>, visibility='public')."
        ),
        agent=editor,
        context=[task_write_politics, task_write_business, task_write_culture],
        expected_output="A complete publication summary report listing all published articles, skipped categories, and quality notes, stored in memory.",
    )

    agents = [raw_reader, politics_writer, business_writer, culture_writer, editor]
    tasks = [task_read_raw, task_write_politics, task_write_business, task_write_culture, task_editor_review]

    return (agents, tasks)


def run() -> None:
    run_crew(CrewSpec(agent_name=AGENT_NAME, build_domain=build_domain, readme_md=README, temperature=0.7))


if __name__ == "__main__":
    run()
