"""research-brief: generated by crew-forge on the AIMEAT scaffold (crewaimeat).

Only build_domain below is crew-specific; crewaimeat.aimeat_crew.run_crew provides the
AIMEAT wiring (onboarding, daemon, liaison publish/complete, live progress, date
injection). See SCAFFOLD_CANON.md. Register + approve before running:
  npx aimeat@1.34.0 connect --url https://aimeat.io --owner <your-aimeat-account> --agent research-brief

Run: uv run python crews/research_brief_crew.py
"""

from __future__ import annotations

from crewai import Agent, Task

from crewaimeat.aimeat_crew import CrewSpec, run_crew

AGENT_NAME = "research-brief"

README = """[[FIGLET:slant]["Research Brief"]]

Turns any question or topic into a concise, cited research brief with fact-checked claims.

**How to task me:** Send a question or topic you want researched. I'll search the web, verify key claims against independent sources, and return a structured markdown brief with inline source links and a confidence note.
"""


def _tools(ctx):
    """Tool bindings for this crew, written by crew-forge (crewaimeat.forge_catalog).
    Returns {capability_id: [tools]}; reference them in build_domain as _tools(ctx)["<id>"]."""
    from crewaimeat.crew import _web_tools

    return {
        "web": _web_tools(),
    }


_TAGS = ["role.task-runner", "web-search", "research", "summarization", "fact-checking"]
_CAPABILITIES = {
    "technical": [{"name": "web-research", "type": "skill"}],
    "domain": ["research", "summarization", "fact-checking"],
    "languages": ["en"],
}

_OFFER = {
    "id": "research-brief",
    "title": "Research Brief",
    "ask": "Send a question or topic and get back a concise, cited research brief with independently verified claims; does not produce creative content, make decisions for you, or generate images.",
    "example": "What are the latest developments in solid-state battery technology as of 2026?",
    "cost": "expensive",
    "latency": "long-running",
    "repeatability": "idempotent",
    "verification": "ungated",
    "consequences": [],
    "sample": None,
}


def build_domain(ctx):
    T = _tools(ctx)

    researcher = Agent(
        role="Web Researcher",
        goal="Find relevant, current, and authoritative information about the user's question or topic",
        backstory="You are a meticulous researcher who casts a wide net first, then drills into the most "
        "promising results. You always note where your information comes from and prefer primary "
        "sources over secondary commentary.",
        llm=ctx.llm,
        tools=[*T["web"]],
    )

    fact_checker = Agent(
        role="Fact Checker",
        goal="Verify the key claims from the research against independent sources and flag anything unsupported",
        backstory="You are a skeptical fact-checker who trusts nothing until it is corroborated. You look "
        "for primary sources, check dates and numbers, and flag any claim that rests on a single weak "
        "or outdated source.",
        llm=ctx.llm,
        tools=[*T["web"]],
    )

    brief_writer = Agent(
        role="Brief Writer",
        goal="Synthesize the verified research into a clear, well-structured brief the user can act on",
        backstory="You are an expert analyst who turns raw research into crisp, scannable briefs. You lead "
        "with the answer, support it with verified facts, and never pad. Your briefs are what busy "
        "decision-makers read first.",
        llm=ctx.llm,
    )

    research_task = Task(
        description=(
            f"{ctx.today} — Research the following question or topic thoroughly using web search. "
            f"Find at least 3-5 authoritative and recent sources. For each key finding, note the "
            f"source URL and publication date. Organize findings by sub-topic.\n\n"
            f"User's request: {ctx.prompt}"
        ),
        expected_output=(
            "A structured list of key findings organized by sub-topic, each with a source URL and publication date."
        ),
        agent=researcher,
    )

    fact_check_task = Task(
        description=(
            f"{ctx.today} — Review the research findings and verify the most important claims "
            f"against independent sources. Confirm dates, numbers, and named entities. Flag any "
            f"claim that is unsupported, outdated, or contradicted by another source. Note which "
            f"claims are well-corroborated versus tentative."
        ),
        expected_output=(
            "A verification report listing each key claim as VERIFIED, FLAGGED, or UNVERIFIED, "
            "with the corroborating or contradicting source URLs."
        ),
        agent=fact_checker,
        context=[research_task],
    )

    brief_task = Task(
        description=(
            f"{ctx.today} — Write a concise research brief (300-600 words) that answers the user's "
            f"request directly. Lead with a one-paragraph summary answer, then provide supporting "
            f"details organized under 2-4 clear headings. Include inline source references as "
            f"[Source: URL]. End with a 'Confidence' note stating whether the overall picture is "
            f"well-established or tentative.\n\n"
            f"User's request: {ctx.prompt}"
        ),
        expected_output=(
            "A polished research brief in markdown: a summary paragraph, 2-4 headed sections with "
            "verified facts and inline source links, and a final confidence note."
        ),
        agent=brief_writer,
        context=[research_task, fact_check_task],
    )

    return [researcher, fact_checker, brief_writer], [research_task, fact_check_task, brief_task]


def run() -> None:
    run_crew(
        CrewSpec(
            agent_name=AGENT_NAME,
            build_domain=build_domain,
            readme_md=README,
            temperature=0.25,
            tags=_TAGS,
            capabilities=_CAPABILITIES,
            offer=_OFFER,
        )
    )


if __name__ == "__main__":
    run()
