"""tagline-translator: generated by crew-forge on the AIMEAT scaffold (crewaimeat).

Only build_domain below is crew-specific; crewaimeat.aimeat_crew.run_crew provides the
AIMEAT wiring (onboarding, daemon, liaison publish/complete, live progress, date
injection). See SCAFFOLD_CANON.md. Register + approve before running:
  npx aimeat@latest connect add --agent tagline-translator --mode task-runner --url https://aimeat.io --owner <your-aimeat-account>

Run: uv run python crews/tagline_translator_crew.py
"""

from __future__ import annotations

from crewai import Agent, Task

from crewaimeat.aimeat_crew import BuildContext, CrewSpec, run_crew
from crewaimeat.crew import _web_tools  # Tavily web search if TAVILY_API_KEY is set, else []

AGENT_NAME = "tagline-translator"


def build_domain(ctx):
    # --- Agents ---
    tagline_analyzer = Agent(
        role="Tagline Analyst",
        goal="Break down the user's English marketing tagline to identify core message, tone, brand voice, and any idioms or wordplay that need special handling in translation.",
        backstory="You are a seasoned marketing linguist who specializes in dissecting short-form brand copy. You know that a great tagline translation starts with understanding what makes the original work — its rhythm, emotional punch, and cultural references — before a single word is translated.",
        llm=ctx.llm,
        tools=_web_tools(),
    )

    french_translator = Agent(
        role="French Tagline Translator",
        goal="Produce a natural, idiomatic French translation of the marketing tagline that preserves the original's tone, brevity, and emotional impact.",
        backstory="You are a native-French copywriter with years of experience adapting international brand slogans for the French market. You prioritize elegance, cultural resonance, and natural phrasing over literal translation. You know when to adapt idioms and when to invent fresh phrasing that captures the spirit of the original.",
        llm=ctx.llm,
        tools=_web_tools(),
    )

    german_translator = Agent(
        role="German Tagline Translator",
        goal="Produce a natural, idiomatic German translation of the marketing tagline that preserves the original's tone, brevity, and emotional impact.",
        backstory="You are a native-German copywriter who has localized campaigns for global brands into German-speaking markets. You understand that German taglines often benefit from compound-word creativity and directness, and you know how to keep translations punchy without losing the brand's voice.",
        llm=ctx.llm,
        tools=_web_tools(),
    )

    quality_reviewer = Agent(
        role="Bilingual Quality Reviewer",
        goal="Review both the French and German translations side by side, flag any issues with tone, idiom naturalness, or brand consistency, and deliver a polished final output with both translations and brief rationale.",
        backstory="You are a senior localization QA specialist who reviews multilingual marketing copy for global launches. You compare translations against the original brief and each other to ensure neither language version feels like an afterthought. You deliver clean, client-ready output with concise notes on translation choices.",
        llm=ctx.llm,
        tools=_web_tools(),
    )

    # --- Tasks ---
    analysis_task = Task(
        description=(
            f"{ctx.today}\n\n"
            "Analyze the following English marketing tagline provided by the user:\n\n"
            f"{ctx.prompt}\n\n"
            "Identify: (1) the core message and value proposition, (2) the tone (e.g. playful, premium, urgent), "
            "(3) any idioms, puns, or cultural references that won't translate literally, "
            "(4) the desired emotional response from the audience, and "
            "(5) any constraints (character count, brand name to keep in English, etc.). "
            "Output a structured analysis that the translators can use as a brief."
        ),
        agent=tagline_analyzer,
        expected_output="A structured analysis of the tagline covering core message, tone, idioms/references, emotional goal, and constraints.",
    )

    french_task = Task(
        description=(
            f"{ctx.today}\n\n"
            "Using the tagline analysis brief, translate the original English tagline into French. "
            "Prioritize natural, idiomatic French phrasing that preserves the original's tone and emotional impact. "
            "If the original uses wordplay or an idiom, adapt it creatively rather than translating literally. "
            "Keep it concise — taglines should be short and memorable. "
            "Provide the French translation along with a brief note explaining any key adaptation choices."
        ),
        agent=french_translator,
        context=[analysis_task],
        expected_output="A polished French tagline translation with a short rationale for key adaptation choices.",
    )

    german_task = Task(
        description=(
            f"{ctx.today}\n\n"
            "Using the tagline analysis brief, translate the original English tagline into German. "
            "Prioritize natural, idiomatic German phrasing that preserves the original's tone and emotional impact. "
            "If the original uses wordplay or an idiom, adapt it creatively rather than translating literally. "
            "Keep it concise — taglines should be short and memorable. "
            "Provide the German translation along with a brief note explaining any key adaptation choices."
        ),
        agent=german_translator,
        context=[analysis_task],
        expected_output="A polished German tagline translation with a short rationale for key adaptation choices.",
    )

    review_task = Task(
        description=(
            f"{ctx.today}\n\n"
            "Review the French and German tagline translations produced by the translators, "
            "alongside the original analysis brief. Check for:\n"
            "- Tone consistency with the original English tagline\n"
            "- Naturalness and idiomatic quality in each language\n"
            "- Any brand names or proper nouns handled correctly\n"
            "- Overall brevity and punchiness\n\n"
            "If either translation needs a tweak, note it. Then deliver the final output containing:\n"
            "1. The original English tagline\n"
            "2. The final French translation with rationale\n"
            "3. The final German translation with rationale\n"
            "4. A brief overall quality note"
        ),
        agent=quality_reviewer,
        context=[french_task, german_task],
        expected_output="The final deliverable: original English tagline, polished French and German translations each with rationale, and an overall quality note.",
    )

    agents = [tagline_analyzer, french_translator, german_translator, quality_reviewer]
    tasks = [analysis_task, french_task, german_task, review_task]

    return (agents, tasks)


def run() -> None:
    run_crew(CrewSpec(agent_name=AGENT_NAME, build_domain=build_domain))


if __name__ == "__main__":
    run()
