"""web-researcher: generated by crew-forge on the AIMEAT scaffold (crewaimeat).

Only build_domain below is crew-specific; crewaimeat.aimeat_crew.run_crew provides the
AIMEAT wiring (onboarding, daemon, liaison publish/complete, live progress, date
injection). See SCAFFOLD_CANON.md. Register + approve before running:
  npx aimeat@latest connect add --agent web-researcher --mode task-runner --url https://aimeat.io --owner <your-aimeat-account>

Run: uv run python crews/web_researcher_crew.py
"""

from __future__ import annotations

from crewai import Agent, Task

from crewaimeat.aimeat_crew import CrewSpec, contract_record_spaces, record_event_targets, run_crew
from crewaimeat.contract_adopt import build_adopt_domain, is_adopt_task
from crewaimeat.crew import _web_tools  # free SearXNG web search by default (USE_TAVILY=1 for Tavily)
from crewaimeat.research_contract import CONTRACT

AGENT_NAME = "web-researcher"

README = """[[FIGLET:slant]["Web Researcher"]]

Performs live web searches to find recent articles, reports, and news on a given topic, producing sourced summaries with proper citations (publication name, URL, date). Claims without sources are flagged as "not verified".

**How to task me:** Give me a topic or question and I'll research it live, returning a concise summary with citations.
"""


def build_domain(ctx):
    """Build a web research crew that searches for recent articles, reports, and news on a given topic,
    producing sourced summaries with proper citations."""
    if is_adopt_task(ctx.task):  # UI "Adopt contract" chip -> provision the ADOPTED contract's spaces
        # web-researcher serves THREE contracts; stamp the spaces with the contract named in scope.contract
        # (§7c / audit point 4), not a hardcoded one — else a market-scan/company-research adopt would stamp
        # its spaces as 'research' and granular per-contract Retire would break.
        from crewaimeat.company_contract import CONTRACT as _CO
        from crewaimeat.contract_adopt import task_scope
        from crewaimeat.market_contract import CONTRACT as _MK

        _by_id = {CONTRACT["id"]: CONTRACT, _MK["id"]: _MK, _CO["id"]: _CO}
        _contract = _by_id.get(task_scope(ctx.task).get("contract"), CONTRACT)
        return build_adopt_domain(ctx, AGENT_NAME, _contract)

    # --- Agents ---

    search_agent = Agent(
        role="Web Search Specialist",
        goal="Perform targeted web searches to find recent, relevant articles, reports, and news on the given topic. Gather raw search results with URLs, publication names, and dates.",
        backstory="You are an expert web researcher with a talent for crafting precise search queries and quickly identifying high-quality, recent sources. You always note the publication name, URL, and date of every source you find. You use _web_tools() to perform live searches.",
        llm=ctx.llm,
        tools=_web_tools(),
    )

    verification_agent = Agent(
        role="Source Verifier",
        goal="Cross-check claims and facts found by the search agent against the gathered sources. Flag any claim that cannot be corroborated by a found source as 'not verified'. Ensure every cited claim has a matching source.",
        backstory="You are a meticulous fact-checker who never lets an unsourced claim slip through. You compare each claim against the actual search results and clearly mark anything that lacks a verifiable source as 'not verified'.",
        llm=ctx.llm,
        tools=_web_tools(),
    )

    summary_writer = Agent(
        role="Research Summary Writer",
        goal="Produce a clear, concise sourced summary of the research findings. Every factual claim must include a citation (publication name, URL, date). Claims without sources must be explicitly flagged as 'not verified'.",
        backstory="You are a skilled technical writer who specializes in turning raw research into polished, well-cited summaries. You always include proper citations and are transparent about what cannot be verified.",
        llm=ctx.llm,
    )

    # --- Tasks ---

    search_task = Task(
        description=(
            f"Research date context: {ctx.today}\n\n"
            "Search the web for recent articles, reports, and news on the following topic:\n\n"
            f"{ctx.prompt}\n\n"
            "Perform multiple searches using different query angles to ensure broad coverage. "
            "For each source found, record: the article/report title, publication name, URL, and publication date. "
            "Focus on sources published within the last 12 months when possible. "
            "Return a structured list of all sources found with their metadata, plus a brief note on key findings from each."
        ),
        agent=search_agent,
        expected_output="A structured list of sources (title, publication, URL, date) with key findings from each.",
    )

    verify_task = Task(
        description=(
            f"Research date context: {ctx.today}\n\n"
            "Review the search results and any claims made. For each claim or fact, verify it against the actual sources found. "
            "If a claim has a matching source, confirm it. If a claim cannot be matched to any found source, flag it as 'not verified'. "
            "Return the verified/flagged list of claims alongside the source references."
        ),
        agent=verification_agent,
        context=[search_task],
        expected_output="A list of claims each marked as verified (with source) or 'not verified'.",
    )

    summary_task = Task(
        description=(
            f"Research date context: {ctx.today}\n\n"
            "Using the search results and verification report, write a concise sourced summary on the topic:\n\n"
            f"{ctx.prompt}\n\n"
            "Structure the summary as follows:\n"
            "1. **Overview** – 2-3 sentence high-level summary.\n"
            "2. **Key Findings** – Bullet points of the most important findings, each with a citation in the format: "
            "(Publication Name, URL, Date).\n"
            "3. **Unverified Claims** – Any claims that could not be verified, explicitly flagged as 'not verified'.\n"
            "4. **Sources** – A numbered list of all sources consulted (Title, Publication, URL, Date).\n\n"
            "Ensure every factual claim in the summary has a corresponding citation. "
            "If no source supports a claim, flag it as 'not verified'."
        ),
        agent=summary_writer,
        context=[search_task, verify_task],
        expected_output="A complete sourced research summary with citations, unverified claims flagged, and a sources list.",
    )

    agents = [search_agent, verification_agent, summary_writer]
    tasks = [search_task, verify_task, summary_task]

    return (agents, tasks)


def run() -> None:
    # adapt_to_task: research tasks classify as 'fact' -> cool temp (0.15) + grounding rule (no invented
    # specifics, honest "not found") + a final faithfulness-verify pass over the summary before publish,
    # on top of the crew's own Source Verifier. score_to_stats: keep the self-verify as introspection.
    #
    # Event-driven (aimeat-crewai 0.7.0): a pushed request record (or the catch-up on connect) wakes us,
    # across all THREE of this agent's contracts — research, market-scan, company-research. Each process_*
    # is a DETERMINISTIC scan that fulfils any pending requests (the CHECK uses NO LLM; the LLM runs only to
    # distil a request that actually exists). No idle polling — idle minutes cost zero tokens.
    from crewaimeat.company_contract import CONTRACT as COMPANY_CONTRACT
    from crewaimeat.company_contract import process_company_research
    from crewaimeat.market_contract import CONTRACT as MARKET_CONTRACT
    from crewaimeat.market_contract import process_market_scans
    from crewaimeat.research_contract import process_research_requests

    # targets scopes every scan to the event's OWN workspace (no member rediscovery/full re-scan per
    # event). The event may be for any of the three spaces; the non-matching scans just read that one
    # workspace's (usually empty) space and dedupe — bounded and cheap.
    def _on_record(event) -> None:
        targets = record_event_targets(event)
        res = process_research_requests(max_items=3, targets=targets)
        if res.get("processed") or res.get("failed"):
            print(f"[{AGENT_NAME}] research-contract event: {res}")
        scans = process_market_scans(max_items=2, targets=targets)  # SECOND contract: market-scan
        if scans.get("processed") or scans.get("failed"):
            print(f"[{AGENT_NAME}] market-scan event: {scans}")
        cos = process_company_research(max_items=3, targets=targets)  # THIRD contract: company-research
        if cos.get("processed") or cos.get("failed"):
            print(f"[{AGENT_NAME}] company-research event: {cos}")

    run_crew(
        CrewSpec(
            agent_name=AGENT_NAME,
            build_domain=build_domain,
            readme_md=README,
            adapt_to_task=True,
            score_to_stats=True,
            discover=True,  # researcher: survey what already exists on the node before researching
            listen_for=("tasks", "records"),
            record_spaces=lambda: contract_record_spaces(AGENT_NAME, CONTRACT, MARKET_CONTRACT, COMPANY_CONTRACT),
            on_record=_on_record,
        )
    )


if __name__ == "__main__":
    run()
